#!/usr/bin/env python3
"""
Github-Rest MCP Connector
Auto-generated by Pure Agentic Pipeline v1.1

JSON-RPC server for Github-Rest operations.
Category: api_saas

DO NOT EDIT - This file is auto-generated. Make changes to the spec instead.
Generated: 2026-06-19T14:11:28.695382
"""

import sys
import os
import logging
from typing import Dict, Any, List, Optional, Union
import json
from datetime import datetime
import requests

# Add parent directory for base_connector imports
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from base_connector import (
    BaseMCPConnector,
    PaginationHandler,
    ApiHandler,
    StorageHandler,
    DatabaseHandler,
    ExportResult,
    ImportResult,
    ErrorItem,
    RateLimitHandler,
    RESPONSE_DATA_KEYS,
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Pagination safety caps (overrideable per-call)
DEFAULT_MAX_PAGES = 10
DEFAULT_MAX_RECORDS = 10000


class GithubRestConnector(BaseMCPConnector):
    # The spec-declared endpoint. Hoisted to a constant because
    # configure_from_connection must be able to RESET base_url — not merely
    # set it — and therefore needs a value to reset TO. See the comment there.
    SPEC_BASE_URL = 'https://api.github.com'

    """MCP Server for Github-Rest"""

    # =========================================================================
    # RETRY / RATE-LIMIT POLICY (visible per-connector tunables)
    # =========================================================================
    # BaseMCPConnector._make_request_v2 uses these settings to drive retries.
    # Retries trigger on:
    #   - HTTP 429 (rate-limited): respects the Retry-After header when present,
    #     otherwise applies exponential backoff
    #   - HTTP 5xx (transient server errors): exponential backoff
    #   - Network/connection errors: exponential backoff
    # Other 4xx codes are NOT retried (they're user errors).
    #
    # Tuning advice: lower RATE_LIMIT_RPS for APIs with strict per-second
    # limits (Shopify GraphQL cost-based throttling, Stripe 100 req/s in
    # test mode). Raise MAX_RETRIES for unreliable upstreams.
    RATE_LIMIT_RPS = 10.0
    MAX_RETRIES = 3


    def __init__(self):
        # MUST call super().__init__() first
        super().__init__()

        # Apply connector-specific retry / rate-limit policy. This overrides
        # the env-driven defaults set by BaseMCPConnector.__init__ so the
        # tuning is per-connector (not per-deployment-env).
        self._rate_limiter = RateLimitHandler(
            requests_per_second=self.RATE_LIMIT_RPS,
            max_retries=self.MAX_RETRIES,
        )

        # REQUIRED: Set connector metadata
        self.connector_type = "github-rest"
        self.connector_category = "api_saas"
        self.supports_source = True
        self.supports_destination = False
        self.supports_cdc = False
        
        # Capability Stats
        self.supported_formats = ['json']
        self.max_batch_size = 10000
        
        # API Configuration
        # `os.getenv(k) or default`, NOT `os.getenv(k, default)`: for a
        # SET-but-empty var (some Dockerfiles bake `ENV MCP_BASE_URL=""` as an
        # operator override slot) the two-arg form returns "", because the
        # default applies only when the var is UNSET. "" is falsy, so every
        # request would fall through to whatever base_url the last connection
        # left on this shared instance. See KI-RESTMCP-STICKY-BASE-URL.
        self.base_url = os.getenv('MCP_BASE_URL') or self.SPEC_BASE_URL
        # IMPORTANT: For API connectors using API keys or bearer tokens, we keep auth_type="none"
        # and explicitly set the auth header in _get_headers().
        #
        # Why:
        # - BaseMCPConnector will otherwise auto-inject Authorization: Bearer <token> when auth_type="api_key"
        # - Many APIs use custom headers like X-API-Key; that causes duplicate auth headers and 400/401 errors
        self.auth_type = "none"

        # Initialize API handler for contract-driven operations
        self._api_handler = ApiHandler(
            connector=self,
            pagination_type="none",
            pagination_param="",
            limit_param="limit",
            max_page_size=100,
            rate_limit_rps=10.0,
        )

        self.log("Github-Rest MCP Server initialized")
    
    # =========================================================================
    # CONFIGURATION HELPERS
    # =========================================================================
    
    def _get_config(self, params: Dict) -> Dict:
        """Extract and validate configuration from params"""
        config = params.get('config', params) if params else {}
        
        # Apply environment variable defaults

        
        return config
    
    def configure_from_connection(self, connection_config: Dict[str, Any]) -> None:
        """
        Override BaseMCPConnector.configure_from_connection for api_saas connectors.

        Base implementation auto-sets auth_type="api_key" when it sees 'api_key' in config,
        which can cause duplicate auth headers for APIs that use non-Authorization headers.

        We still capture connection_id/base_url/token values, but keep auth_type as defined
        by this generated connector (oauth for oauth2, none for api_key/bearer/basic).
        """
        connection_config = connection_config or {}
        self.connection_id = connection_config.get("id") or connection_config.get("connection_id")

        # Drop the previous connection's auth state before applying this one's.
        # The api_key if/elif below has no else, and the oauth branch returns
        # early without clearing _oauth_token — so on this process-global
        # instance a connection carrying no credential would keep the PREVIOUS
        # tenant's api_key / _oauth_token and authenticate as them. This
        # restores the post-__init__ values, which means auth_type comes back as
        # this generated connector defined it — the very thing overriding the
        # base method exists to preserve. See KI-RESTMCP-STICKY-BASE-URL.
        self._reset_connection_state()
        # Assign on EVERY path — never conditionally. create_http_app() builds
        # ONE connector per process and base_connector re-runs this method on
        # that shared instance for every request, so a guarded write leaves the
        # PREVIOUS connection's base_url standing and the next caller's
        # credential (headers are built from the current config) is sent to
        # that inherited host. connection_id above is already unconditional —
        # this line now matches it. See KI-RESTMCP-STICKY-BASE-URL.
        self.base_url = (
            connection_config.get("base_url")
            or os.getenv('MCP_BASE_URL')
            or self.SPEC_BASE_URL
        )

        # OAuth2 connectors: use base helper to parse token dicts when provided.
        if getattr(self, "auth_type", "") == "oauth":
            if "oauth_token" in connection_config and isinstance(connection_config.get("oauth_token"), dict):
                self.set_oauth_token(connection_config["oauth_token"])
            elif "access_token" in connection_config:
                # Accept a minimal token payload (access_token only) for testing/dev
                self.set_oauth_token({"access_token": connection_config.get("access_token")})
            return

        # For non-oauth connectors, stash token for convenience but do NOT change auth_type.
        if "api_key" in connection_config:
            self.api_key = connection_config.get("api_key") or ""
        elif "access_token" in connection_config:
            self.api_key = connection_config.get("access_token") or ""
        elif "token" in connection_config:
            self.api_key = connection_config.get("token") or ""

    def _get_headers(self, config: Dict) -> Dict[str, str]:
        """Build request headers with authentication"""
        token = (
            config.get('access_token')
            or config.get('token')
            or config.get('api_key')
            or os.getenv('MCP_API_KEY', '')
        )
        header_name = "Authorization"
        # IMPORTANT: header_prefix may be an empty string for APIs like Shopify
        # (e.g., X-Shopify-Access-Token: <token>). Only default to "Bearer" when
        # header_prefix is truly missing/None.
        prefix = "Bearer".strip()
        headers = {
            "Content-Type": "application/json",
            "Accept": "application/json",
        }
        # Only attach auth when a credential is actually present. An empty
        # "Authorization: Bearer" (no token configured) 401s on public endpoints
        # such as GitHub /licenses; omitting the header lets those return 200,
        # while a present token still authenticates exactly as before.
        if token:
            headers[header_name] = f"{prefix} {token}".strip() if prefix else token
        return headers
    
    def _make_request(self, method: str, endpoint: str, config: Dict, 
                      params: Dict = None, data: Dict = None) -> Dict[str, Any]:
        """Legacy request wrapper (dict). Uses BaseMCPConnector._make_request_v2 under the hood."""
        success, status_code, body, resp_headers = self._make_request_v2(
            method=method,
            endpoint=endpoint,
            config=config,
            params=params,
            data=data,
        )
        if not success:
            return {
                "success": False,
                "status_code": status_code,
                "data": body,
                "headers": resp_headers,
                "error": f"HTTP {status_code}",
            }
        return {
            "success": True,
            "status_code": status_code,
            "data": body,
            "headers": resp_headers,
        }

    def _make_request_v2(
        self,
        method: str,
        endpoint: str,
        config: Dict,
        params: Dict = None,
        data: Dict = None,
    ):
        """New request helper: returns (success, status_code, data, headers)."""
        if params and isinstance(params, dict) and params.get("_override_url"):
            url = params.get("_override_url")
            params = {k: v for k, v in params.items() if k != "_override_url"}
        else:
            # Allow per-connection base_url override so QA can run offline against mock servers
            # and operators can point connectors at sandbox/staging endpoints.
            base = (config or {}).get("base_url") or (config or {}).get("url") or self.base_url
            # Substitute {placeholder} path params (e.g. /repos/{owner}/{repo}/commits)
            # from connection config first, then call params. Fail loud rather than
            # send a literal '{owner}' that 404s. Params used for substitution are
            # popped so they aren't also appended as query params.
            if endpoint and "{" in endpoint:
                import re as _re_pp
                _consumed: list = []
                def _sub_path_param(_m):
                    _key = _m.group(1)
                    _val = (config or {}).get(_key)
                    if (_val is None or _val == "") and isinstance(params, dict) and _key in params:
                        _val = params.get(_key)
                        _consumed.append(_key)
                    # Treat None or empty-string as missing — fail loud rather
                    # than build a malformed '/.../' URL segment.
                    if _val is None or _val == "":
                        raise ValueError(
                            f"Missing required path parameter '{_key}' for endpoint '{endpoint}'"
                        )
                    return str(_val)
                endpoint = _re_pp.sub(r"\{([^/{}]+)\}", _sub_path_param, endpoint)
                if _consumed and isinstance(params, dict):
                    params = {k: v for k, v in params.items() if k not in _consumed}
            url = f"{str(base).rstrip('/')}/{endpoint.lstrip('/')}"

        headers = self._get_headers(config)
        return super()._make_request_v2(
            method=method,
            url=url,
            headers=headers,
            params=params,
            json_data=data,
            timeout=30,
        )


    def _coerce_row_count(self, value, default=None):
        """
        Best-effort coercion for item counts from API responses.

        - Returns an int when possible
        - Clamps negative values to 0
        - Returns `default` for missing/unparseable values
        """
        if value is None:
            return default
        try:
            i = int(value)
        except Exception:
            try:
                i = int(float(value))
            except Exception:
                return default
        if i < 0:
            return 0
        return i

    def _extract_total_count(self, body: Any, headers: Dict[str, Any] = None):
        """
        Try to extract a total item count from common API response shapes.

        This is intentionally heuristic and best-effort: many APIs do not expose totals
        without expensive pagination. If we cannot find a clear total, return None.
        """
        # 1) Prefer explicit headers when present (common with REST pagination)
        if headers and isinstance(headers, dict):
            for k in ("x-total-count", "X-Total-Count", "x-total", "X-Total"):
                if k in headers:
                    v = self._coerce_row_count(headers.get(k), default=None)
                    if v is not None:
                        return v

        # 2) JSON bodies with common total fields
        if not isinstance(body, dict):
            return None

        def get_path(d: Dict[str, Any], path: List[str]):
            cur: Any = d
            for p in path:
                if not isinstance(cur, dict) or p not in cur:
                    return None
                cur = cur[p]
            return cur

        candidates: List[List[str]] = [
            # Common top-level totals
            ["total"],
            ["total_count"],
            ["totalCount"],
            ["total_results"],
            ["totalResults"],
            # Common nested totals
            ["meta", "total"],
            ["meta", "total_count"],
            ["meta", "totalCount"],
            ["pagination", "total"],
            ["paging", "total"],
            ["page", "totalElements"],
            ["page", "total_elements"],
            ["result", "total"],
            ["results", "total"],
        ]

        for path in candidates:
            v = get_path(body, path)
            c = self._coerce_row_count(v, default=None)
            if c is not None:
                return c

        return None

    def _extract_first_row(self, body: Any, response_data_key: str = "") -> Optional[Dict[str, Any]]:
        """Find the first record in a list-style REST response.

        REST APIs return list results in wildly different shapes:
          - ``[ {...}, {...} ]``                          (bare array)
          - ``{ "data":    [...] }``                      (Stripe, JSON:API)
          - ``{ "results": [...] }``                      (HubSpot, DRF)
          - ``{ "items":   [...] }``                      (GitHub search)
          - ``{ "value":   [...] }``                      (OData)
          - ``{ "records": [...] }``                      (Salesforce)

        When the vendor spec declares a ``response_data_key`` for this
        resource we honour it first; otherwise we walk the common
        wrapper names. Returns the first item as a dict, or ``None`` if
        we can't find one (used to infer columns when row_count alone
        isn't enough).
        """
        # 1) Bare list response.
        if isinstance(body, list):
            return body[0] if body and isinstance(body[0], dict) else None

        if not isinstance(body, dict):
            return None

        # 2) Honour an explicit response_data_key from the vendor spec.
        if response_data_key:
            cur: Any = body
            for part in response_data_key.split("."):
                if not isinstance(cur, dict) or part not in cur:
                    cur = None
                    break
                cur = cur[part]
            if isinstance(cur, list) and cur and isinstance(cur[0], dict):
                return cur[0]

        # 3) Walk common wrapper names — shared with the runtime paginator via
        # base_connector.RESPONSE_DATA_KEYS so discovery and pagination agree.
        for key in RESPONSE_DATA_KEYS:
            v = body.get(key)
            if isinstance(v, list) and v and isinstance(v[0], dict):
                return v[0]

        return None

    def _infer_columns_from_row(self, row: Optional[Dict[str, Any]]) -> List[Dict[str, str]]:
        """Turn a single record dict into a canonical column list.

        REST has no introspection, so we infer columns from the first
        row of a ``GET ?limit=1`` probe. Each column is emitted with a
        canonical type name (see
        shared/mcp-connectors/schemas/response_schemas.py) so sinks can
        translate to their dialect without per-source knowledge:

          - dict / list values  -> ``"json"`` (stored as JSONB / JSON)
          - bool                -> ``"boolean"``
          - int                 -> ``"integer"``
          - float               -> ``"number"``
          - str                 -> ``"string"``
          - None                -> ``"string"`` (best fallback; the
                                   sink's canonical layer also coerces
                                   "unknown" -> "string")

        ISO-8601 timestamp detection is intentionally NOT done here —
        REST APIs vary too much. Sinks coerce timestamp strings at
        bind time when the column type is declared.

        Returns ``[]`` when row is None, empty, or not a dict.
        """
        if not isinstance(row, dict) or not row:
            return []

        def canonical(v: Any) -> str:
            if v is None:
                return "string"
            if isinstance(v, bool):
                return "boolean"
            if isinstance(v, int):
                return "integer"
            if isinstance(v, float):
                return "number"
            if isinstance(v, str):
                return "string"
            if isinstance(v, (list, dict)):
                return "json"
            return "string"

        return [{"name": str(k), "type": canonical(v)} for k, v in row.items()]

    def _get_resource_config(self, resource: str) -> Dict:
        """Get configuration for a specific API resource"""
        resources = {
            "licenses": {
                "endpoint": "/licenses",
                "supports_incremental": False,
                "incremental_param": "updated_since",
                "incremental_field": "updated_at",
                "pagination_type": "none",
                "pagination_param": "",
                "limit_param": "limit",
                "max_page_size": 100,
                # Deterministic pagination hints (injected by architect_rest from vendor_apis.yaml).
                # PaginationHandler uses these to avoid auto-detection guessing wrong keys.
                "response_data_key": "",
                "cursor_path": "",
                "cursor_mode": "response",
                "id_field": "id",
            },
        }
        return resources.get(resource, {"endpoint": f"/{resource}"})


    
    # =========================================================================
    # CORE OPERATIONS (Required by BaseMCPConnector)
    # =========================================================================
    
    def get_capabilities(self, params: Dict = None) -> Dict[str, Any]:
        """Return connector capabilities with method keys for auto-dispatch."""
        return {
            "success": True,
            "connector_type": self.connector_type,
            "connector_category": self.connector_category,
            "supports_source": self.supports_source,
            "supports_destination": self.supports_destination,
            "supports_cdc": self.supports_cdc,
            "operations": [
                {
                    "name": "test_connection",
                    "method": "github-rest_test_connection",
                    "type": "core",
                    "description": "Test connectivity to the API"
                },
                {
                    "name": "validate_config",
                    "method": "github-rest_validate_config",
                    "type": "core",
                    "description": "Validate connection configuration"
                },
                {
                    "name": "discover_schema",
                    "method": "github-rest_discover_schema",
                    "type": "core",
                    "description": "Discover available resources and their schemas"
                },
                {
                    "name": "get_capabilities",
                    "method": "github-rest_get_capabilities",
                    "type": "core",
                    "description": "Return connector capabilities"
                },
                {
                    "name": "export",
                    "method": "github-rest_export",
                    "type": "source",
                    "description": "Export records from a REST resource with automatic pagination"
                },
                {
                    "name": "licenses",
                    "method": "github-rest_licenses",
                    "type": "source",
                    "description": "Export records from licenses (/licenses)"
                },
            ],
            "capabilities": {
                "max_batch_size": self.max_batch_size,
                "supported_formats": self.supported_formats,
                "supports_cdc": self.supports_cdc
            }
        }
    
    def validate_config(self, params: Dict = None) -> Dict[str, Any]:
        """Validate configuration without connecting."""
        if not params:
            return {"valid": False, "errors": ["No configuration provided"]}
        
        config = self._get_config(params)
        errors = []
        warnings = []

        # Check required fields. Every request is authenticated with a personal
        # access token and metadata.json declares access_token as required, so
        # an absent one is a configuration error. Returning valid=True
        # unconditionally (as this did) was indistinguishable from no check.
        if not self._credentials_present(config) and not os.getenv('MCP_API_KEY'):
            errors.append(
                "access_token is required: supply a GitHub personal access token, "
                "or set MCP_API_KEY in the connector environment."
            )
        
        return {
            "valid": len(errors) == 0,
            "errors": errors,
            "warnings": warnings
        }
    
    # Credential-bearing config keys, used to build an anonymous control probe.
    # Covers the per-connector config key names; the instance-side credential
    # surface is the one BaseMCPConnector enumerates in _CONNECTION_STATE_FIELDS.
    _CREDENTIAL_CONFIG_KEYS = (
        "access_token", "token", "api_key", "apikey", "key", "secret",
        "client_secret", "client_id", "password", "username", "bearer_token",
        "personal_access_token", "private_token", "auth_token",
    )
    _AUTH_HEADER_NAMES = (
        "authorization", "x-api-key", "api-key", "x-auth-token",
        "private-token", "x-access-token",
    )

    def _credentials_present(self, config: Dict) -> bool:
        """True if the caller supplied a credential that still has to be proven.

        Checks this connector's OWN declared auth config_keys first. A hardcoded
        list of common names misses vendor-specific ones -- Notion calls its
        token `integration_token` -- and a credential we fail to notice here is
        a credential that is then never validated at all.
        """
        cfg = config or {}
        for spec in (getattr(self, "SUPPORTED_AUTH_METHODS", None) or {}).values():
            for k in (spec.get("config_keys") or []):
                if cfg.get(k):
                    return True
            if spec.get("query_param") and cfg.get(spec["query_param"]):
                return True
        if cfg.get("username") and cfg.get("password"):
            return True
        return any(cfg.get(k) for k in (
            "access_token", "token", "api_key", "apikey", "bearer_token",
            "personal_access_token", "private_token", "auth_token",
        ))

    def _anonymous_config(self, config: Dict) -> Dict:
        """Copy of `config` with every credential-bearing key removed.

        Prefers this connector's OWN declared auth config_keys, so a
        vendor-specific key name (Notion calls its token `integration_token`)
        is stripped as well; the static list below only fills the gap for
        connectors that declare no auth methods.
        """
        keys = set(self._CREDENTIAL_CONFIG_KEYS)
        for spec in (getattr(self, "SUPPORTED_AUTH_METHODS", None) or {}).values():
            for k in (spec.get("config_keys") or []):
                keys.add(str(k).lower())
            if spec.get("query_param"):
                keys.add(str(spec["query_param"]).lower())
        return {k: v for k, v in (config or {}).items() if k.lower() not in keys}

    def _probe_endpoint_is_public(self, endpoint: str, config: Dict,
                                  params: Dict = None) -> Optional[bool]:
        """Re-issue a successful probe WITHOUT credentials, as a control.

        A 2xx only proves the credentials are valid if the endpoint would have
        REFUSED an anonymous caller. So ask it that question directly:

            True  -> answered 2xx anonymously too: the endpoint is PUBLIC, and
                     the authenticated 2xx proves nothing about the credentials.
            False -> rejected the anonymous request: it IS auth-protected, so
                     the credentials earned the 2xx and are proven valid.
            None  -> inconclusive; the caller must fall back to legacy behaviour.

        Credentials reach a request from three places -- the config dict, an
        env-var fallback, and instance state cached by
        configure_from_connection() -- so all three are neutralised here. The
        two header sets are then diffed to CONFIRM the strip actually worked: if
        the "anonymous" request would still carry auth, its answer is
        meaningless, so return None rather than a confidently wrong verdict.
        """
        anon = self._anonymous_config(config)
        saved_env = {k: os.environ.get(k) for k in ("ALLOW_ENV_CREDENTIALS", "MCP_API_KEY")}
        saved_api_key = getattr(self, "api_key", None)
        saved_oauth = getattr(self, "_oauth_token", None)
        try:
            os.environ["ALLOW_ENV_CREDENTIALS"] = "false"
            os.environ.pop("MCP_API_KEY", None)
            self.api_key = ""
            self._oauth_token = None
            try:
                authed_headers = self._get_headers(config) or {}
                anon_headers = self._get_headers(anon) or {}
            except Exception:
                return None

            def _auth_material(headers):
                out = {}
                for k, v in headers.items():
                    if k.lower() not in self._AUTH_HEADER_NAMES:
                        continue
                    # A credential-free header is not auth material: an empty
                    # token renders as a bare scheme name ("Bearer"), which a
                    # server treats exactly like sending nothing at all.
                    parts = str(v or "").split()
                    if not parts:
                        continue
                    if len(parts) == 1 and parts[0].lower() in ("bearer", "token", "basic"):
                        continue
                    out[k.lower()] = v
                return out

            # Nothing to strip, or the strip changed nothing (query-string auth,
            # an unknown config key, a cached token we cannot see). Either way an
            # anonymous 2xx would be indistinguishable from an authenticated one.
            if not _auth_material(authed_headers):
                return None
            if _auth_material(anon_headers) == _auth_material(authed_headers):
                return None
            try:
                result = self._make_request('GET', endpoint, anon, params=params)
            except Exception:
                return None
        finally:
            for _k, _v in saved_env.items():
                if _v is None:
                    os.environ.pop(_k, None)
                else:
                    os.environ[_k] = _v
            if saved_api_key is not None:
                self.api_key = saved_api_key
            self._oauth_token = saved_oauth

        if result.get("success"):
            return True
        if int(result.get("status_code") or 0) in (401, 403):
            return False
        return None

    def test_connection(self, params: Dict = None) -> Dict[str, Any]:
        """Test connectivity to Github-Rest."""
        config = self._get_config(params)
        
        try:
            # Test API connectivity. A 2xx only proves the credentials are good
            # if the endpoint that produced it would have REFUSED an anonymous
            # caller -- so wherever credentials were supplied, each hit is put
            # to _probe_endpoint_is_public, which re-issues it with them
            # stripped. That control reaches a verdict only when there is auth
            # material on the request to strip. _credentials_present() ends in a
            # generic key list, so a config carrying e.g. personal_access_token
            # counts as credentialed here while _get_headers() sends nothing --
            # the control then returns None WITHOUT a second request, and a
            # whoami 2xx is trusted uncorroborated. Same hole as the template's;
            # neither is closed here.
            #
            # This used to trust a 2xx from any "whoami"-shaped path, on the
            # convention that such paths always require auth. GitHub breaks that
            # convention: /users/me is an ordinary PUBLIC user lookup, so an
            # unvalidated token could pass here. GitHub's real authenticated
            # whoami is GET /user, which is why it is probed first.
            whoami_candidates = [
                "/user",
                "/users/me",
                "/user/me",
                "/me",
                "/whoami",
                "/account",
                "/accounts/me",
                "/profile",
            ]
            # This connector's own listable, path-param-free endpoints. Each of
            # these requires auth on GitHub, so they also cover a token whose
            # scopes are too narrow for /user.
            resource_candidates = [
                "/user/repos",
                "/user/orgs",
                "/notifications",
                "/gists",
                "/issues",
            ]

            creds_present = self._credentials_present(config)
            allow_unauth_pass = not creds_present

            last_err = None
            saw_auth_failure = False
            saw_public_endpoint = False
            probes = (
                [(ep, False) for ep in whoami_candidates]
                + [(ep, True) for ep in resource_candidates if ep]
            )
            for ep, is_resource in probes:
                try:
                    probe_params = {"per_page": 1} if is_resource else None
                    result = self._make_request('GET', ep, config, params=probe_params)
                except Exception as e:
                    last_err = str(e)
                    continue
                if result.get("success"):
                    if allow_unauth_pass:
                        # No credentials supplied: nothing to validate, and
                        # reachability is the whole question.
                        return {
                            "success": True,
                            "message": "Connection successful",
                            "credentials_validated": False,
                        }
                    verdict = self._probe_endpoint_is_public(ep, config, params=probe_params)
                    if verdict is False:
                        # Refused the anonymous caller, so the 2xx was earned.
                        return {
                            "success": True,
                            "message": "Connection successful",
                            "credentials_validated": True,
                        }
                    if verdict is True:
                        saw_public_endpoint = True
                        last_err = "reachable, but the endpoints that answered are public and cannot validate credentials"
                        continue
                    # Inconclusive -- fall back to the historical rule.
                    if not is_resource:
                        return {
                            "success": True,
                            "message": "Connection successful",
                            "credentials_validated": True,
                        }
                    last_err = "reachable but credentials were not validated on an auth-protected endpoint"
                    continue
                code = int(result.get("status_code") or 0)
                if code in (401, 403):
                    # Auth header was received and rejected: credentials are bad.
                    saw_auth_failure = True
                    last_err = result.get("error") or f"HTTP {code}: authentication failed"
                    break
                # Any other non-2xx: this endpoint is not a usable probe here.
                last_err = result.get("error") or f"HTTP {code}"
                continue

            if saw_auth_failure:
                return {"success": False, "error": last_err}
            if saw_public_endpoint:
                # AT LEAST ONE probe that answered was proven public: any single
                # verdict-True sets the flag. The warning text below says "every
                # probe endpoint that responded", which claims more than that --
                # filed in BACKLOG.md, since rewording it changes behaviour.
                return {
                    "success": True,
                    "message": "Connection successful",
                    "credentials_validated": False,
                    "warning": (
                        "Reachable, but the credentials could not be validated: every probe "
                        "endpoint that responded also responds without credentials. Calls to "
                        "auth-protected paths on this API may still fail."
                    ),
                }
            return {
                "success": False,
                "error": f"No probe endpoint confirmed the connection. Last error: {last_err or 'all candidates 404/timed out'}.",
            }
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def discover_schema(self, params: Dict = None) -> Dict[str, Any]:
        """Discover available resources and their schemas."""
        params = params or {}
        config = self._get_config(params)
        
        try:
            include_row_counts = bool(params.get("include_row_counts", True))
            try:
                max_tables = int(params.get("max_tables", 100))
            except Exception:
                max_tables = 100
            if max_tables <= 0:
                max_tables = 100

            # ----------------------------------------------------------------
            # Generic REST discovery contract (matches GraphQL connectors):
            #
            #   1. Auth check first. The connector's `test_connection`
            #      hits a known endpoint with the supplied credentials;
            #      if it fails we return `{success: false, tables: []}`
            #      instead of leaking a hardcoded resource list. This
            #      catches the "user pasted the wrong API key" case at
            #      the table-selection step instead of pipeline runtime.
            #
            #   2. Resource list is baked in from the vendor spec at
            #      generation time — REST has no universal introspection
            #      so we can't enumerate at runtime. Pagination + auth
            #      shape comes from vendor_apis.yaml.
            #
            #   3. For each list-capable resource we issue one cheap
            #      `GET ?limit=1` and extract:
            #        - row_count via _extract_total_count (existing
            #          best-effort total in headers / body wrappers).
            #        - columns via _extract_first_row +
            #          _infer_columns_from_row (top-level keys of the
            #          first record; types inferred from JSON values).
            #
            #   4. Resources for which the probe fails get `columns: []`
            #      and `row_count: -1` (the canonical "unknown"
            #      sentinel the frontend already renders as no badge).
            #      Per-resource failures don't take down the whole
            #      discovery call.
            # ----------------------------------------------------------------
            try:
                auth_check = self.test_connection(config)
            except Exception as auth_exc:
                return {
                    "success": False,
                    "error": f"connection test raised: {auth_exc}",
                    "tables": [],
                    "total_tables": 0,
                }
            if not auth_check.get("success"):
                return {
                    "success": False,
                    "error": "auth check failed: " + str(auth_check.get("error", "unknown")),
                    "tables": [],
                    "total_tables": 0,
                }

            # For API connectors, return predefined resources (optionally augmented with counts + columns)
            resources = [
                {
                    "name": "licenses",
                    "endpoint": "/licenses",
                    "supports_list": True,
                    "pagination_type": "none",
                    "pagination_param": "offset",
                    "limit_param": "limit",
                    "supports_incremental": False,
                    "incremental_param": "updated_since",
                    "incremental_field": "updated_at",
                    "response_data_key": "",
                    "columns": [],
                    "row_count": -1,
                    # PK detection: the vendor spec carries an id_field
                    # per resource (default "id"). If the probe response
                    # exposes that field we declare it as the primary
                    # key so sinks can upsert idempotently on reruns.
                    # Empty until the probe confirms the field exists.
                    "primary_keys": [],
                    "primary_key_source": "synthetic",
                    "id_field": "id",
                    "operations": [
                        "list",
                        "get",
                    ]
                },
            ]

            # One probe per resource: read the first record (for column
            # schema) and the total (for row count). Per-resource
            # failures stay local — one bad endpoint must not take down
            # the whole catalog.
            if include_row_counts:
                for r in resources[:max_tables]:
                    try:
                        if not r.get("supports_list"):
                            continue
                        endpoint = r.get("endpoint") or ""
                        if not endpoint:
                            continue

                        # Finding C: only probe with a limit param when the
                        # resource actually declares one. An empty limit_param
                        # means the API rejects unknown query fields (NASA APOD
                        # → 400), which would leave the resource with no columns
                        # and row_count=-1. Skip the limit entirely when blank.
                        limit_param = r.get("limit_param")
                        req_params: Dict[str, Any] = {}
                        if limit_param:
                            req_params[limit_param] = 1

                        pag_type = (r.get("pagination_type") or "").lower()
                        pag_param = r.get("pagination_param") or None
                        if pag_param:
                            if pag_type == "offset":
                                req_params[pag_param] = 0
                            elif pag_type == "page":
                                req_params[pag_param] = 1

                        resp = self._make_request("GET", endpoint, config, params=req_params)
                        if not resp.get("success"):
                            continue

                        body = resp.get("data")
                        headers = resp.get("headers")

                        # Row count: keep existing best-effort behaviour
                        # but emit the canonical "-1" sentinel when the
                        # API doesn't expose a total, so the UI knows
                        # the value is unknown rather than zero.
                        total = self._extract_total_count(body, headers)
                        if total is not None:
                            r["row_count"] = total
                            r["is_exact_count"] = False

                        # Columns: derived from the first record of the
                        # probe response. Honours the vendor spec's
                        # response_data_key when present (so we look at
                        # `data[0]` for Stripe-style responses,
                        # `results[0]` for HubSpot, etc.).
                        first_row = self._extract_first_row(body, r.get("response_data_key") or "")
                        cols = self._infer_columns_from_row(first_row)
                        if cols:
                            r["columns"] = cols
                            # PK confirmation: if the id_field from the
                            # vendor spec exists in the probe response,
                            # declare it as the primary key. Sinks will
                            # use this for idempotent upserts; sources
                            # without an id field fall through to the
                            # sink's synthetic-hash PK.
                            id_field = r.get("id_field") or "id"
                            col_names = {c["name"] for c in cols}
                            if id_field and id_field in col_names:
                                r["primary_keys"] = [id_field]
                                r["primary_key_source"] = "inferred"
                    except Exception:
                        continue

            return {
                "success": True,
                "tables": resources,  # Using 'tables' for compatibility
                "total_tables": len(resources)
            }
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    # =========================================================================
    # SOURCE OPERATIONS (REQUIRED)
    # =========================================================================
    
    def export(self, params: Dict) -> Dict[str, Any]:
        """
        Export data from the source.
        REQUIRED by BaseMCPConnector abstract class.
        """
        # Delegate to ApiHandler (contract-driven)
        prepared = self.prepare_export_data(params)
        if not prepared.get('success'):
            return prepared
        
        config = prepared['config']
        
        resource_endpoints = {
            "licenses": "/licenses",
        }

        # Determine which resource/object to export.
        # If not provided, default to the first known resource so the connector is usable
        # out-of-the-box (and offline QA can run without guessing an object name).
        # NOTE: The orchestrator/executor and BaseMCPConnector may normalize generic terms like
        # 'table' into API-ish terms like 'endpoint'. Treat these as aliases so pipelines work
        # without per-connector manual fixes.
        resource = (
            params.get('object')
            or params.get('resource')
            or params.get('endpoint')  # common normalization target for api_saas
            or params.get('table')
        )
        if not resource:
            if resource_endpoints:
                resource = next(iter(resource_endpoints.keys()))
            else:
                return {"success": False, "error": "Missing 'object' parameter"}

        # Strip schema prefix if the orchestrator passed a qualified name like
        # "stripe.charges" — endpoint map keys are bare resource names. Parallels
        # the GraphQL template's rsplit dispatch fix (F-13, PR #61).
        if isinstance(resource, str) and "." in resource:
            resource = resource.rsplit(".", 1)[-1]

        endpoint = resource_endpoints.get(resource)
        if not endpoint:
            return {"success": False, "error": f"Unknown resource: {resource}"}
        
        # Extract pagination parameters
        max_pages = int(params.get("max_pages") or DEFAULT_MAX_PAGES)
        max_records = int(params.get("max_records") or DEFAULT_MAX_RECORDS)
        
        # Extract incremental sync parameters
        since = params.get('since') or params.get('updated_since') or params.get('modified_after')
        cursor = params.get('cursor') or params.get('next_cursor')
        incremental_field = params.get('incremental_field', 'updated_at')
        
        # Only pass *query params* to the API (exclude config/object/max_pages, etc.)
        query_params = {}
        if isinstance(params, dict):
            qp = params.get("params")
            if isinstance(qp, dict):
                query_params = qp
        
        # Build resource config with incremental metadata
        resource_config = self._get_resource_config(resource)
        
        # Always forward 'since' to the API when provided — even if the resource
        # doesn't advertise supports_incremental, sending the param is harmless
        # (the API will ignore it), and NOT sending it silently drops the caller's
        # watermark filter, causing a full re-sync every time.
        if since:
            incremental_param = resource_config.get('incremental_param', 'updated_since')
            query_params[incremental_param] = since
        
        # Apply cursor for pagination resumption
        if cursor:
            pagination_param = resource_config.get('pagination_param', 'cursor')
            query_params[pagination_param] = cursor

        # On an incremental re-run the caller passes its last checkpoint as
        # `since`. Forward it as prior_watermark so a 0-row result echoes the
        # checkpoint back instead of resetting it (and re-scanning from zero).
        prior_watermark = None
        if since and resource_config.get('supports_incremental'):
            prior_watermark = {"field": incremental_field, "value": since}

        try:
            # Use ApiHandler for export, passing per-resource pagination/shape config
            # so PaginationHandler uses the correct settings for this resource instead
            # of the connector-wide defaults (critical for multi-resource connectors).
            result = self._api_handler.export_resource(
                connector=self,
                config=config,
                resource=resource,
                endpoint=endpoint,
                params=query_params,
                max_pages=max_pages,
                max_records=max_records,
                incremental_field=incremental_field if resource_config.get('supports_incremental') else None,
                resource_config=resource_config,
                prior_watermark=prior_watermark,
            )

            # Convert ExportResult to dict (carries records, next_cursor,
            # has_more, and stats.watermark/max_watermark).
            return result.to_dict()

        except Exception as e:
            logger.error(f"Export failed: {e}", exc_info=True)
            return {"success": False, "error": str(e)}
    
    # Additional source operations (custom methods beyond export)
    
    def licenses(self, params: Dict = None) -> Dict[str, Any]:
        """Export records from licenses (/licenses)"""
        prepared = self.prepare_export_data(params)
        config = prepared['config']
        
        # Determine which resource/object to export
        obj_name = params.get('object') or params.get('table') or params.get('resource')
        if not obj_name:
            return {"success": False, "error": "Missing 'object' parameter"}
        # Strip schema prefix (e.g. "stripe.charges" → "charges") — parallels F-13.
        if isinstance(obj_name, str) and "." in obj_name:
            obj_name = obj_name.rsplit(".", 1)[-1]
        
        limit = prepared.get('limit', 100)
        offset = prepared.get('offset', 0)
        
        # Find resource endpoint
        resource_endpoints = {
            "licenses": "/licenses",
        }
        
        endpoint = resource_endpoints.get(obj_name)
        if not endpoint:
            return {"success": False, "error": f"Unknown resource: {obj_name}"}
        
        try:
            result = self._make_request(
                'GET', 
                endpoint, 
                config,
                params={'limit': limit, 'offset': offset}
            )
            
            if not result['success']:
                return result
            
            data = result.get('data', {})
            records = data.get('results') or data.get('data') or data.get('items') or []
            if isinstance(data, list):
                records = data
            
            return self.finalize_export_result(
                records, 
                prepared, 
                columns=list(records[0].keys()) if records else []
            )
            
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    # =========================================================================
    # DESTINATION OPERATIONS (REQUIRED)
    # =========================================================================
    
    def import_data(self, params: Dict) -> Dict[str, Any]:
        """
        Import data to the destination.
        REQUIRED by BaseMCPConnector abstract class.
        """
        # Not a destination connector or not implemented
        return {
            "success": False,
            "error": "Import operation not supported by this connector"
        }
    

    # =========================================================================
    # RESOURCE-SPECIFIC OPERATIONS
    # =========================================================================
    
    def list_licenses(self, params: Dict = None) -> Dict[str, Any]:
        """List all licenses"""
        params = params or {}
        params['object'] = 'licenses'
        return self.export(params)
    
    def get_license(self, params: Dict = None) -> Dict[str, Any]:
        """Get single licene by ID"""
        config = self._get_config(params)
        record_id = params.get('id')
        
        if not record_id:
            return {"success": False, "error": "Missing 'id' parameter"}
        
        endpoint = f"/licenses/{record_id}"
        return self._make_request('GET', endpoint, config)

    # DO NOT implement handle_request, _handle_tool_call, run, or list_tools
    # The base class handles these automatically!


# =============================================================================
# HTTP SERVER MODE (for Docker deployment)
# =============================================================================

def create_http_app():
    """Create FastAPI app for HTTP-based MCP server"""
    from fastapi import FastAPI, HTTPException
    # Decimal crosses this boundary as a STRING, never a float. FastAPI's
    # jsonable_encoder maps Decimal -> float (ENCODERS_BY_TYPE), which silently
    # destroys precision on the way to the sink: a numeric 123456789012345678.5
    # arrives as 1.2345678901234568e+17, and the orchestrator writes that back
    # out as 123456789012345680 -- a changed value, with no error raised anywhere.
    # The stdio path already serialises with json.dumps(..., default=str), so
    # HTTP mode was the only lossy leg -- and it is the leg every containerised
    # deployment uses, which is why no stdio-based test could ever see it.
    from decimal import Decimal as _Decimal
    from fastapi.encoders import ENCODERS_BY_TYPE as _ENCODERS_BY_TYPE
    _ENCODERS_BY_TYPE[_Decimal] = str
    from pydantic import BaseModel
    from typing import Optional, Any
    
    runtime_version = os.getenv("MCP_CONNECTOR_VERSION") or os.getenv("CONNECTOR_VERSION") or "1.0.0"
    runtime_version = str(runtime_version).strip()
    if runtime_version and not runtime_version.startswith("v"):
        runtime_version = f"v{runtime_version}"

    app = FastAPI(
        title="Github-Rest MCP Connector",
        description="github-rest connector",
        version=runtime_version or "1.0.0"
    )
    
    server = GithubRestConnector()
    
    class MCPRequest(BaseModel):
        """MCP JSON-RPC request (full envelope)"""
        jsonrpc: str = "2.0"
        id: Optional[int] = None
        method: str
        params: Optional[dict] = None
    
    class LegacyMCPRequest(BaseModel):
        """Legacy MCP request format (backward compatibility)"""
        method: str
        params: Optional[dict] = None
    
    @app.get("/health")
    async def health():
        return {
            "status": "healthy",
            "connector": server.connector_type,
            "version": runtime_version or "1.0.0",
        }
    
    @app.post("/mcp")
    async def mcp_handler(request: Union[MCPRequest, LegacyMCPRequest, Dict]):
        """Handle MCP JSON-RPC requests over HTTP (supports full envelope or legacy format)"""
        try:
            # Normalize to full JSON-RPC envelope
            if isinstance(request, dict):
                request_dict = request
            else:
                request_dict = request.dict() if hasattr(request, 'dict') else request.model_dump()
            
            # If legacy format (no jsonrpc field), wrap it
            if "jsonrpc" not in request_dict:
                request_dict = {
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": request_dict.get("method"),
                    "params": request_dict.get("params") or {}
                }
            
            result = server.handle_request(request_dict)
            return result
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
    @app.post("/invoke/{tool_name}")
    async def invoke_tool(tool_name: str, params: dict = {}):
        """Direct tool invocation endpoint"""
        try:
            # Map tool names to methods
            method_name = tool_name.replace("-", "_")
            # Security: this route bypasses _handle_tool_call, so it needs its own
            # copy of that dispatcher's guard. Without it a crafted name like
            # "_cleanup_worker" resolves via getattr and exposes internals to any
            # caller that can reach the container. Tool handlers are always public.
            if method_name.startswith("_"):
                raise HTTPException(status_code=404, detail=f"Tool not found: {tool_name}")
            if hasattr(server, method_name):
                method = getattr(server, method_name)
                return method(params)
            
            # Try with connector prefix
            prefixed = f"github-rest_{method_name}"
            if hasattr(server, prefixed):
                method = getattr(server, prefixed)
                return method(params)
            
            raise HTTPException(status_code=404, detail=f"Tool not found: {tool_name}")
        except HTTPException:
            raise
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
    @app.get("/capabilities")
    async def get_capabilities():
        return server.get_capabilities()
    
    @app.post("/test_connection")
    async def test_connection(params: dict = {}):
        return server.test_connection(params)
    
    @app.post("/validate_config")
    async def validate_config(params: dict = {}):
        return server.validate_config(params)
    
    @app.post("/discover_schema")
    async def discover_schema(params: dict = {}):
        return server.discover_schema(params)
    
    return app


if __name__ == "__main__":
    import os
    
    # Check if running in HTTP mode (Docker)
    http_mode = os.getenv("MCP_HTTP_MODE", "false").lower() == "true"
    port = int(os.getenv("MCP_PORT", os.getenv("PORT", "8000")))
    
    if http_mode or os.getenv("DOCKER_CONTAINER"):
        # HTTP mode for Docker
        import uvicorn
        app = create_http_app()
        logger.info(f"🚀 Starting Github-Rest MCP Server in HTTP mode on port {port}")
        uvicorn.run(app, host="0.0.0.0", port=port)
    else:
        # Stdio mode for local/CLI usage
        server = GithubRestConnector()
        server.run()

