-- Migration: Fix seeded dev users to have a real bcrypt password hash
-- Background:
--  - Older migrations inserted a placeholder '$2a$10$dummyhashfordevelopment' which can never pass bcrypt.
--  - This migration updates seeded users so login works in dev environments.
--
-- Dev password: password123
-- bcrypt hash (generated by api-gateway register endpoint): $2a$10$wEAsBOF81BxdOovfGBoWqOJz4TlpnEQonn3TLVUbOLr3uozAEMROq

UPDATE users
SET password_hash = '$2a$10$wEAsBOF81BxdOovfGBoWqOJz4TlpnEQonn3TLVUbOLr3uozAEMROq',
    updated_at = NOW()
WHERE password_hash = '$2a$10$dummyhashfordevelopment'
  AND (
    id IN (
      '00000000-0000-0000-0000-000000000000'::uuid,
      '00000000-0000-0000-0000-000000000001'::uuid
    )
    OR email IN ('default@rsync-ai.local', 'test@rsync-ai.local')
  );

