#!/usr/bin/env python3
"""
Shopify MCP Connector (GraphQL)
Auto-generated by Pure Agentic Pipeline v1.1

JSON-RPC server for Shopify GraphQL operations.
Category:   api_saas
Protocol:   graphql
Endpoint:   https://{shop}.myshopify.com/admin/api/2024-10/graphql.json

DO NOT EDIT - This file is auto-generated. Make changes to the spec instead.
Generated: 2026-05-12T13:39:04.694079

Incremental sync contract
-------------------------
This connector is the reference implementation of the cross-connector
incremental sync contract documented in
``shared/mcp-connectors/INCREMENTAL.md``. The export() method accepts
an optional ``since`` ISO-8601 timestamp in params, filters Shopify
resources to rows updated AFTER that timestamp using Shopify's search
syntax (``updated_at:>2024-05-22T16:54:36Z``), and returns
``stats.watermark = {"field": "last_modified", "value": <max updatedAt>}``
in the export response. The executor persists that watermark into
``pipeline_checkpoints.position`` and replays it as ``since`` on the
next scheduled run. When ``since`` is absent the behavior is byte-
identical to a full fetch — this is the first-run / backfill path.

Per-resource adoption (Shopify v1.0.1):
  - products, orders, customers      → incremental (query filter)
  - inventory_items                  → full refetch (Shopify Admin
    2024-10 ``inventoryItems`` has no ``query`` arg)
  - collections                      → full refetch (``collections``
    has no ``query`` arg in 2024-10)
  - shop                             → singleton, no watermark
"""

import json
import logging
import os
import re
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlsplit

import requests

# Parent dir for base_connector
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from base_connector import (
    BaseMCPConnector,
    ExportResult,
    ImportResult,
    ErrorItem,
    GraphQLPaginationHandler,
)

# Bulk Operations helper (SHOPIFY-BulkOps). Co-located in this directory.
# Import is best-effort — if missing/broken, bulk path is silently
# disabled and export() always uses the regular paginated path.
try:
    sys.path.insert(0, os.path.dirname(__file__))
    import bulk_operations as _bulk_ops  # type: ignore
except Exception as _bulk_import_err:  # pragma: no cover - defensive
    _bulk_ops = None  # type: ignore
    logging.getLogger(__name__).warning(
        "[BulkOps] helper module unavailable, bulk path disabled: %s",
        _bulk_import_err,
    )

# Canonical type vocabulary for the generic discovery contract. Source
# connectors emit one of these strings in `discover_schema` so the
# orchestrator can route to any sink without per-connector type code.
# Single source of truth lives in
# shared/mcp-connectors/schemas/response_schemas.py; the same mapping
# is inlined here because that module is not bundled into the connector
# container image. Keep both copies in sync if you extend the vocabulary.
_CANONICAL_TYPES = {
    "string", "integer", "number", "boolean",
    "timestamp", "date", "time", "json", "binary",
}
_GRAPHQL_TO_CANONICAL = {
    "String": "string", "ID": "string",
    "Int": "integer",
    "Float": "number",
    "Boolean": "boolean",
    "DateTime": "timestamp", "Datetime": "timestamp",
    "Date": "date",
    "Time": "time",
    "JSON": "json",
}


def canonicalize_type(t):
    """Coerce any GraphQL scalar / type name to a canonical type.

    Anything not in the scalar map (custom scalars like ``Money``,
    object types, Connection types) lands as ``json`` — generic SQL JSON
    columns are queryable in both Postgres and MySQL and preserve the
    full payload losslessly. None / unknown → ``string`` so a typo
    or new scalar never blocks a pipeline.
    """
    if not isinstance(t, str):
        return "string"
    raw = t.strip()
    if not raw:
        return "string"
    if raw in _CANONICAL_TYPES:
        return raw
    mapped = _GRAPHQL_TO_CANONICAL.get(raw)
    if mapped:
        return mapped
    # Any other GraphQL type (Money, MoneyBag, Metafield, *Connection,
    # custom enum, ...) is non-scalar from the sink's perspective. JSON
    # is the safest landing zone — preserves the nested structure.
    return "json"

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# GraphQL helpers
# ---------------------------------------------------------------------------


class GraphQLError(Exception):
    """Raised when a GraphQL response carries `errors[]` or transport fails."""

    def __init__(self, message: str, errors: Optional[List[Dict[str, Any]]] = None,
                 status_code: Optional[int] = None):
        super().__init__(message)
        self.errors = errors or []
        self.status_code = status_code


# ---------------------------------------------------------------------------
# Host-injection guard (data-plane token-exfil follow-up to #625)
# ---------------------------------------------------------------------------
# The user-supplied `shop` is spliced into the data-plane endpoint
# https://{shop}.myshopify.com/admin/... while the tenant's Shopify Admin
# access token rides in the X-Shopify-Access-Token request header. If `shop`
# (or an `endpoint` override) is not validated to be a real *.myshopify.com
# host, a value like "attacker.com#", "attacker.com/" or a raw foreign endpoint
# would POST that access token to an attacker-controlled server (credential
# exfil). The SSRF guard only blocks *internal* targets (loopback / private /
# link-local IMDS), NOT public attacker hosts, so it does not cover this class.
# Restrict `shop` to a single DNS label and pin the resolved host to
# <label>.myshopify.com. Mirrors sanitize_subdomain in
# shared/mcp-connectors/oauth/oauth_registry.py (which fixed the OAuth
# control-plane path in #625) — keep the two in lockstep.
_SHOP_LABEL_RE = re.compile(r"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$")
_SHOPIFY_HOST_SUFFIX = ".myshopify.com"


def _sanitize_shop(raw: Optional[str]) -> str:
    """Validate a user-supplied Shopify ``shop`` and return its bare store
    subdomain (a single DNS label).

    Accepts either a bare label ("acme") or the full domain
    ("acme.myshopify.com"). Rejects anything else — an embedded
    scheme/path/'@'/'#'/'/', a foreign host, an IP literal, or an empty value —
    by raising ValueError, so the access token can never be routed to an
    attacker host.
    """
    s = (raw or "").strip()
    if s.lower().endswith(_SHOPIFY_HOST_SUFFIX):
        s = s[: -len(_SHOPIFY_HOST_SUFFIX)]
    s = s.strip().strip(".")
    if not s:
        raise ValueError("shop is required (e.g. 'acme' for acme.myshopify.com)")
    if not _SHOP_LABEL_RE.match(s):
        raise ValueError(
            f"invalid Shopify shop {raw!r}: expected a store subdomain such as "
            f"'acme' or 'acme.myshopify.com' (a single DNS label)"
        )
    return s


# ---------------------------------------------------------------------------
# Operation registry — generated from spec.operations
# ---------------------------------------------------------------------------

# Each entry: operation_name (snake_case) → {
#   "graphql_name":    str (original camelCase),
#   "operation_type":  "query"|"mutation"|"subscription",
#   "query":           str (full GraphQL document),
#   "return_type":     str | None,
# }
GRAPHQL_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "shop": {
        "graphql_name": "shop",
        "operation_type": "query",
        "query": "query ShopInfo {\n  shop {\n    id\n    name\n    email\n    myshopifyDomain\n    primaryDomain { url host }\n    plan { displayName partnerDevelopment shopifyPlus }\n    currencyCode\n    timezoneAbbreviation\n    ianaTimezone\n    contactEmail\n    createdAt\n    updatedAt\n  }\n}",
        "return_type": "Shop",
        "description": "Retrieve shop information and settings",
    },
    "products": {
        "graphql_name": "products",
        "operation_type": "query",
        "query": "query GetProducts($first: Int, $after: String, $query: String) {\n  products(first: $first, after: $after, query: $query, sortKey: UPDATED_AT, reverse: false) {\n    edges {\n      node {\n        id\n        title\n        handle\n        vendor\n        productType\n        status\n        descriptionHtml\n        createdAt\n        updatedAt\n        publishedAt\n        tags\n        totalInventory\n        variants(first: 5) {\n          edges {\n            node {\n              id\n              title\n              sku\n              price\n              inventoryQuantity\n            }\n          }\n        }\n      }\n      cursor\n    }\n    pageInfo { hasNextPage hasPreviousPage startCursor endCursor }\n  }\n}",
        "return_type": "ProductConnection",
        "description": "List products with Relay connection pagination",
    },
    "orders": {
        "graphql_name": "orders",
        "operation_type": "query",
        # PII fields (Order.email, Order.phone, Order.customer.*,
        # Order.shippingAddress.*) require a protected-customer-data approval
        # that dev/Basic stores don't have, returning
        # "This app is not approved to access the Customer object". Keep the
        # default query PII-free so previews and bulk exports succeed on every
        # plan; downstream pipelines can still join Customer data via a
        # separately-approved app.
        "query": "query GetOrders($first: Int, $after: String, $query: String) {\n  orders(first: $first, after: $after, query: $query, sortKey: UPDATED_AT, reverse: false) {\n    edges {\n      node {\n        id\n        name\n        createdAt\n        updatedAt\n        processedAt\n        cancelledAt\n        displayFinancialStatus\n        displayFulfillmentStatus\n        totalPriceSet { shopMoney { amount currencyCode } }\n        subtotalPriceSet { shopMoney { amount currencyCode } }\n        totalTaxSet { shopMoney { amount currencyCode } }\n        lineItems(first: 10) {\n          edges {\n            node {\n              id\n              title\n              quantity\n              originalUnitPriceSet { shopMoney { amount currencyCode } }\n            }\n          }\n        }\n      }\n      cursor\n    }\n    pageInfo { hasNextPage hasPreviousPage startCursor endCursor }\n  }\n}",
        "return_type": "OrderConnection",
        "description": "List orders with Relay connection pagination",
    },
    "customers": {
        "graphql_name": "customers",
        "operation_type": "query",
        # Customer name/email/phone/address fields are protected customer data
        # and unavailable on Basic plans without app approval. Keep only
        # non-PII signals (id, timestamps, lifetime metrics, tags) so previews
        # work everywhere; apps with approval can extend the field set.
        "query": "query GetCustomers($first: Int, $after: String, $query: String) {\n  customers(first: $first, after: $after, query: $query, sortKey: UPDATED_AT, reverse: false) {\n    edges {\n      node {\n        id\n        createdAt\n        updatedAt\n        verifiedEmail\n        numberOfOrders\n        amountSpent { amount currencyCode }\n        tags\n      }\n      cursor\n    }\n    pageInfo { hasNextPage hasPreviousPage startCursor endCursor }\n  }\n}",
        "return_type": "CustomerConnection",
        "description": "List customers with Relay connection pagination",
    },
    "collections": {
        "graphql_name": "collections",
        "operation_type": "query",
        # Shopify Admin 2024-10 changed `productsCount` from a scalar Int to a
        # `Count` object, so it now requires `{ count }` sub-selections.
        # Without this, every collections query fails with
        # "Field must have selections (field 'productsCount' returns Count
        # but has no selections)".
        "query": "query GetCollections($first: Int, $after: String) {\n  collections(first: $first, after: $after) {\n    edges {\n      node {\n        id\n        title\n        handle\n        description\n        updatedAt\n        productsCount { count }\n        ruleSet { appliedDisjunctively }\n      }\n      cursor\n    }\n    pageInfo { hasNextPage hasPreviousPage startCursor endCursor }\n  }\n}",
        "return_type": "CollectionConnection",
        "description": "List collections with Relay connection pagination",
    },
    "inventory_items": {
        "graphql_name": "inventoryItems",
        "operation_type": "query",
        # Shopify Admin 2024-10 removed the scalar `available` field from
        # `InventoryLevel`. The replacement is the parametric
        # `quantities(names: [...])` returning {name, quantity} per
        # requested type. Without this update, every inventory_items
        # preview/export fails with `graphql errors: Field 'available'
        # doesn't exist on type 'InventoryLevel'`.
        "query": "query GetInventoryItems($first: Int, $after: String) {\n  inventoryItems(first: $first, after: $after) {\n    edges {\n      node {\n        id\n        sku\n        tracked\n        createdAt\n        updatedAt\n        inventoryLevels(first: 5) {\n          edges {\n            node {\n              id\n              quantities(names: [\"available\"]) { name quantity }\n              location { id name }\n            }\n          }\n        }\n      }\n      cursor\n    }\n    pageInfo { hasNextPage endCursor }\n  }\n}",
        "return_type": "InventoryItemConnection",
        "description": "List inventory items with Relay connection pagination",
    },
}


# ---------------------------------------------------------------------------
# Incremental sync support (cross-connector contract — see INCREMENTAL.md)
# ---------------------------------------------------------------------------
#
# Mapping resource -> whether the Shopify GraphQL `<resource>` field accepts
# a `query` filter argument we can use to narrow to rows updated AFTER a
# watermark. Resources marked False fall through to full-refetch on every
# call (still safe; just no API-call savings until Shopify exposes a filter).
#
# Verified against Shopify Admin API 2024-10:
#   - products       : `products(query: ...)` supports `updated_at:>` predicate
#   - orders         : `orders(query: ...)` supports `updated_at:>`
#   - customers      : `customers(query: ...)` supports `updated_at:>`
#   - inventory_items: `inventoryItems` has NO `query` arg in 2024-10 schema
#   - collections    : `collections` has NO `query` arg in 2024-10 schema
#   - shop           : singleton, no watermark concept
_INCREMENTAL_CAPABLE: Dict[str, bool] = {
    "products": True,
    "orders": True,
    "customers": True,
    "inventory_items": False,
    "collections": False,
    "shop": False,
}

# Shopify's search-string predicate field used to filter on the row's
# server-side updated timestamp. The same field name is canonical across
# products, orders, customers per Shopify's search-syntax docs.
_SHOPIFY_UPDATED_AT_FIELD = "updated_at"


def _normalize_iso_timestamp(raw: Any) -> Optional[str]:
    """Best-effort parse of an arbitrary ISO-8601 string into a Shopify-safe form.

    The executor sends ``since`` as whatever value the prior run wrote into
    ``pipeline_checkpoints.position.watermark.value``. We accept any
    standard ISO-8601 shape and re-emit ``YYYY-MM-DDTHH:MM:SSZ`` which
    Shopify's search parser handles unambiguously.

    Returns ``None`` for empty / non-string / unparseable input, so callers
    can fall back to a full fetch instead of crashing.
    """
    if raw is None:
        return None
    if not isinstance(raw, str):
        return None
    s = raw.strip()
    if not s:
        return None
    # Accept trailing Z by mapping to +00:00 for fromisoformat (Python 3.10).
    candidate = s.replace("Z", "+00:00") if s.endswith("Z") else s
    try:
        dt = datetime.fromisoformat(candidate)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    # Shopify's search-string parser is fine with `YYYY-MM-DDTHH:MM:SSZ`
    # and dislikes microseconds in some date fields. Drop them.
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _compose_query_filter(existing: Optional[str], since_iso: Optional[str]) -> Optional[str]:
    """Combine an existing user `query` variable with an updated_at predicate.

    Per the incremental contract: if the caller already supplied a custom
    Shopify search string in ``variables.query`` we AND-combine. Otherwise
    we emit a bare predicate. Returns ``None`` (== don't pass `query`)
    when both inputs are empty.
    """
    predicate = f"{_SHOPIFY_UPDATED_AT_FIELD}:>{since_iso}" if since_iso else None
    existing = (existing or "").strip()
    if existing and predicate:
        # Wrap each side in parens to keep predicate boundaries explicit;
        # Shopify's search parser supports AND as a keyword between groups.
        return f"({existing}) AND {predicate}"
    return existing or predicate


# ISO-8601 of the maximum `updatedAt` seen so far across a multi-page export.
# Stored as a tuple (max_string, max_datetime) so comparisons stay correct
# even when strings carry different tz offsets. None == no rows seen.
def _max_updated_at(
    rows: List[Dict[str, Any]],
    current: Optional[Tuple[str, datetime]],
) -> Optional[Tuple[str, datetime]]:
    """Scan ``rows`` for ``updatedAt`` and return the new running max.

    Shopify products / orders / customers / inventory_items each carry an
    ``updatedAt`` field with an ISO-8601 string. We track the textual
    representation we'll persist AND the parsed datetime we use to compare,
    so the comparison is timezone-correct even if Shopify's offset format
    varies between resources.
    """
    best = current
    for row in rows or []:
        if not isinstance(row, dict):
            continue
        raw = row.get("updatedAt")
        if not isinstance(raw, str) or not raw:
            continue
        try:
            dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        if best is None or dt > best[1]:
            best = (raw, dt)
    return best


# ---------------------------------------------------------------------------
# Connector
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Destination (write) support — products via productCreate / productUpdate
# ---------------------------------------------------------------------------
#
# v1.0.0 was source-only. v1.1.0 adds a products write path. Shopify mutations
# return HTTP 200 with a `userErrors[]` array INSIDE the mutation payload — NOT
# the top-level GraphQL `errors[]` that _execute_graphql raises on — so a write
# that "succeeds" at the transport layer can still have failed. _write_records
# parses userErrors and only counts a row written when userErrors is empty;
# otherwise the sink would record a silent false success.

_PRODUCT_CREATE_MUTATION = (
    "mutation ProductCreate($input: ProductInput!) {\n"
    "  productCreate(input: $input) {\n"
    "    product { id handle title status }\n"
    "    userErrors { field message }\n"
    "  }\n"
    "}"
)
_PRODUCT_UPDATE_MUTATION = (
    "mutation ProductUpdate($input: ProductInput!) {\n"
    "  productUpdate(input: $input) {\n"
    "    product { id handle title status }\n"
    "    userErrors { field message }\n"
    "  }\n"
    "}"
)

# ProductInput fields passed through from an incoming record. Anything else is
# ignored (Shopify rejects unknown input fields). Kept to stable scalar fields
# so a Shopify→Shopify products copy round-trips and a DB/CSV→Shopify load maps
# cleanly. The source `products` query (above) emits id/title/handle/vendor/
# productType/status/descriptionHtml/tags — all map straight back here.
_PRODUCT_INPUT_FIELDS = (
    "title", "handle", "descriptionHtml", "vendor", "productType",
    "status", "tags", "templateSuffix", "giftCard", "requiresSellingPlan",
)
# Common source column names → ProductInput field.
_PRODUCT_FIELD_ALIASES = {
    "description": "descriptionHtml",
    "body_html": "descriptionHtml",
    "product_type": "productType",
    "template_suffix": "templateSuffix",
}
_PRODUCT_GID_PREFIX = "gid://shopify/Product/"


def _build_product_input(record: Dict[str, Any]) -> Tuple[Dict[str, Any], bool]:
    """Map an incoming record onto a Shopify ``ProductInput``.

    Returns ``(input_dict, is_update)``. ``is_update`` is True when the record
    carries a Shopify product GID (``gid://shopify/Product/...``) — those route
    to productUpdate; everything else is a productCreate. Applies field-name
    aliases (description→descriptionHtml, product_type→productType, …) and
    coerces ``tags`` (CSV string → list) and ``status`` (→ upper-case enum).
    """
    rec = dict(record or {})
    for src, dst in _PRODUCT_FIELD_ALIASES.items():
        if src in rec and dst not in rec and rec.get(src) is not None:
            rec[dst] = rec[src]

    pid = rec.get("id") or rec.get("admin_graphql_api_id")
    is_update = isinstance(pid, str) and pid.startswith(_PRODUCT_GID_PREFIX)

    out: Dict[str, Any] = {}
    if is_update:
        out["id"] = pid
    for k in _PRODUCT_INPUT_FIELDS:
        if k in rec and rec[k] is not None:
            out[k] = rec[k]

    tags = out.get("tags")
    if isinstance(tags, str):
        out["tags"] = [t.strip() for t in tags.split(",") if t.strip()]
    status = out.get("status")
    if isinstance(status, str):
        out["status"] = status.upper()
    return out, is_update


# Writable resources → mutation wiring. Register a new resource by adding its
# create/update mutations + result keys + input builder here.
_WRITABLE_RESOURCES: Dict[str, Dict[str, Any]] = {
    "products": {
        "create_mutation": _PRODUCT_CREATE_MUTATION,
        "create_result_key": "productCreate",
        "update_mutation": _PRODUCT_UPDATE_MUTATION,
        "update_result_key": "productUpdate",
        "build_input": _build_product_input,
    },
}


class ShopifyConnector(BaseMCPConnector):
    """Shopify GraphQL connector."""

    DEFAULT_ENDPOINT = "https://{shop}.myshopify.com/admin/api/2024-10/graphql.json"

    def __init__(self) -> None:
        super().__init__()
        self.connector_type = "shopify-admin-graphql"
        self.display_name = "Shopify"
        # Must match metadata.json "category". Left undeclared, BaseMCPConnector
        # defaults to "relational_db" (base_connector.py:1000), so Go read api_saas
        # from metadata.json while Python normalised params as a relational DB.
        self.connector_category = "api_saas"

    @staticmethod
    def _get_config(params: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Unwrap config from MCP tool-call wrapper.

        _handle_tool_call passes the full arguments dict, which wraps the
        actual connection config under a ``"config"`` key. Accept both shapes:
          - {"config": {"shop": ..., "access_token": ...}}  ← tools/call path
          - {"shop": ..., "access_token": ...}              ← direct stdio path
        """
        if not params:
            return {}
        if "config" in params and isinstance(params["config"], dict):
            return dict(params["config"])
        return dict(params)

    # ----- HTTP transport ---------------------------------------------------

    def _resolve_endpoint(self, config: Dict[str, Any]) -> str:
        """Resolve the GraphQL endpoint URL.

        The spec's base_url carries a runtime `{shop}` placeholder that is
        substituted from `config` at call time. The shop is STRICTLY validated
        (single DNS label) and the resolved host is pinned to
        ``<label>.myshopify.com`` so the tenant's X-Shopify-Access-Token can
        never be POSTed to an attacker host — even via a raw `endpoint`
        override. See ``_sanitize_shop`` above.
        """
        try:
            shop = _sanitize_shop(config.get("shop"))
        except ValueError as e:
            # Fail closed using the connector's transport error type so callers
            # (test_connection / export) surface it cleanly instead of raising
            # an uncaught ValueError.
            raise GraphQLError(f"invalid shop: {e}") from e

        endpoint = config.get("endpoint") or self.DEFAULT_ENDPOINT
        # Merge optional-placeholder defaults so a single missing key doesn't
        # suppress all substitutions (e.g. {version} defaults to 2024-10).
        # Force the validated shop label into the substitution set so a caller
        # cannot smuggle a host-escaping value through config["shop"].
        defaults = {
            "version": "2024-10",
        }
        sub = {**defaults, **config, "shop": shop}
        try:
            resolved = endpoint.format(**sub)
        except (KeyError, IndexError):
            resolved = endpoint

        # Defense in depth: whatever the template or `endpoint` override
        # produced, the host MUST be <shop>.myshopify.com. Blocks an override
        # that points the access-token POST at a foreign host.
        parts = urlsplit(resolved)
        expected_host = f"{shop}{_SHOPIFY_HOST_SUFFIX}".lower()
        if parts.scheme not in ("http", "https") or (parts.hostname or "").lower() != expected_host:
            raise GraphQLError(
                f"refusing to send Shopify credentials to non-myshopify host "
                f"{parts.hostname!r} (resolved endpoint {resolved!r})"
            )
        return resolved

    # ----- Auth dispatcher (Phase 12: multi-auth) ---------------------------
    # Each supported method's wire config is baked in at generation time.
    # The user picks `config["auth_method"]` at connection time and the
    # dispatcher formats the request accordingly. Falls back to the spec's
    # default `auth.type` when the user doesn't specify.

    SUPPORTED_AUTH_METHODS: List[Dict[str, Any]] = [
        {
            "method": "custom_header",
            "header_name": "X-Shopify-Access-Token",
            "header_prefix": "",
            "config_keys": ["access_token", "token"],
            "description": "Shopify Admin API access token (private app or custom app token)",
        },
        {
            "method": "oauth2",
            "header_name": "X-Shopify-Access-Token",
            "header_prefix": "",
            "config_keys": ["access_token"],
            "description": "OAuth 2.0 \u2014 for public/custom Shopify Apps installed on a shop",
        },
    ]

    DEFAULT_AUTH_METHOD = "custom_header"

    def _resolve_auth_method(self, config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Pick the auth method to use for a request.

        Priority:
          1. `config['auth_method']` if it matches a supported method
          2. The connector's DEFAULT_AUTH_METHOD
          3. The first supported method declared
        """
        requested = (config.get("auth_method") or "").strip().lower()
        for m in self.SUPPORTED_AUTH_METHODS:
            if m["method"] == requested:
                return m
        for m in self.SUPPORTED_AUTH_METHODS:
            if m["method"] == self.DEFAULT_AUTH_METHOD:
                return m
        return self.SUPPORTED_AUTH_METHODS[0] if self.SUPPORTED_AUTH_METHODS else None

    def _build_auth_headers(self, config: Dict[str, Any]) -> Dict[str, str]:
        """Format auth headers based on the user's chosen method.

        For basic auth, returns empty headers (the connector uses
        `requests.auth=(user, pass)` instead).
        """
        method = self._resolve_auth_method(config)
        if method is None:
            return {}

        wire = method["method"]
        if wire == "none":
            return {}
        if wire == "basic":
            return {}  # handled via auth=(user, pass) in _execute_graphql

        # Bearer / api_key / custom_header / oauth2 — all just put a token in
        # a header. Differences are header_name + header_prefix.
        token = self._resolve_credential(config, *method["config_keys"])
        if not token:
            return {}

        header_name = method["header_name"] or "Authorization"
        prefix = method["header_prefix"] or ""
        if prefix and not prefix.endswith(" "):
            prefix = prefix + " "
        return {header_name: f"{prefix}{token}".strip()}

    @staticmethod
    def _resolve_credential(config: Dict[str, Any], *keys: str) -> Optional[str]:
        """Look up a credential value from config or environment.

        Tries each key in `keys` against `config`, then falls back to the
        env var derived from the key name (e.g. `access_token` → `ACCESS_TOKEN`).
        """
        for k in keys:
            v = config.get(k)
            if v:
                return str(v)
        for k in keys:
            v = os.environ.get(k.upper())
            if v:
                return v
        return None

    # ----- GraphQL execution ----------------------------------------------

    def _execute_graphql(
        self,
        query: str,
        variables: Optional[Dict[str, Any]],
        config: Dict[str, Any],
        *,
        timeout: int = 30,
    ) -> Dict[str, Any]:
        """POST a GraphQL document and return the `data` payload.

        - Sends Content-Type: application/json (required by GraphQL spec).
        - Surfaces any `errors[]` envelope as a GraphQLError.
        - Raises on non-200 responses.
        """
        endpoint = self._resolve_endpoint(config)
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        headers.update(self._build_auth_headers(config))

        body = {"query": query}
        if variables is not None:
            body["variables"] = variables

        # Basic auth uses requests.auth=(user, pass) instead of headers.
        # The dispatcher returns empty headers in that case; we recompute here.
        method = self._resolve_auth_method(config)
        auth = None
        if method and method["method"] == "basic":
            auth = (
                self._resolve_credential(config, "username") or "",
                self._resolve_credential(config, "password") or "",
            )

        # SSRF guard: the endpoint is resolved from connection config
        # (`endpoint` override or `{shop}` substitution), so refuse to send
        # the X-Shopify-Access-Token to internal services / private IPs /
        # loopback / link-local before the POST. Mirrors the generated
        # GraphQL template (connector_graphql.py.j2). Best-effort import so
        # an older base_connector copy without the helper degrades to no-op.
        # Opt-out for dev: MCP_ALLOW_PRIVATE_NETWORKS=true.
        try:
            from base_connector import _ssrf_check_url
            _ssrf_reason = _ssrf_check_url(endpoint)
        except Exception:
            _ssrf_reason = None
        if _ssrf_reason is not None:
            raise GraphQLError(f"SSRF guard blocked outbound GraphQL call: {_ssrf_reason}")

        try:
            resp = requests.post(endpoint, headers=headers, json=body, timeout=timeout, auth=auth)
        except requests.RequestException as e:
            raise GraphQLError(f"transport error: {e}") from e

        if resp.status_code != 200:
            raise GraphQLError(
                f"HTTP {resp.status_code}: {resp.text[:200]}",
                status_code=resp.status_code,
            )

        try:
            payload = resp.json()
        except ValueError as e:
            raise GraphQLError(f"invalid json response: {e}") from e

        # GraphQL `errors[]` envelope — non-empty means failure even on 200 OK
        if isinstance(payload, dict) and payload.get("errors"):
            errs = payload.get("errors") or []
            msg = "; ".join(str(e.get("message") or "") for e in errs[:3] if isinstance(e, dict))
            raise GraphQLError(f"graphql errors: {msg}", errors=errs)

        return (payload or {}).get("data") or {}

    # ----- Generic dispatcher (lazy-mode core) ------------------------------

    def execute_operation(
        self,
        operation_name: str,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Execute a registered operation by name. Lazy-mode dispatch.

        Tolerates schema-qualified operation names. ``discover_schema``
        emits tables with a ``schema`` field set to "shopify"; the UI
        joins schema+name for display ("shopify.products") and the HITL
        table-picker persists that joined string verbatim into
        ``pipelines.config.selected_tables``. Downstream when the
        executor calls this method with the persisted name, "shopify."
        is just a leading namespace — the actual operation key is
        the suffix ("products"). Strip the leading "<schema>." (where
        schema matches the connector_type's vendor prefix) so a HITL
        round-trip doesn't break SaaS pipelines.

        This is also called by all the per-operation methods below.
        """
        cfg = self._get_config(config)
        op_key = (operation_name or "").strip()
        op = GRAPHQL_OPERATIONS.get(op_key)
        if op is None and "." in op_key:
            # Try the suffix after the LAST dot — covers both "shopify.products"
            # and any future per-namespace shape like "shopify.admin.products".
            suffix = op_key.rsplit(".", 1)[-1]
            op = GRAPHQL_OPERATIONS.get(suffix)
        if op is None:
            raise GraphQLError(f"unknown operation '{operation_name}'")
        return self._execute_graphql(op["query"], variables or {}, cfg)

    # ----- Required core operations ----------------------------------------

    def test_connection(self, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Verify connectivity by issuing a minimal `__typename` query."""
        cfg = self._get_config(config)
        try:
            data = self._execute_graphql(
                query="{ __typename }",
                variables=None,
                config=cfg,
            )
            return {"success": True, "details": {"typename": data.get("__typename")}}
        except GraphQLError as e:
            return {"success": False, "error": str(e)}

    def validate_config(self, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Confirm required config fields are present."""
        cfg = self._get_config(config)
        required: List[str] = [
"shop",
"access_token",
        ]
        missing = [
            name for name in required
            if not (cfg.get(name) or os.environ.get(name.upper()))
        ]
        if missing:
            return {"valid": False, "missing": missing}
        return {"valid": True}

    def discover_schema(self, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Discover the source schema via real GraphQL introspection.

        Implements the canonical discovery contract every source connector
        must satisfy (see docs/discovery.md):

            {
              "success": bool,
              "tables": [
                {
                  "name":        str,          # resource / table name
                  "schema":      str | None,   # namespace (db/schema)
                  "columns":     [             # populated when available
                    {"name": str, "type": str}
                  ],
                  "row_count":   int,          # -1 sentinel == unknown
                  "description": str | None,
                  "type":        "query|table|collection",
                },
                ...
              ],
              "operations": [...],
              "error":      str | None,
            }

        The previous implementation hardcoded the table list with empty
        columns and no row counts, so the HITL table-selection UI showed
        "products / orders / customers …" with `columns=0, row_count=0`
        even when the connection was broken or pointed at an empty
        store. That hid auth errors and gave users no schema signal.
        We now:

          1. Verify auth via ``test_connection`` and fail closed on
             auth errors instead of returning a hardcoded list.
          2. Run a GraphQL ``__type`` introspection query for every
             known operation to enumerate the leaf fields of the
             response type (after unwrapping Relay ``*Connection``
             wrappers down to the underlying ``Node`` type).
          3. Best-effort row counts using Shopify's ``<resource>Count``
             queries — leave ``row_count = -1`` when the count query is
             not exposed by the API (the UI knows ``-1`` means unknown
             and renders nothing rather than a misleading zero).

        Per-table errors are localised: if introspection fails for one
        resource we keep going and just leave its columns empty, so a
        partial schema is still better than nothing.
        """
        cfg = self._get_config(config)

        # 1. Fail-closed auth check. The hardcoded fallback used to
        # silently succeed; we'd rather tell the user their token is
        # bad than show them a fake schema.
        try:
            auth_check = self.test_connection(cfg)
        except Exception as e:  # pragma: no cover - defensive
            return {
                "success": False,
                "error": f"connection test raised: {e}",
                "tables": [],
                "operations": [],
            }
        if not auth_check.get("success"):
            return {
                "success": False,
                "error": "auth check failed: " + str(auth_check.get("error", "unknown")),
                "tables": [],
                "operations": [],
            }

        # 2 & 3. For each operation, introspect its return type and
        # best-effort count. Each per-resource lookup is independent —
        # an introspection failure on `orders` shouldn't take down
        # `products`.
        tables: List[Dict[str, Any]] = []
        for name, op in GRAPHQL_OPERATIONS.items():
            return_type = op.get("return_type") or ""
            raw_fields = self._introspect_raw_fields(self._unwrap_connection_type(return_type), cfg)
            row_count = self._best_effort_count(op.get("graphql_name") or name, cfg)
            # Canonical column types — sinks rely on canonical, not raw GraphQL names.
            columns = [
                {"name": fname, "type": canonicalize_type(raw_type)}
                for fname, raw_type in raw_fields
            ]
            # PK detection: any field whose GraphQL type is `ID` is a PK
            # candidate. Generic across all Relay-compliant GraphQL APIs;
            # Shopify resources each expose exactly one `id: ID!`.
            pk_fields = [fname for fname, raw_type in raw_fields if raw_type == "ID"]
            tables.append({
                "name": name,
                "schema": "shopify",
                "columns": columns,
                "row_count": row_count,
                "description": op.get("description", ""),
                "type": op.get("operation_type", "query"),
                "primary_keys": pk_fields,
                "primary_key_source": "declared" if pk_fields else "synthetic",
            })

        ops = [
            {"name": name, **{k: v for k, v in op.items() if k != "query"}}
            for name, op in GRAPHQL_OPERATIONS.items()
        ]
        return {
            "success": True,
            "tables": tables,
            "operations": ops,
        }

    # ----- Introspection helpers -------------------------------------------
    #
    # These are local to the Shopify connector for now but match the
    # canonical discovery contract documented in
    # llm-service/src/agents/tool_generator/templates/connector_graphql.py.j2
    # — the GraphQL template emits the same helpers so newly-generated
    # connectors comply with the contract by default.

    @staticmethod
    def _unwrap_connection_type(type_name: str) -> str:
        """Strip Relay Connection wrappers so we introspect the node type.

        Shopify (and most Relay-compliant GraphQL APIs) wrap list results
        in ``<X>Connection`` { edges { node: X, cursor }, pageInfo }.
        The interesting fields live on ``X``, not ``XConnection``. Without
        this unwrap, introspection of ``ProductConnection`` returns just
        ``edges`` and ``pageInfo`` which is useless to a table-selection
        UI.
        """
        if not type_name:
            return ""
        if type_name.endswith("Connection"):
            return type_name[:-len("Connection")]
        return type_name

    def _introspect_raw_fields(self, target_type: str, config: Dict[str, Any]) -> List[tuple]:
        """Return ``[(field_name, raw_gql_type_name)]`` for a GraphQL type.

        Keeps the raw GraphQL type name (e.g. ``ID``, ``String``,
        ``MoneyBag``) so callers can both (a) canonicalize for the
        generic pipeline and (b) detect ``ID`` fields for primary-key
        declaration. Returns ``[]`` when introspection is unavailable.
        """
        if not target_type:
            return []
        introspect = (
            "query IntrospectType($name: String!) {"
            "  __type(name: $name) {"
            "    name kind"
            "    fields { name type { name kind ofType { name kind ofType { name kind } } } }"
            "  }"
            "}"
        )
        try:
            data = self._execute_graphql(introspect, {"name": target_type}, config)
        except Exception:
            return []
        type_info = data.get("__type") if isinstance(data, dict) else None
        if not isinstance(type_info, dict):
            return []
        out: List[tuple] = []
        for f in type_info.get("fields") or []:
            if not isinstance(f, dict):
                continue
            fname = f.get("name", "")
            raw_type = self._flatten_graphql_type(f.get("type"))
            out.append((fname, raw_type))
        return out

    def _introspect_columns(self, target_type: str, config: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Canonical-typed column list. Kept for callers that don't need PK info."""
        return [
            {"name": fname, "type": canonicalize_type(raw_type)}
            for fname, raw_type in self._introspect_raw_fields(target_type, config)
        ]

    def _flatten_graphql_type(self, type_node: Optional[Dict[str, Any]]) -> str:
        """Walk a GraphQL type-ref chain (NonNull / List wrappers) to the leaf name."""
        if not isinstance(type_node, dict):
            return "Unknown"
        name = type_node.get("name")
        if name:
            return name
        of_type = type_node.get("ofType")
        if of_type is not None:
            return self._flatten_graphql_type(of_type)
        return type_node.get("kind") or "Unknown"

    def _best_effort_count(self, graphql_resource: str, config: Dict[str, Any]) -> int:
        """Return the row count for a resource via Shopify's ``<X>Count`` queries.

        Shopify exposes zero-cost count queries for many top-level
        resources (``productsCount``, ``ordersCount``, ``customersCount``,
        ``collectionsCount``). Resources without a count query are not
        an error — we return ``-1`` to mean "unknown" so the UI can
        render "?" instead of a misleading zero.
        """
        # Only resources known to expose a count query in the Admin API
        # v2024-10. Cheaper than blindly probing every operation.
        count_capable = {"products", "orders", "customers", "collections"}
        if graphql_resource not in count_capable:
            return -1
        query = "query Count { %sCount { count } }" % graphql_resource
        try:
            data = self._execute_graphql(query, None, config)
        except Exception:
            return -1
        if not isinstance(data, dict):
            return -1
        block = data.get("%sCount" % graphql_resource)
        if isinstance(block, dict):
            v = block.get("count")
            if isinstance(v, int):
                return v
        if isinstance(block, int):
            return block
        return -1

    def get_capabilities(self, params: Dict = None) -> Dict[str, Any]:
        # Accept `params`: the base dispatcher resolves this by name at step 2 and
        # calls handler(normalized_args) with one positional arg, so a no-arg
        # override raises "takes 1 positional argument but 2 were given" — the
        # step-5 zero-arg fallback is unreachable once hasattr() has matched.
        """Operation listing for MCP auto-dispatch."""
        return {
            "connector_type": "shopify-admin-graphql",
            "protocol": "graphql",
            "supports_source": True,
            "supports_destination": True,
            "operations": [
                {
                    "name": "test_connection",
                    "type": "core",
                    "method": "shopify-admin-graphql_test_connection",
                },
                {
                    "name": "validate_config",
                    "type": "core",
                    "method": "shopify-admin-graphql_validate_config",
                },
                {
                    "name": "discover_schema",
                    "type": "core",
                    "method": "shopify-admin-graphql_discover_schema",
                },
                {
                    "name": "get_capabilities",
                    "type": "core",
                    "method": "shopify-admin-graphql_get_capabilities",
                },
                {
                    "name": "export",
                    "type": "source",
                    "method": "shopify-admin-graphql_export",
                },
                {
                    "name": "shop",
                    "type": "source",
                    "method": "shopify-admin-graphql_shop",
                },
                {
                    "name": "products",
                    "type": "source",
                    "method": "shopify-admin-graphql_products",
                },
                {
                    "name": "orders",
                    "type": "source",
                    "method": "shopify-admin-graphql_orders",
                },
                {
                    "name": "customers",
                    "type": "source",
                    "method": "shopify-admin-graphql_customers",
                },
                {
                    "name": "collections",
                    "type": "source",
                    "method": "shopify-admin-graphql_collections",
                },
                {
                    "name": "inventory_items",
                    "type": "source",
                    "method": "shopify-admin-graphql_inventory_items",
                },
                {
                    "name": "import_data",
                    "type": "destination",
                    "method": "shopify-admin-graphql_import_data",
                },
                {
                    "name": "upsert_data",
                    "type": "destination",
                    "method": "shopify-admin-graphql_upsert_data",
                },
            ],
        }

    # ----- Generic export / import (alias to dispatcher) -------------------

    def export(
        self,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Source-side export — base-class calling convention: export(params: Dict).

        _handle_tool_call always calls handler(normalized_args) where
        normalized_args is a dict.  The dict may contain:
            table / operation_name / operation — the GraphQL operation to run
            config  — connection config
            variables / filters — optional query variables
        """
        if isinstance(params, str):
            # Legacy positional call: export("products")
            operation_name = params
            cfg: Dict[str, Any] = {}
            variables: Dict[str, Any] = {}
        else:
            cfg = self._get_config(params)
            operation_name = (
                (params or {}).get("table")
                or (params or {}).get("endpoint")  # normalisation target for api_saas
                or (params or {}).get("operation_name")
                or (params or {}).get("operation")
            )
            variables = (params or {}).get("variables") or (params or {}).get("filters") or {}

        # Canonicalise schema-qualified table names BEFORE we route on
        # the operation. The HITL table picker persists names verbatim
        # from discover_schema, which joins schema+name for display
        # ("shopify.products"). The actual operation key is the suffix.
        # Strip here so downstream checks (e.g. the singleton-shop
        # detection below, dispatcher lookup) all see the canonical key.
        if isinstance(operation_name, str) and "." in operation_name:
            operation_name = operation_name.rsplit(".", 1)[-1]

        # Shopify Admin GraphQL Relay connections require "first" or "last" on
        # every connection field, AND enforce a hard cap of 250 per page.
        # The orchestrator's executor passes a `limit` derived from cost
        # estimation that can be in the tens of thousands; capping here keeps
        # Shopify happy and pagination handles the rest of the rows.
        if operation_name and operation_name not in ("shop",):
            variables = dict(variables or {})
            if "first" not in variables and "last" not in variables:
                requested = int((params or {}).get("limit") or 250)
                variables["first"] = max(1, min(requested, 250))

        if not operation_name:
            return {"success": False, "error": "Missing table/operation_name parameter"}

        # ---------------------------------------------------------------
        # Incremental sync — read `since` from params, translate to a
        # Shopify search-string predicate, and track max(updatedAt) so we
        # can return it as the watermark for the executor to persist.
        #
        # Contract (see shared/mcp-connectors/INCREMENTAL.md):
        #   params.since                  -> ISO-8601 timestamp (optional)
        #   variables.query                -> existing user filter (optional)
        #
        # The executor (executor.go:1370-1374) sets `since`, `updated_since`,
        # `modified_since`, and `modified_after` to the same value from the
        # checkpoint; we read whichever is present. NEVER log the raw value
        # below INFO — it's a customer-data leakage hint even though it's
        # just a date.
        # ---------------------------------------------------------------
        raw_since: Any = None
        if isinstance(params, dict):
            for key in ("since", "updated_since", "modified_since", "modified_after"):
                v = params.get(key)
                if v:
                    raw_since = v
                    break
        normalized_since = _normalize_iso_timestamp(raw_since)
        if raw_since and not normalized_since:
            # Don't crash on a malformed checkpoint; just degrade to full fetch.
            logger.warning(
                "[Incremental] %s: malformed since value, falling back to full fetch",
                operation_name,
            )

        incremental_capable = _INCREMENTAL_CAPABLE.get(operation_name, False)
        if incremental_capable and normalized_since:
            variables = dict(variables or {})
            existing_query = variables.get("query") if isinstance(variables.get("query"), str) else None
            combined = _compose_query_filter(existing_query, normalized_since)
            if combined:
                variables["query"] = combined
                logger.info(
                    "[Incremental] %s: applying updated_at filter (since=%s)",
                    operation_name, normalized_since,
                )

        # ---------------------------------------------------------------
        # SHOPIFY-BulkOps dispatch (opt-in via threshold or explicit flag)
        # ---------------------------------------------------------------
        # Bulk Operations is Shopify's high-throughput export path: submit
        # one query, Shopify processes it server-side, returns a downloadable
        # JSONL file. ~10x faster than paginated GraphQL for large stores
        # (>10k rows). For small stores (dev/Basic with <10k rows), the
        # bulk path's submit+poll overhead is net slower, so the regular
        # path is kept for them.
        #
        # Dispatch rules:
        #   use_bulk_ops=True        -> bulk path
        #   use_bulk_ops=False       -> regular path (today's behavior)
        #   use_bulk_ops="auto" (default):
        #     - count probe via <resource>Count
        #     - if count >= bulk_ops_threshold -> bulk path
        #     - else (or count unknown) -> regular path
        #
        # ANY bulk-path failure (userError, FAILED, timeout, download
        # error) falls back to the regular paginated path. Bulk ops
        # failure must NEVER cause export to fail.
        use_bulk_ops_raw = (params or {}).get("use_bulk_ops", "auto") if isinstance(params, dict) else "auto"
        bulk_threshold_raw = (params or {}).get("bulk_ops_threshold") if isinstance(params, dict) else None

        try:
            bulk_decision = self._decide_bulk_path(
                operation_name=operation_name,
                use_bulk_ops=use_bulk_ops_raw,
                bulk_threshold=bulk_threshold_raw,
                config=cfg,
            )
        except Exception as exc:  # pragma: no cover - defensive
            logger.warning("[BulkOps] dispatch decision raised, using regular path: %s", exc)
            bulk_decision = False

        if bulk_decision and _bulk_ops is not None:
            bulk_params = params if isinstance(params, dict) else {}
            bulk_result = self._try_bulk_export(operation_name=operation_name, config=cfg, params=bulk_params)
            if bulk_result is not None:
                return bulk_result
            # bulk_result is None == fall back to regular path; warning
            # already logged inside _try_bulk_export.

        # ---------------------------------------------------------------
        # Regular paginated path. Loops EVERY page of the Relay connection
        # inside this single export() call (Shopify caps a page at 250 rows),
        # accumulating all rows so tables in the 251–9,999 range — below the
        # bulk-ops threshold but above one page — return in full instead of
        # being silently truncated to the first 250. The watermark contract
        # below then scans the full set for max(updatedAt).
        #
        # Singleton operations (e.g. ``shop``) have no connection / ``first``
        # argument and take the single-call path unchanged.
        #
        # Resume: when a hard cap (record/page) stops the loop early it
        # returns ``has_more=True`` + ``next_cursor``; the executor replays
        # that as ``params.cursor`` on the next call. The cap is only reached
        # when bulk-ops is force-disabled on a very large table — auto-mode
        # routes ≥10k-row tables to the bulk path before reaching here.
        # ---------------------------------------------------------------
        page_size = variables.get("first") if isinstance(variables, dict) else None
        next_cursor: Optional[str] = None
        has_more = False
        if page_size:
            start_after = (params or {}).get("cursor") if isinstance(params, dict) else None
            max_records = int((params or {}).get("limit") or 10000) if isinstance(params, dict) else 10000

            def _execute_page(page_vars: Dict[str, Any]) -> Any:
                return self.execute_operation(
                    operation_name, variables=page_vars or None, config=cfg or None
                )

            try:
                rows, next_cursor, has_more = GraphQLPaginationHandler().fetch_all_pages(
                    _execute_page,
                    variables,
                    page_size=int(page_size),
                    max_records=max_records,
                    start_after=start_after,
                    row_extractor=_normalize_to_rows,
                )
            except Exception as exc:
                return {"success": False, "error": str(exc)}
        else:
            # Singleton / non-connection operation (e.g. ``shop``): single call.
            try:
                data = self.execute_operation(operation_name, variables=variables or None, config=cfg or None)
            except Exception as exc:
                return {"success": False, "error": str(exc)}
            rows = _normalize_to_rows(data)

        cols = list(rows[0].keys()) if rows else []

        response: Dict[str, Any] = {
            "success": True,
            "data": rows,
            "columns": cols,
            "row_count": len(rows),
            "has_more": has_more,
        }
        if has_more and next_cursor:
            response["next_cursor"] = next_cursor
            response["paging_mode"] = "cursor"

        # Compute and attach the watermark when the resource is incremental-
        # capable. The executor reads ``stats.watermark = {field, value}``
        # (executor.go:1436-1440) and persists it; on the next run it sends
        # the value back as ``since``.
        #
        # Edge cases (per contract):
        #   * No rows seen AND a prior `since` exists  -> echo `since` so the
        #     existing checkpoint stays advanced rather than being cleared.
        #   * No rows seen AND no prior `since`       -> omit watermark (the
        #     executor keeps whatever it had, which is nothing — first run).
        #   * Resource not incremental-capable         -> never attach
        #     watermark; executor preserves prior checkpoint.
        if incremental_capable:
            running = _max_updated_at(rows, None)
            watermark_value: Optional[str] = None
            if running is not None:
                watermark_value = running[0]
            elif normalized_since:
                # 0 rows returned but we had a prior watermark — keep it.
                watermark_value = normalized_since

            if watermark_value:
                response["stats"] = {
                    "watermark": {
                        "field": "last_modified",
                        "value": watermark_value,
                    }
                }
                response["max_watermark"] = watermark_value

        return response

    # ----- Bulk Operations helpers (SHOPIFY-BulkOps) ----------------------

    # Shopify resources that expose a free <X>Count query in Admin 2024-10.
    # Resources outside this set don't get auto-bulk (we don't gamble on
    # bulk's submit+poll overhead for unknown sizes — better to keep the
    # regular path's predictable per-page latency).
    _BULK_COUNT_CAPABLE = {"products", "orders", "customers", "collections"}

    def _decide_bulk_path(
        self,
        *,
        operation_name: str,
        use_bulk_ops: Any,
        bulk_threshold: Any,
        config: Dict[str, Any],
    ) -> bool:
        """Return True iff this export should attempt the bulk path."""
        if _bulk_ops is None:
            return False

        # Explicit override wins. Accept the same values the orchestrator
        # might serialize: bool, "true"/"false", "True"/"False", "auto".
        if isinstance(use_bulk_ops, bool):
            return use_bulk_ops
        if isinstance(use_bulk_ops, str):
            v = use_bulk_ops.strip().lower()
            if v in ("true", "yes", "1", "force"):
                return True
            if v in ("false", "no", "0", "off"):
                return False
            # "auto" / "" / anything else -> threshold-based decision.

        # "auto" mode: count probe + threshold.
        if operation_name == "shop":
            # shop is a singleton, never benefits from bulk ops.
            return False
        if operation_name not in self._BULK_COUNT_CAPABLE:
            # No reliable count query for this resource (e.g. inventory_items).
            # Don't gamble on bulk; stay on regular pagination.
            return False

        # Resolve threshold: param > env > default(10_000).
        try:
            threshold = int(bulk_threshold) if bulk_threshold is not None else _bulk_ops.env_threshold(10000)
        except (TypeError, ValueError):
            threshold = _bulk_ops.env_threshold(10000)

        if threshold <= 0:
            # threshold=0 means "force bulk in auto mode".
            return True

        count = self._best_effort_count(operation_name, config)
        if count is None or count < 0:
            return False
        return count >= threshold

    def _try_bulk_export(
        self,
        *,
        operation_name: str,
        config: Dict[str, Any],
        params: Dict[str, Any],
    ) -> Optional[Dict[str, Any]]:
        """Run the bulk-export path. Return None on failure (caller falls back).

        Returns the export() success-shape dict on completion (even with
        zero rows). Returns None when bulk ops failed and the caller
        should fall back to regular pagination.
        """
        if _bulk_ops is None:
            return None

        op = GRAPHQL_OPERATIONS.get(operation_name)
        if op is None:
            logger.warning("[BulkOps] no GraphQL op for %r, falling back", operation_name)
            return None
        inner_query = op.get("query") or ""
        if not inner_query.strip():
            return None

        cfg_copy = dict(config or {})

        # Adapter: post_graphql callable bound to this connector's auth +
        # endpoint. Returns the GraphQL `data` payload, raises GraphQLError
        # on transport/HTTP/GraphQL-error envelope failure.
        def _post_graphql(query: str, variables: Optional[Dict[str, Any]]) -> Dict[str, Any]:
            return self._execute_graphql(query, variables, cfg_copy, timeout=60)

        # Adapter: get_url for the JSONL download. The bulk-op URL is a
        # Google Cloud Storage signed URL — auth headers MUST NOT be sent
        # (some signed URLs reject extra Authorization). Use a fresh
        # requests.get with no headers added.
        def _get_url(url: str, timeout: int) -> tuple[int, str]:
            # SSRF guard: the bulk-op download URL comes from Shopify's
            # response (a GCS signed URL). Guard it defensively so a
            # malicious/MITM'd response can't redirect the fetch to an
            # internal target. GCS URLs are public, so legit traffic passes.
            try:
                from base_connector import _ssrf_check_url
                _ssrf_reason = _ssrf_check_url(url)
            except Exception:
                _ssrf_reason = None
            if _ssrf_reason is not None:
                raise GraphQLError(f"SSRF guard blocked bulk download: {_ssrf_reason}")
            resp = requests.get(url, timeout=timeout)
            return resp.status_code, resp.text

        timeout_sec = _bulk_ops.env_timeout()
        poll_interval = _bulk_ops.env_poll_interval()

        try:
            result = _bulk_ops.run_bulk_export(
                inner_query=inner_query,
                post_graphql=_post_graphql,
                get_url=_get_url,
                poll_interval_sec=poll_interval,
                timeout_sec=timeout_sec,
            )
        except Exception as e:
            # Belt-and-suspenders: run_bulk_export shouldn't raise, but
            # if it does, never let bulk-ops failure break export().
            logger.warning("[BulkOps] run_bulk_export raised, falling back: %s", e)
            return None

        if not result.ok:
            logger.warning(
                "[BulkOps] %s failed (status=%s, elapsed=%.1fs, error=%s), falling back to regular pagination",
                operation_name,
                result.status,
                result.elapsed_sec,
                result.error,
            )
            return None

        # Success — normalize rows the same way the regular path does so
        # the downstream sink sees identical row shape regardless of which
        # path produced the data.
        rows = [_flatten_row(r) for r in (result.rows or []) if isinstance(r, dict)]
        cols = list(rows[0].keys()) if rows else []
        logger.info(
            "[BulkOps] %s completed via bulk path: rows=%d, object_count=%s, elapsed=%.1fs",
            operation_name,
            len(rows),
            result.object_count,
            result.elapsed_sec,
        )
        bulk_response: Dict[str, Any] = {
            "success": True,
            "data": rows,
            "columns": cols,
            "row_count": len(rows),
            "has_more": False,
            "bulk_ops": {
                "used": True,
                "operation_id": result.operation_id,
                "object_count": result.object_count,
                "elapsed_sec": result.elapsed_sec,
            },
        }

        # Emit the incremental watermark exactly as the regular path does, so a
        # ≥10k-row table routed through bulk ops still advances its checkpoint
        # (otherwise every incremental run would re-export the whole table).
        # Bulk JSONL returns the full result set, so max(updatedAt) over `rows`
        # is the true high-water mark. Mirrors the regular-path contract:
        # 0 rows + prior `since` -> echo `since`; not incremental-capable -> skip.
        if _INCREMENTAL_CAPABLE.get(operation_name, False):
            since_value = None
            for key in ("since", "updated_since", "modified_since", "modified_after"):
                v = (params or {}).get(key)
                if v:
                    since_value = _normalize_iso_timestamp(v)
                    break
            running = _max_updated_at(rows, None)
            watermark_value = running[0] if running is not None else since_value
            if watermark_value:
                bulk_response["stats"] = {
                    "watermark": {"field": "last_modified", "value": watermark_value}
                }
                bulk_response["max_watermark"] = watermark_value

        return bulk_response

    # ----- Destination (write) ---------------------------------------------

    @staticmethod
    def _resolve_dest_resource(params: Optional[Dict[str, Any]]) -> str:
        """Resolve the writable resource name from the call params.

        The sink sends the destination as ``table`` (or ``object``); a HITL
        round-trip may prefix it with the connector's schema ("shopify.products")
        — strip that. A singular alias ("product") maps to "products".
        """
        raw = (
            (params or {}).get("table")
            or (params or {}).get("endpoint")  # normalisation target for api_saas
            or (params or {}).get("object")
            or ""
        )
        name = str(raw).strip()
        if "." in name:
            name = name.rsplit(".", 1)[-1]
        if name not in _WRITABLE_RESOURCES and (name + "s") in _WRITABLE_RESOURCES:
            name = name + "s"
        return name

    def _write_records(
        self,
        resource: str,
        rows: List[Dict[str, Any]],
        cfg: Dict[str, Any],
        *,
        mode: str,
    ) -> Tuple[int, List[str]]:
        """Run the per-record create/update mutations for a writable resource.

        ``mode`` is "append" (always create) or "upsert" (update when the record
        carries a product GID, else create). Returns ``(written, errors)``;
        ``written`` counts only rows whose mutation returned NO ``userErrors``
        (Shopify reports validation failures there on a 200, not via the
        top-level GraphQL errors envelope).
        """
        spec = _WRITABLE_RESOURCES[resource]
        build_input = spec["build_input"]
        written = 0
        errors: List[str] = []
        for idx, row in enumerate(rows or []):
            try:
                input_obj, is_update = build_input(row)
                if mode == "append":
                    # Append never updates: drop any id so it always creates.
                    is_update = False
                    input_obj.pop("id", None)
                if is_update:
                    mutation = spec["update_mutation"]
                    result_key = spec["update_result_key"]
                else:
                    mutation = spec["create_mutation"]
                    result_key = spec["create_result_key"]
                data = self._execute_graphql(mutation, {"input": input_obj}, cfg)
            except GraphQLError as e:
                errors.append(f"record {idx}: {e}")
                continue
            payload = (data or {}).get(result_key) or {}
            user_errors = payload.get("userErrors") or []
            if user_errors:
                msg = "; ".join(
                    f"{'.'.join(ue.get('field') or []) or '?'}: {ue.get('message')}"
                    for ue in user_errors[:3] if isinstance(ue, dict)
                )
                errors.append(f"record {idx}: {msg}")
            else:
                written += 1
        return written, errors

    def _destination_write(
        self,
        params: Optional[Dict[str, Any]],
        *,
        mode: str,
    ) -> Dict[str, Any]:
        """Shared body for import_data (append) / upsert_data (upsert).

        Reads rows from the sink's ``data`` key via ``prepare_import_data``
        (which also resolves claim-checked / staged batches), falling back to
        raw ``data``/``records`` if the base helper is unavailable. Returns the
        SaaS-destination shape ``{success, rows_inserted|rows_upserted, errors}``.
        """
        count_key = "rows_upserted" if mode == "upsert" else "rows_inserted"

        # Legacy positional / string call — nothing to write.
        if params is None or isinstance(params, str):
            return {"success": True, count_key: 0, "message": "No data to write"}

        cfg = self._get_config(params)
        resource = self._resolve_dest_resource(params)
        if resource not in _WRITABLE_RESOURCES:
            return {
                "success": False,
                count_key: 0,
                "error": (
                    f"Shopify destination supports {sorted(_WRITABLE_RESOURCES)}; "
                    f"got '{resource or '(none)'}'"
                ),
            }

        rows: Optional[List[Dict[str, Any]]] = None
        try:
            prepared = self.prepare_import_data(params)
            if isinstance(prepared, dict):
                if not prepared.get("success", True):
                    return prepared
                rows = prepared.get("data")
                if prepared.get("config"):
                    cfg = prepared["config"]
        except Exception:  # pragma: no cover - defensive
            rows = None
        if rows is None:
            rows = (params.get("data") or params.get("records") or [])

        if not rows:
            return {"success": True, count_key: 0, "message": "No data to write"}

        written, errors = self._write_records(resource, rows, cfg, mode=mode)
        return {
            "success": len(errors) == 0,
            count_key: written,
            "errors": errors[:10],
        }

    def import_data(
        self,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Destination APPEND: create one Shopify record per row.

        The sink calls ``shopify-admin-graphql_import_data`` for keyless /
        append-mode destinations, sending rows under ``data`` and the resource
        under ``table``. Returns ``{success, rows_inserted, errors}``.
        """
        return self._destination_write(params, mode="append")

    def upsert_data(
        self,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Destination UPSERT: update a record carrying a product GID, else
        create it. The sink calls ``shopify-admin-graphql_upsert_data`` when
        key fields are present. Returns ``{success, rows_upserted, errors}``.
        """
        return self._destination_write(params, mode="upsert")

    # ----- Eager-mode per-operation methods -------------------------------
    # Generated when total ops ≤ LAZY_OPS_THRESHOLD. Above the threshold we
    # only emit the dispatcher above (callers use execute_operation()).

    def shop(
        self,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Retrieve shop information and settings

        GraphQL: `query shop`
        Returns: Shop
        """
        return self.execute_operation("shop", variables=variables, config=config)

    def products(
        self,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """List products with Relay connection pagination

        GraphQL: `query products`
        Returns: ProductConnection
        """
        return self.execute_operation("products", variables=variables, config=config)

    def orders(
        self,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """List orders with Relay connection pagination

        GraphQL: `query orders`
        Returns: OrderConnection
        """
        return self.execute_operation("orders", variables=variables, config=config)

    def customers(
        self,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """List customers with Relay connection pagination

        GraphQL: `query customers`
        Returns: CustomerConnection
        """
        return self.execute_operation("customers", variables=variables, config=config)

    def collections(
        self,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """List collections with Relay connection pagination

        GraphQL: `query collections`
        Returns: CollectionConnection
        """
        return self.execute_operation("collections", variables=variables, config=config)

    def inventory_items(
        self,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """List inventory items with Relay connection pagination

        GraphQL: `query inventoryItems`
        Returns: InventoryItemConnection
        """
        return self.execute_operation("inventory_items", variables=variables, config=config)



def _flatten_value(v: Any) -> Any:
    """Serialize nested dicts/lists as JSON strings so Postgres can store them."""
    if isinstance(v, (dict, list)):
        return json.dumps(v, ensure_ascii=False, default=str)
    return v


def _flatten_row(row: Dict[str, Any]) -> Dict[str, Any]:
    """Convert all values in a record to Postgres-compatible scalars.

    psycopg2 raises ``can't adapt type 'dict'`` when a column value is a
    Python dict (e.g. nested GraphQL objects like ``plan: {displayName: ...}``).
    We JSON-serialize those values so they land as TEXT/JSONB.
    """
    return {k: _flatten_value(v) for k, v in row.items()}


def _extract_connection_rows(obj: Any, depth: int = 0) -> Optional[List[Dict[str, Any]]]:
    """Depth-first search for Relay connection rows inside a GraphQL object.

    Handles two standard Relay pagination patterns:
      - ``edges[].node``  — full Relay spec (Shopify, GitHub GraphQL v4, Linear, …)
      - ``nodes[]``       — shorthand available on many Relay-compliant APIs

    Recurses into dict-valued children ONLY (not into list-valued sub-fields
    such as ``tags``, ``features``, etc.) so incidental array attributes on a
    single-object response don't get mistaken for the primary result set.

    Returns ``None`` when no connection pattern is found, so callers can
    distinguish "nothing found" from "found an empty list".
    """
    if not isinstance(obj, dict) or depth > 4:
        return None
    # Relay edges pattern: {edges: [{node: {...}}, ...]}
    edges = obj.get("edges")
    if isinstance(edges, list):
        rows = [
            e["node"] for e in edges
            if isinstance(e, dict) and isinstance(e.get("node"), dict)
        ]
        return rows  # may be empty list — that's a valid "found but empty" signal
    # Relay nodes shortcut: {nodes: [{...}, ...]}  (GitHub, some Linear APIs)
    nodes = obj.get("nodes")
    if isinstance(nodes, list):
        rows = [n for n in nodes if isinstance(n, dict)]
        return rows
    # Recurse into dict-valued children to handle wrapped connections like
    # {"viewer": {"repositories": {"edges": [...]}}}  (GitHub viewer pattern)
    for v in obj.values():
        if isinstance(v, dict):
            result = _extract_connection_rows(v, depth + 1)
            if result is not None:
                return result
    return None


def _normalize_to_rows(data: Any) -> List[Dict[str, Any]]:
    """Best-effort flattening of a GraphQL response into a row list.

    Handles all common GraphQL response shapes at any nesting depth:
      1. Relay connection (edges/node) — direct or wrapped in a parent object:
           ``{"products": {"edges": [{"node": {...}}]}}``
           ``{"viewer": {"repositories": {"edges": [{"node": {...}}]}}}``
      2. Relay nodes shortcut:
           ``{"issues": {"nodes": [{...}, ...]}}``
      3. Top-level plain list (non-Relay):
           ``{"orders": [{...}, {...}]}``
      4. Single object:
           ``{"shop": {...}}``
    Falls back to wrapping ``data`` itself in a single-element list.

    All nested dicts/lists are JSON-serialised via ``_flatten_row`` so the
    downstream PostgreSQL connector (psycopg2) can store them without raising
    ``can't adapt type 'dict'``.
    """
    if isinstance(data, dict):
        if len(data) == 1:
            (only_value,) = data.values()
            if isinstance(only_value, dict):
                # Try Relay connection (edges/nodes) recursively — handles
                # both top-level and wrapped (e.g. viewer → repositories)
                rows = _extract_connection_rows(only_value)
                if rows is not None:
                    return [_flatten_row(r) for r in rows]
                # Fall back: plain list field (non-Relay) or single object
                for v in only_value.values():
                    if isinstance(v, list):
                        list_rows = [r for r in v if isinstance(r, dict)]
                        if list_rows:
                            return [_flatten_row(r) for r in list_rows]
                return [_flatten_row(only_value)]
            if isinstance(only_value, list):
                return [_flatten_row(r) for r in only_value if isinstance(r, dict)]
        # Multi-key dict: try connection extraction before treating as a single row
        rows = _extract_connection_rows(data)
        if rows is not None:
            return [_flatten_row(r) for r in rows]
        return [_flatten_row(data)]
    if isinstance(data, list):
        return [_flatten_row(r) for r in data if isinstance(r, dict)]
    return []


if __name__ == "__main__":
    connector = ShopifyConnector()

    http_mode = os.getenv("MCP_HTTP_MODE", "false").lower() == "true"
    port = int(os.getenv("MCP_PORT", os.getenv("PORT", "8000")))

    if http_mode or os.getenv("DOCKER_CONTAINER"):
        try:
            import uvicorn
            from fastapi import FastAPI
            # Decimal crosses this boundary as a STRING, never a float. FastAPI's
            # jsonable_encoder maps Decimal -> float (ENCODERS_BY_TYPE), which silently
            # destroys precision on the way to the sink: a numeric 123456789012345678.5
            # arrives as 1.2345678901234568e+17, and the orchestrator writes that back
            # out as 123456789012345680 -- a changed value, with no error raised anywhere.
            # The stdio path already serialises with json.dumps(..., default=str), so
            # HTTP mode was the only lossy leg -- and it is the leg every containerised
            # deployment uses, which is why no stdio-based test could ever see it.
            from decimal import Decimal as _Decimal
            from fastapi.encoders import ENCODERS_BY_TYPE as _ENCODERS_BY_TYPE
            _ENCODERS_BY_TYPE[_Decimal] = str

            app = FastAPI()

            @app.post("/test_connection")
            def api_test_connection(params: dict = {}):
                return connector.test_connection(params)

            @app.post("/validate_config")
            def api_validate_config(params: dict = {}):
                return connector.validate_config(params)

            @app.post("/discover_schema")
            def api_discover_schema(params: dict = {}):
                return connector.discover_schema(params)

            @app.post("/execute_operation")
            def api_execute_operation(params: dict = {}):
                return connector.execute_operation(
                    params.pop("operation_name", ""),
                    variables=params.pop("variables", None),
                    config=params,
                )

            @app.post("/export")
            def api_export(params: dict = {}):
                result = connector.export(params)
                return result.__dict__ if hasattr(result, "__dict__") else result

            @app.post("/mcp")
            def api_mcp(request: dict):
                # MCP JSON-RPC entry-point used by the orchestrator's executor.
                try:
                    request_dict = request if isinstance(request, dict) else {}
                    if "jsonrpc" not in request_dict:
                        request_dict = {
                            "jsonrpc": "2.0",
                            "id": request_dict.get("id", 1),
                            "method": request_dict.get("method"),
                            "params": request_dict.get("params") or {},
                        }
                    return connector.handle_request(request_dict)
                except Exception as e:
                    return {
                        "jsonrpc": "2.0",
                        "id": (request or {}).get("id", 1) if isinstance(request, dict) else 1,
                        "error": {"code": -32000, "message": str(e)},
                    }

            @app.get("/health")
            def health():
                return {"status": "ok"}

            logging.getLogger(__name__).info(
                "🚀 Starting Shopify GraphQL connector (HTTP) on port %d", port
            )
            uvicorn.run(app, host="0.0.0.0", port=port)
        except ImportError:
            connector.run()
    else:
        connector.run()
