#!/usr/bin/env python3
"""
Widgets-Graphql MCP Connector (GraphQL)
Auto-generated by Pure Agentic Pipeline v1.1

JSON-RPC server for Widgets-Graphql GraphQL operations.
Category:   api_saas
Protocol:   graphql
Endpoint:   https://api.widgets.test/graphql

DO NOT EDIT - This file is auto-generated. Make changes to the spec instead.
Generated: 2026-07-05T15:47:52.925352
"""

import json
import logging
import os
import sys
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple

import requests

# Parent dir for base_connector
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from base_connector import (
    BaseMCPConnector,
    ExportResult,
    ImportResult,
    ErrorItem,
    GraphQLPaginationHandler,
)

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Canonical type vocabulary for the generic discovery contract.
# Single source of truth: shared/mcp-connectors/schemas/response_schemas.py.
# Inlined here because that module is not bundled into connector
# container images. Keep the GraphQL scalar map in sync if the canonical
# vocabulary is extended.
# ---------------------------------------------------------------------------

_GRAPHQL_TO_CANONICAL = {
    "String": "string", "ID": "string",
    "Int": "integer",
    "Float": "number",
    "Boolean": "boolean",
    "DateTime": "timestamp", "Datetime": "timestamp",
    "Date": "date",
    "Time": "time",
    "JSON": "json",
}


def _canonicalize_graphql_type(t: Any) -> str:
    """Coerce a GraphQL scalar / type name to a canonical type.

    Non-scalar GraphQL types (custom scalars like Money, object types,
    Connection types, ...) collapse to ``json`` — sinks land them in
    JSONB / JSON columns where they're queryable and preserve the full
    nested structure. None / unknown -> ``string`` so a typo or new
    scalar never blocks the pipeline.
    """
    if not isinstance(t, str):
        return "string"
    raw = t.strip()
    if not raw:
        return "string"
    mapped = _GRAPHQL_TO_CANONICAL.get(raw)
    if mapped:
        return mapped
    return "json"


# ---------------------------------------------------------------------------
# GraphQL helpers
# ---------------------------------------------------------------------------


class GraphQLError(Exception):
    """Raised when a GraphQL response carries `errors[]` or transport fails."""

    def __init__(self, message: str, errors: Optional[List[Dict[str, Any]]] = None,
                 status_code: Optional[int] = None):
        super().__init__(message)
        self.errors = errors or []
        self.status_code = status_code


# ---------------------------------------------------------------------------
# Operation registry — generated from spec.operations
# ---------------------------------------------------------------------------

# Each entry: operation_name (snake_case) → {
#   "graphql_name":    str (original camelCase),
#   "operation_type":  "query"|"mutation"|"subscription",
#   "query":           str (full GraphQL document),
#   "return_type":     str | None,
# }
GRAPHQL_OPERATIONS: Dict[str, Dict[str, Any]] = {
    "widgets": {
        "graphql_name": "widgets",
        "operation_type": "query",
        "exportable_default": True,
        "query": "query Widgets($first: Int, $after: String) {\n  widgets(first: $first, after: $after) {\n    edges {\n      node { id }\n      cursor\n    }\n    pageInfo {\n      hasNextPage\n      endCursor\n    }\n  }\n}",
        "return_type": "WidgetConnection",
        "selected_fields": ["id"],
        "description": "List widgets (Relay connection).",
    },
}


# ---------------------------------------------------------------------------
# Incremental sync support (generic GraphQL contract)
# ---------------------------------------------------------------------------
#
# The executor persists the watermark a connector returns under
# ``stats.watermark = {"field": "last_modified", "value": <max updatedAt>}``
# into ``pipeline_checkpoints.position`` and replays it on the next run as
# ``since`` (also aliased to ``updated_since`` / ``modified_since`` /
# ``modified_after``). See shared/mcp-connectors/INCREMENTAL.md.
#
# This generic template implements the contract conservatively so EVERY
# generated GraphQL connector advances a checkpoint without per-API tuning:
#
#   * Filtering is OPT-IN by query shape — we inject the ``since`` value as a
#     GraphQL variable ONLY when the operation's query template actually
#     declares one of the recognized "updated after" variable names. If it
#     declares none, we fall back to a full fetch (still correct; just no
#     API-call savings until the spec exposes such a variable).
#   * Watermark emission is automatic — we scan returned rows for a
#     recognized "updated at" field and emit the max. Harmless no-op when no
#     such field is present.

# ISO-8601 keys the executor may use to replay the watermark as a filter.
_SINCE_PARAM_KEYS = ("since", "updated_since", "modified_since", "modified_after")

# GraphQL variable names commonly used to express "updated after <ts>". We
# only inject a since-filter when the operation's query template declares one
# of these (detected by ``$<name>`` in the query string).
_SINCE_VARIABLE_NAMES = (
    "since",
    "updatedSince",
    "updated_since",
    "updatedAfter",
    "updated_after",
    "modifiedSince",
    "modifiedAfter",
)

# Row fields scanned for the max-updated watermark, in priority order.
_WATERMARK_ROW_FIELDS = ("updatedAt", "updated_at", "modifiedAt", "modified_at")


def _normalize_iso_timestamp(raw: Any) -> Optional[str]:
    """Best-effort parse of an arbitrary ISO-8601 string into ``YYYY-MM-DDTHH:MM:SSZ``.

    The executor sends ``since`` as whatever value the prior run wrote into
    ``pipeline_checkpoints.position.watermark.value``. Returns ``None`` for
    empty / non-string / unparseable input so callers fall back to a full
    fetch instead of crashing on a malformed checkpoint.
    """
    if not isinstance(raw, str):
        return None
    s = raw.strip()
    if not s:
        return None
    candidate = s.replace("Z", "+00:00") if s.endswith("Z") else s
    try:
        dt = datetime.fromisoformat(candidate)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def _read_since(params: Any) -> Optional[str]:
    """Extract and normalize the replayed watermark from params, if any."""
    if not isinstance(params, dict):
        return None
    for key in _SINCE_PARAM_KEYS:
        v = params.get(key)
        if v:
            normalized = _normalize_iso_timestamp(v)
            if normalized:
                return normalized
            logger.warning(
                "[Incremental] malformed '%s' value, falling back to full fetch", key
            )
            return None
    return None


def _apply_since_filter(
    query_template: str,
    variables: Dict[str, Any],
    since_iso: str,
) -> Optional[str]:
    """Inject ``since_iso`` as a GraphQL variable when the query declares one.

    Returns the variable name used, or ``None`` when the query template
    declares no recognized "updated after" variable (== full fetch).
    """
    for name in _SINCE_VARIABLE_NAMES:
        if "$" + name in (query_template or ""):
            # Respect a caller-supplied value if already present.
            variables.setdefault(name, since_iso)
            return name
    return None


def _max_updated_at(
    rows: List[Dict[str, Any]],
    current: Optional[Tuple[str, datetime]],
) -> Optional[Tuple[str, datetime]]:
    """Scan ``rows`` for a recognized updated-at field and return the running max.

    Tracks both the textual value we'll persist AND the parsed datetime used
    for comparison, so the comparison stays timezone-correct even if the API's
    offset format varies between rows. ``None`` == no usable timestamp seen.
    """
    best = current
    for row in rows or []:
        if not isinstance(row, dict):
            continue
        raw = None
        for field in _WATERMARK_ROW_FIELDS:
            candidate = row.get(field)
            if isinstance(candidate, str) and candidate:
                raw = candidate
                break
        if raw is None:
            continue
        try:
            dt = datetime.fromisoformat(raw.replace("Z", "+00:00"))
        except ValueError:
            continue
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        if best is None or dt > best[1]:
            best = (raw, dt)
    return best


# ---------------------------------------------------------------------------
# Connector
# ---------------------------------------------------------------------------


class WidgetsGraphqlConnector(BaseMCPConnector):
    """Widgets-Graphql GraphQL connector."""

    DEFAULT_ENDPOINT = "https://api.widgets.test/graphql"

    def __init__(self) -> None:
        super().__init__()
        self.connector_type = "widgets-graphql"
        self.display_name = "Widgets-Graphql"
        # Must match metadata.json "category" — see shopify-admin-graphql.
        self.connector_category = "api_saas"

    @staticmethod
    def _get_config(params: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Unwrap config from MCP tool-call wrapper.

        _handle_tool_call passes the full arguments dict, which wraps the
        actual connection config under a ``"config"`` key. Accept both shapes:
          - {"config": {"shop": ..., "access_token": ...}}  ← tools/call path
          - {"shop": ..., "access_token": ...}              ← direct stdio path
        """
        if not params:
            return {}
        if "config" in params and isinstance(params["config"], dict):
            return dict(params["config"])
        return dict(params)

    # ----- HTTP transport ---------------------------------------------------

    def _resolve_endpoint(self, config: Dict[str, Any]) -> str:
        """Resolve the GraphQL endpoint URL.

        The spec's base_url may carry runtime placeholders (e.g. `{shop}`).
        We substitute them from `config` at call time so connection-time
        values like `shop_domain` flow through correctly.
        """
        endpoint = config.get("endpoint") or self.DEFAULT_ENDPOINT
        # Merge optional-placeholder defaults so a single missing key doesn't
        # suppress all substitutions (e.g. {version} defaults to 2024-10).
        defaults = {
        }
        sub = {**defaults, **config}
        try:
            return endpoint.format(**sub)
        except (KeyError, IndexError):
            return endpoint

    # ----- Auth dispatcher (Phase 12: multi-auth) ---------------------------
    # Each supported method's wire config is baked in at generation time.
    # The user picks `config["auth_method"]` at connection time and the
    # dispatcher formats the request accordingly. Falls back to the spec's
    # default `auth.type` when the user doesn't specify.

    SUPPORTED_AUTH_METHODS: List[Dict[str, Any]] = [
        {
            "method": "bearer",
            "header_name": "Authorization",
            "header_prefix": "Bearer",            "config_keys": ["access_token", "token"],
            "description": "",
        },
    ]

    DEFAULT_AUTH_METHOD = "bearer"

    def _resolve_auth_method(self, config: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """Pick the auth method to use for a request.

        Priority:
          1. `config['auth_method']` if it matches a supported method
          2. The connector's DEFAULT_AUTH_METHOD
          3. The first supported method declared
        """
        requested = (config.get("auth_method") or "").strip().lower()
        for m in self.SUPPORTED_AUTH_METHODS:
            if m["method"] == requested:
                return m
        for m in self.SUPPORTED_AUTH_METHODS:
            if m["method"] == self.DEFAULT_AUTH_METHOD:
                return m
        return self.SUPPORTED_AUTH_METHODS[0] if self.SUPPORTED_AUTH_METHODS else None

    def _build_auth_headers(self, config: Dict[str, Any]) -> Dict[str, str]:
        """Format auth headers based on the user's chosen method.

        For basic auth, returns empty headers (the connector uses
        `requests.auth=(user, pass)` instead).
        """
        method = self._resolve_auth_method(config)
        if method is None:
            return {}

        wire = method["method"]
        if wire == "none":
            return {}
        if wire == "basic":
            return {}  # handled via auth=(user, pass) in _execute_graphql
        if wire == "api_key_query":
            return {}  # credential rides the URL query string, injected in _execute_graphql

        # Bearer / api_key / custom_header / oauth2 — all just put a token in
        # a header. Differences are header_name + header_prefix.
        token = self._resolve_credential(config, *method["config_keys"])
        if not token:
            return {}

        header_name = method["header_name"] or "Authorization"
        prefix = method["header_prefix"] or ""
        if prefix and not prefix.endswith(" "):
            prefix = prefix + " "
        return {header_name: f"{prefix}{token}".strip()}

    @staticmethod
    def _resolve_credential(config: Dict[str, Any], *keys: str) -> Optional[str]:
        """Look up a credential value from config or environment.

        Tries each key in `keys` against `config`, then falls back to the
        env var derived from the key name (e.g. `access_token` → `ACCESS_TOKEN`).
        """
        for k in keys:
            v = config.get(k)
            if v:
                return str(v)
        for k in keys:
            v = os.environ.get(k.upper())
            if v:
                return v
        return None

    # ----- GraphQL execution ----------------------------------------------

    def _execute_graphql(
        self,
        query: str,
        variables: Optional[Dict[str, Any]],
        config: Dict[str, Any],
        *,
        timeout: int = 30,
    ) -> Dict[str, Any]:
        """POST a GraphQL document and return the `data` payload.

        - Sends Content-Type: application/json (required by GraphQL spec).
        - Surfaces any `errors[]` envelope as a GraphQLError.
        - Raises on non-200 responses.
        """
        endpoint = self._resolve_endpoint(config)
        headers = {"Content-Type": "application/json", "Accept": "application/json"}
        headers.update(self._build_auth_headers(config))

        body = {"query": query}
        if variables is not None:
            body["variables"] = variables

        # Basic auth uses requests.auth=(user, pass) instead of headers.
        # The dispatcher returns empty headers in that case; we recompute here.
        method = self._resolve_auth_method(config)
        auth = None
        if method and method["method"] == "basic":
            auth = (
                self._resolve_credential(config, "username") or "",
                self._resolve_credential(config, "password") or "",
            )

        # api_key_query: the credential rides the URL query string (?param=token),
        # not a header. Injected into request params here so test_connection and
        # every data call carry it identically.
        params: Dict[str, str] = {}
        if method and method.get("method") == "api_key_query":
            _qp = method.get("query_param")
            _tok = self._resolve_credential(config, *method.get("config_keys", []))
            if _qp and _tok:
                params[_qp] = _tok

        # SSRF guard (T1-4): refuse to send the connector's auth
        # header to a user-supplied endpoint that resolves to a
        # private network, loopback, link-local (cloud IMDS), or
        # internal-service hostname. Shared with the REST template
        # via base_connector._ssrf_check_url. Opt-out for dev:
        # MCP_ALLOW_PRIVATE_NETWORKS=true.
        try:
            from base_connector import _ssrf_check_url
            _ssrf_reason = _ssrf_check_url(endpoint)
        except Exception:
            _ssrf_reason = None
        if _ssrf_reason is not None:
            raise GraphQLError(f"SSRF guard blocked outbound GraphQL call: {_ssrf_reason}")

        _post_kwargs: Dict[str, Any] = {"headers": headers, "json": body, "timeout": timeout, "auth": auth}
        if params:
            _post_kwargs["params"] = params
        try:
            resp = requests.post(endpoint, **_post_kwargs)
        except requests.RequestException as e:
            raise GraphQLError(f"transport error: {e}") from e

        if resp.status_code != 200:
            raise GraphQLError(
                f"HTTP {resp.status_code}: {resp.text[:200]}",
                status_code=resp.status_code,
            )

        try:
            payload = resp.json()
        except ValueError as e:
            raise GraphQLError(f"invalid json response: {e}") from e

        # GraphQL `errors[]` envelope — non-empty means failure even on 200 OK
        if isinstance(payload, dict) and payload.get("errors"):
            errs = payload.get("errors") or []
            msg = "; ".join(str(e.get("message") or "") for e in errs[:3] if isinstance(e, dict))
            raise GraphQLError(f"graphql errors: {msg}", errors=errs)

        return (payload or {}).get("data") or {}

    # ----- Generic dispatcher (lazy-mode core) ------------------------------

    def execute_operation(
        self,
        operation_name: str,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Execute a registered operation by name. Lazy-mode dispatch.

        This is also called by all the per-operation methods below.

        Connection-time query override (audit #13):
        Generated queries are capped at MAX_FIELDS_PER_TYPE=25 to keep
        payloads bounded for wide types (e.g. Shopify `Product` has 50+
        scalar fields). If you need a wider or narrower selection set,
        pass an override at connection time:

            config["query_overrides"] = {
                "<operation_name>": "query MyQuery($id: ID!) { ... }",
                ...
            }

        Overrides are full GraphQL document strings — they replace the
        built-in template entirely. Variables flow through unchanged so
        the same `$id`, `$first`, `$after` parameter names work.

        Tolerates schema-qualified operation names. ``discover_schema``
        emits tables with a ``schema`` field set to the connector's
        vendor prefix; the UI joins schema+name for display
        (e.g. "shopify.products") and the HITL table-picker persists that
        joined string verbatim into ``pipelines.config.selected_tables``.
        Downstream when the executor calls this method with the persisted
        name, the leading "<schema>." is just a namespace — the actual
        operation key is the suffix. Strip the leading prefix so a HITL
        round-trip doesn't break SaaS pipelines.
        """
        cfg = self._get_config(config)
        op_key = (operation_name or "").strip()
        op = GRAPHQL_OPERATIONS.get(op_key)
        if op is None and "." in op_key:
            # Try the suffix after the LAST dot — covers both "schema.products"
            # and any future per-namespace shape like "schema.admin.products".
            suffix = op_key.rsplit(".", 1)[-1]
            op = GRAPHQL_OPERATIONS.get(suffix)
            if op is not None:
                operation_name = suffix
        if op is None:
            raise GraphQLError(f"unknown operation '{operation_name}'")

        query = op["query"]
        overrides = cfg.get("query_overrides") or {}
        if isinstance(overrides, dict) and operation_name in overrides:
            override_query = overrides[operation_name]
            if isinstance(override_query, str) and override_query.strip():
                self.log(f"using user-supplied query_overrides for {operation_name}")
                query = override_query

        return self._execute_graphql(query, variables or {}, cfg)

    # ----- Required core operations ----------------------------------------

    def test_connection(self, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Verify connectivity by issuing a minimal `__typename` query."""
        cfg = self._get_config(config)
        try:
            data = self._execute_graphql(
                query="{ __typename }",
                variables=None,
                config=cfg,
            )
            return {"success": True, "details": {"typename": data.get("__typename")}}
        except GraphQLError as e:
            return {"success": False, "error": str(e)}

    def validate_config(self, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Confirm required config fields are present."""
        cfg = self._get_config(config)
        required: List[str] = [
        ]
        missing = [
            name for name in required
            if not (cfg.get(name) or os.environ.get(name.upper()))
        ]
        if missing:
            return {"valid": False, "missing": missing}
        return {"valid": True}

    def discover_schema(self, config: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Discover the source schema via real GraphQL introspection.

        Implements the canonical discovery contract every source connector
        must satisfy:

            {
              "success": bool,
              "tables": [
                {
                  "name":        str,
                  "schema":      str | None,
                  "columns":     [{"name": str, "type": str}],
                  "row_count":   int,           # -1 sentinel == unknown
                  "description": str | None,
                  "type":        "query|table|collection",
                },
                ...
              ],
              "operations": [...],
              "error":      str | None,
            }

        Generated GraphQL connectors previously returned a hardcoded
        table list with empty columns and no row counts. That hid auth
        errors and gave the table-selection UI nothing useful to show.
        This template implementation:

          1. Verifies auth via ``test_connection`` and fails closed on
             auth errors instead of returning a hardcoded list.
          2. Runs a ``__type`` introspection query for every known
             operation to enumerate the leaf fields of the response
             type (after unwrapping Relay ``*Connection`` wrappers).
          3. Best-effort row counts using ``<resource>Count`` queries —
             leaves ``row_count = -1`` when the API doesn't expose a
             count so the UI knows the value is unknown, not zero.
        """
        cfg = self._get_config(config)

        try:
            auth_check = self.test_connection(cfg)
        except Exception as e:  # pragma: no cover - defensive
            return {
                "success": False,
                "error": f"connection test raised: {e}",
                "tables": [],
                "operations": [],
            }
        if not auth_check.get("success"):
            return {
                "success": False,
                "error": "auth check failed: " + str(auth_check.get("error", "unknown")),
                "tables": [],
                "operations": [],
            }

        tables: List[Dict[str, Any]] = []
        for name, op in GRAPHQL_OPERATIONS.items():
            # Arg-required singular lookups (exportable_default=False, e.g.
            # country(code: ID!)) are not parameterless list resources — keep
            # them callable via export() with explicit variables, but don't
            # surface them as default exportable tables (a parameterless run
            # would fail with a missing-required-argument error).
            if not op.get("exportable_default", True):
                continue
            return_type = op.get("return_type") or ""
            raw_fields = self._introspect_raw_fields(self._unwrap_connection_type(return_type), cfg)
            # F6: advertise EXACTLY the columns export() returns. export() runs the
            # query_template, which selects a SUBSET of the node's fields; the full
            # introspected type is wider, so advertising it builds the destination
            # with columns export() never fills. Intersect introspection (for real
            # types + ID/PK detection) with the generation-time selected_fields —
            # any selected field introspection can't resolve is still advertised
            # (as String) so a returned column is NEVER dropped. No selected_fields
            # (older spec / unparseable query) → keep the full introspected list.
            selected = op.get("selected_fields") or []
            if selected:
                _typed = {fname: raw_type for fname, raw_type in raw_fields}
                raw_fields = [(f, _typed.get(f, "String")) for f in selected]
            row_count = self._best_effort_count(op.get("graphql_name") or name, cfg)
            # Canonical types so sinks can translate to their dialect.
            columns = [
                {"name": fname, "type": _canonicalize_graphql_type(raw_type)}
                for fname, raw_type in raw_fields
            ]
            # Generic GraphQL PK detection: any field whose type is `ID`
            # is a primary-key candidate. Works for all Relay-compliant
            # APIs (Shopify, GitHub, Linear, ...). Sources without ID
            # fields fall through to the sink's synthetic-hash PK.
            pk_fields = [fname for fname, raw_type in raw_fields if raw_type == "ID"]
            tables.append({
                "name": name,
                "columns": columns,
                "row_count": row_count,
                "description": op.get("description", ""),
                "type": op.get("operation_type", "query"),
                "primary_keys": pk_fields,
                "primary_key_source": "declared" if pk_fields else "synthetic",
            })

        ops = [
            {"name": name, **{k: v for k, v in op.items() if k != "query"}}
            for name, op in GRAPHQL_OPERATIONS.items()
        ]
        return {
            "success": True,
            "tables": tables,
            "operations": ops,
        }

    # ----- Introspection helpers -------------------------------------------

    @staticmethod
    def _unwrap_connection_type(type_name: str) -> str:
        """Strip Relay Connection wrappers so we introspect the node type."""
        if not type_name:
            return ""
        if type_name.endswith("Connection"):
            return type_name[:-len("Connection")]
        return type_name

    def _introspect_raw_fields(self, target_type: str, config: Dict[str, Any]) -> List[tuple]:
        """Return ``[(field_name, raw_gql_type_name)]`` for a GraphQL type.

        Returns the *raw* GraphQL type name (``ID``, ``String``,
        ``MoneyBag``, ...) so callers can both (a) canonicalize for the
        generic pipeline and (b) detect ``ID`` fields for primary-key
        declaration. Returns ``[]`` when introspection is unavailable.
        """
        if not target_type:
            return []
        introspect = (
            "query IntrospectType($name: String!) {"
            "  __type(name: $name) {"
            "    name kind"
            "    fields { name type { name kind ofType { name kind ofType { name kind } } } }"
            "  }"
            "}"
        )
        try:
            data = self._execute_graphql(introspect, {"name": target_type}, config)
        except Exception:
            return []
        type_info = data.get("__type") if isinstance(data, dict) else None
        if not isinstance(type_info, dict):
            return []
        out: List[tuple] = []
        for f in type_info.get("fields") or []:
            if not isinstance(f, dict):
                continue
            out.append((f.get("name", ""), self._flatten_graphql_type(f.get("type"))))
        return out

    def _introspect_columns(self, target_type: str, config: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Canonical-typed column list. Kept for callers that don't need PK info."""
        return [
            {"name": fname, "type": _canonicalize_graphql_type(raw_type)}
            for fname, raw_type in self._introspect_raw_fields(target_type, config)
        ]

    def _flatten_graphql_type(self, type_node: Optional[Dict[str, Any]]) -> str:
        """Walk a GraphQL type-ref chain (NonNull / List wrappers) to the leaf name."""
        if not isinstance(type_node, dict):
            return "Unknown"
        name = type_node.get("name")
        if name:
            return name
        of_type = type_node.get("ofType")
        if of_type is not None:
            return self._flatten_graphql_type(of_type)
        return type_node.get("kind") or "Unknown"

    def _best_effort_count(self, graphql_resource: str, config: Dict[str, Any]) -> int:
        """Best-effort row count via ``<X>Count`` introspection.

        Many GraphQL APIs (notably Shopify) expose zero-cost count
        queries for top-level resources. We probe ``<resource>Count``
        and fall back to ``-1`` if the field isn't exposed — ``-1`` is
        the canonical "unknown" sentinel; the UI renders nothing rather
        than a misleading zero.
        """
        if not graphql_resource:
            return -1
        query = "query Count { %sCount { count } }" % graphql_resource
        try:
            data = self._execute_graphql(query, None, config)
        except Exception:
            return -1
        if not isinstance(data, dict):
            return -1
        block = data.get("%sCount" % graphql_resource)
        if isinstance(block, dict):
            v = block.get("count")
            if isinstance(v, int):
                return v
        if isinstance(block, int):
            return block
        return -1

    def get_capabilities(self, params: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Operation listing for MCP auto-dispatch.

        The base-class dispatcher always invokes capability methods with
        a single ``params`` positional (may be ``None`` / empty dict).
        Accepting it here avoids ``takes 1 positional argument but 2 were
        given`` on the runtime path. ``params`` is unused for capability
        reporting but is part of the contract.
        """
        return {
            "connector_type": "widgets-graphql",
            "protocol": "graphql",
            "supports_source": True,
            "supports_destination": False,
            "operations": [
                {
                    "name": "test_connection",
                    "type": "core",
                    "method": "widgets-graphql_test_connection",
                    "description": "Test connectivity",
                },
                {
                    "name": "validate_config",
                    "type": "core",
                    "method": "widgets-graphql_validate_config",
                    "description": "Validate configuration",
                },
                {
                    "name": "discover_schema",
                    "type": "core",
                    "method": "widgets-graphql_discover_schema",
                    "description": "Discover the upstream schema",
                },
                {
                    "name": "get_capabilities",
                    "type": "core",
                    "method": "widgets-graphql_get_capabilities",
                    "description": "Return connector capabilities",
                },
                {
                    "name": "export",
                    "type": "source",
                    "method": "widgets-graphql_export",
                    "description": "Generic GraphQL query dispatcher",
                },
                {
                    "name": "widgets",
                    "type": "source",
                    "method": "widgets-graphql_widgets",
                    "description": "List widgets (Relay connection).",
                },
            ],
        }

    # ----- Generic export / import (alias to dispatcher) -------------------

    def export(
        self,
        params: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Source-side export — base-class calling convention: export(params: Dict).

        _handle_tool_call always calls handler(normalized_args) where
        normalized_args is a dict.  The dict may contain:
            table / operation_name / operation — the GraphQL operation to run
            config  — connection config
            variables / filters — optional query variables
        """
        if isinstance(params, str):
            # Legacy positional call: export("products")
            operation_name = params
            cfg: Dict[str, Any] = {}
            variables: Dict[str, Any] = {}
        else:
            cfg = self._get_config(params)
            operation_name = (
                (params or {}).get("table")
                or (params or {}).get("endpoint")  # normalisation target for api_saas
                or (params or {}).get("operation_name")
                or (params or {}).get("operation")
            )
            variables = (params or {}).get("variables") or (params or {}).get("filters") or {}

        # Canonicalise schema-qualified table names BEFORE we route on
        # the operation. The HITL table picker persists names verbatim
        # from discover_schema, which joins schema+name for display
        # (e.g. "shopify.products"). The actual operation key is the
        # suffix. Strip here so downstream checks (e.g. the Relay-pagination
        # detection below, dispatcher lookup) all see the canonical key.
        if isinstance(operation_name, str) and "." in operation_name:
            operation_name = operation_name.rsplit(".", 1)[-1]

        # Default Relay pagination if the operation's query template uses
        # $first / $last (every GraphQL Relay connection field requires one).
        # The orchestrator's executor often calls export() without variables;
        # without a default the API rejects with "first or last must be provided".
        # Cap at 100: it is GitHub GraphQL's HARD per-connection maximum (first>100 ->
        # "first must be within 1..100") and the de-facto Relay default; Shopify (which
        # permits up to 250) still returns every row — export() loops all pages, so a
        # smaller page just means more requests, never truncation. A single 250 default
        # broke GitHub outright, so 100 is the safe generalizable cap.
        op_cfg = GRAPHQL_OPERATIONS.get(operation_name) if operation_name else None
        query_template = (op_cfg or {}).get("query", "") if isinstance(op_cfg, dict) else ""
        needs_relay = "$first" in query_template or "$last" in query_template
        if operation_name:
            if needs_relay and not isinstance(variables, dict):
                variables = {}
            if needs_relay and "first" not in variables and "last" not in variables:
                requested = int((params or {}).get("limit") or 100)
                variables["first"] = max(1, min(requested, 100))

        if not operation_name:
            return {"success": False, "error": "Missing table/operation_name parameter"}

        # -----------------------------------------------------------------
        # Incremental sync — replay the prior watermark as a since-filter when
        # the operation's query declares a recognized "updated after" variable,
        # and track max(updatedAt) so we can return the new watermark. When the
        # query declares no such variable we full-fetch (still correct). See
        # the module-level helpers + shared/mcp-connectors/INCREMENTAL.md.
        # -----------------------------------------------------------------
        normalized_since = _read_since(params)
        incremental_applied = False
        if normalized_since:
            variables = dict(variables or {})
            used_var = _apply_since_filter(query_template, variables, normalized_since)
            if used_var:
                incremental_applied = True
                logger.info(
                    "[Incremental] %s: applying since-filter via $%s",
                    operation_name, used_var,
                )

        # -----------------------------------------------------------------
        # Regular paginated path. Loops EVERY page of the Relay connection
        # inside this single export() call (connections are typically capped at
        # ~250 rows/page), accumulating all rows so tables above one page return
        # in full instead of being silently truncated to the first page. The
        # watermark contract below then scans the full set for max(updatedAt).
        #
        # Singleton / non-connection operations (no $first/$last) take the
        # single-call path unchanged.
        # -----------------------------------------------------------------
        page_size = variables.get("first") if isinstance(variables, dict) else None
        next_cursor: Optional[str] = None
        has_more = False
        if needs_relay and page_size:
            start_after = (params or {}).get("cursor") if isinstance(params, dict) else None
            max_records = int((params or {}).get("limit") or 10000) if isinstance(params, dict) else 10000

            def _execute_page(page_vars: Dict[str, Any]) -> Any:
                return self.execute_operation(
                    operation_name, variables=page_vars or None, config=cfg or None
                )

            try:
                rows, next_cursor, has_more = GraphQLPaginationHandler().fetch_all_pages(
                    _execute_page,
                    variables,
                    page_size=int(page_size),
                    max_records=max_records,
                    start_after=start_after,
                    row_extractor=_normalize_to_rows,
                )
            except Exception as exc:
                return {"success": False, "error": str(exc)}
        else:
            try:
                data = self.execute_operation(operation_name, variables=variables or None, config=cfg or None)
            except Exception as exc:
                return {"success": False, "error": str(exc)}
            rows = _normalize_to_rows(data)

        cols = list(rows[0].keys()) if rows else []
        response: Dict[str, Any] = {
            "success": True,
            "data": rows,
            "columns": cols,
            "row_count": len(rows),
            "has_more": has_more,
        }
        if has_more and next_cursor:
            response["next_cursor"] = next_cursor
            response["paging_mode"] = "cursor"

        # Emit the watermark from the max updated-at seen. If we filtered on a
        # prior `since` and got 0 rows, echo it so the checkpoint stays
        # advanced rather than being cleared.
        running = _max_updated_at(rows, None)
        watermark_value: Optional[str] = None
        if running is not None:
            watermark_value = running[0]
        elif incremental_applied and normalized_since:
            watermark_value = normalized_since
        if watermark_value:
            response["stats"] = {
                "watermark": {"field": "last_modified", "value": watermark_value}
            }
            response["max_watermark"] = watermark_value

        return response

    def import_data(
        self,
        params: Optional[Dict[str, Any]] = None,
    ) -> ImportResult:
        """Destination-side dispatcher: invoke a mutation per record.

        _handle_tool_call always calls handler(normalized_args) where
        normalized_args is a dict.  The dict may contain:
            operation_name / table — the GraphQL mutation to run
            records               — list of records to import
            config                — connection config (nested under "config" key
                                    or flat in params)
        """
        if isinstance(params, str):
            # Legacy positional call — no records to process
            return ImportResult(success=True, written=0, failed=0, errors=[])

        cfg = self._get_config(params)
        operation_name = (
            (params or {}).get("operation_name")
            or (params or {}).get("table")
            or (params or {}).get("endpoint")  # normalisation target for api_saas
            or ""
        )
        records = (params or {}).get("records") or []

        if not operation_name:
            return ImportResult(
                success=False,
                written=0,
                failed=1,
                errors=[ErrorItem(
                    code="MISSING_PARAM",
                    message="Missing operation_name/table parameter",
                )],
            )

        written = 0
        errors: List[ErrorItem] = []
        for idx, record in enumerate(records or []):
            try:
                self.execute_operation(operation_name, variables=record, config=cfg)
                written += 1
            except GraphQLError as e:
                errors.append(ErrorItem(
                    code="GRAPHQL_ERROR",
                    message=str(e),
                ))
        return ImportResult(
            success=len(errors) == 0,
            written=written,
            failed=len(errors),
            errors=errors,
        )

    # ----- Eager-mode per-operation methods -------------------------------
    # Generated when total ops ≤ LAZY_OPS_THRESHOLD. Above the threshold we
    # only emit the dispatcher above (callers use execute_operation()).

    def widgets(
        self,
        variables: Optional[Dict[str, Any]] = None,
        config: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """List widgets (Relay connection).

        GraphQL: `query widgets`
        Returns: WidgetConnection
        """
        return self.execute_operation("widgets", variables=variables, config=config)



def _flatten_value(v: Any) -> Any:
    """Serialize nested dicts/lists as JSON strings so Postgres can store them."""
    if isinstance(v, (dict, list)):
        return json.dumps(v, ensure_ascii=False, default=str)
    return v


def _flatten_row(row: Dict[str, Any]) -> Dict[str, Any]:
    """Convert all values in a record to Postgres-compatible scalars.

    psycopg2 raises ``can't adapt type 'dict'`` when a column value is a
    Python dict (e.g. nested GraphQL objects like ``plan: {displayName: ...}``).
    We JSON-serialize those values so they land as TEXT/JSONB.
    """
    return {k: _flatten_value(v) for k, v in row.items()}


def _extract_connection_rows(obj: Any, depth: int = 0) -> Optional[List[Dict[str, Any]]]:
    """Depth-first search for Relay connection rows inside a GraphQL object.

    Handles two standard Relay pagination patterns:
      - ``edges[].node``  — full Relay spec (Shopify, GitHub GraphQL v4, Linear, …)
      - ``nodes[]``       — shorthand available on many Relay-compliant APIs

    Recurses into dict-valued children ONLY (not into list-valued sub-fields
    such as ``tags``, ``features``, etc.) so incidental array attributes on a
    single-object response don't get mistaken for the primary result set.

    Returns ``None`` when no connection pattern is found, so callers can
    distinguish "nothing found" from "found an empty list".
    """
    if not isinstance(obj, dict) or depth > 4:
        return None
    # Relay edges pattern: {edges: [{node: {...}}, ...]}
    edges = obj.get("edges")
    if isinstance(edges, list):
        rows = [
            e["node"] for e in edges
            if isinstance(e, dict) and isinstance(e.get("node"), dict)
        ]
        return rows  # may be empty list — that's a valid "found but empty" signal
    # Relay nodes shortcut: {nodes: [{...}, ...]}  (GitHub, some Linear APIs)
    nodes = obj.get("nodes")
    if isinstance(nodes, list):
        rows = [n for n in nodes if isinstance(n, dict)]
        return rows
    # Recurse into dict-valued children to handle wrapped connections like
    # {"viewer": {"repositories": {"edges": [...]}}}  (GitHub viewer pattern)
    for v in obj.values():
        if isinstance(v, dict):
            result = _extract_connection_rows(v, depth + 1)
            if result is not None:
                return result
    return None


def _normalize_to_rows(data: Any) -> List[Dict[str, Any]]:
    """Best-effort flattening of a GraphQL response into a row list.

    Handles all common GraphQL response shapes at any nesting depth:
      1. Relay connection (edges/node) — direct or wrapped in a parent object:
           ``{"products": {"edges": [{"node": {...}}]}}``
           ``{"viewer": {"repositories": {"edges": [{"node": {...}}]}}}``
      2. Relay nodes shortcut:
           ``{"issues": {"nodes": [{...}, ...]}}``
      3. Top-level plain list (non-Relay):
           ``{"orders": [{...}, {...}]}``
      4. Single object:
           ``{"shop": {...}}``
    Falls back to wrapping ``data`` itself in a single-element list.

    All nested dicts/lists are JSON-serialised via ``_flatten_row`` so the
    downstream PostgreSQL connector (psycopg2) can store them without raising
    ``can't adapt type 'dict'``.
    """
    if isinstance(data, dict):
        if len(data) == 1:
            (only_value,) = data.values()
            if isinstance(only_value, dict):
                # Try Relay connection (edges/nodes) recursively — handles
                # both top-level and wrapped (e.g. viewer → repositories)
                rows = _extract_connection_rows(only_value)
                if rows is not None:
                    return [_flatten_row(r) for r in rows]
                # Fall back: plain list field (non-Relay) or single object
                for v in only_value.values():
                    if isinstance(v, list):
                        list_rows = [r for r in v if isinstance(r, dict)]
                        if list_rows:
                            return [_flatten_row(r) for r in list_rows]
                return [_flatten_row(only_value)]
            if isinstance(only_value, list):
                return [_flatten_row(r) for r in only_value if isinstance(r, dict)]
        # Multi-key dict: try connection extraction before treating as a single row
        rows = _extract_connection_rows(data)
        if rows is not None:
            return [_flatten_row(r) for r in rows]
        return [_flatten_row(data)]
    if isinstance(data, list):
        return [_flatten_row(r) for r in data if isinstance(r, dict)]
    return []


if __name__ == "__main__":
    connector = WidgetsGraphqlConnector()

    http_mode = os.getenv("MCP_HTTP_MODE", "false").lower() == "true"
    port = int(os.getenv("MCP_PORT", os.getenv("PORT", "8000")))

    if http_mode or os.getenv("DOCKER_CONTAINER"):
        try:
            import uvicorn
            from fastapi import FastAPI
            # Decimal crosses this boundary as a STRING, never a float. FastAPI's
            # jsonable_encoder maps Decimal -> float (ENCODERS_BY_TYPE), which silently
            # destroys precision on the way to the sink: a numeric 123456789012345678.5
            # arrives as 1.2345678901234568e+17, and the orchestrator writes that back
            # out as 123456789012345680 -- a changed value, with no error raised anywhere.
            # The stdio path already serialises with json.dumps(..., default=str), so
            # HTTP mode was the only lossy leg -- and it is the leg every containerised
            # deployment uses, which is why no stdio-based test could ever see it.
            from decimal import Decimal as _Decimal
            from fastapi.encoders import ENCODERS_BY_TYPE as _ENCODERS_BY_TYPE
            _ENCODERS_BY_TYPE[_Decimal] = str

            app = FastAPI()

            @app.post("/test_connection")
            def api_test_connection(params: dict = {}):
                return connector.test_connection(params)

            @app.post("/validate_config")
            def api_validate_config(params: dict = {}):
                return connector.validate_config(params)

            @app.post("/discover_schema")
            def api_discover_schema(params: dict = {}):
                return connector.discover_schema(params)

            @app.post("/execute_operation")
            def api_execute_operation(params: dict = {}):
                return connector.execute_operation(
                    params.pop("operation_name", ""),
                    variables=params.pop("variables", None),
                    config=params,
                )

            @app.post("/export")
            def api_export(params: dict = {}):
                result = connector.export(params)
                return result.__dict__ if hasattr(result, "__dict__") else result

            @app.post("/mcp")
            def api_mcp(request: dict):
                # MCP JSON-RPC entry-point used by the orchestrator's executor.
                # The REST endpoints above remain for direct invocation; this
                # endpoint dispatches tools/list, tools/call, and ping via
                # the inherited BaseMCPConnector.handle_request method.
                # Without this route GraphQL connectors are silently invisible
                # to the orchestrator (the executor reports
                # "connector did not return table information" when its
                # tools/call POST 404s).
                try:
                    request_dict = request if isinstance(request, dict) else {}
                    if "jsonrpc" not in request_dict:
                        request_dict = {
                            "jsonrpc": "2.0",
                            "id": request_dict.get("id", 1),
                            "method": request_dict.get("method"),
                            "params": request_dict.get("params") or {},
                        }
                    return connector.handle_request(request_dict)
                except Exception as e:
                    return {
                        "jsonrpc": "2.0",
                        "id": (request or {}).get("id", 1) if isinstance(request, dict) else 1,
                        "error": {"code": -32000, "message": str(e)},
                    }

            @app.get("/health")
            def health():
                return {"status": "ok"}

            logging.getLogger(__name__).info(
                "🚀 Starting Widgets-Graphql GraphQL connector (HTTP) on port %d", port
            )
            uvicorn.run(app, host="0.0.0.0", port=port)
        except ImportError:
            connector.run()
    else:
        connector.run()
