#!/usr/bin/env bash
#
# gen-third-party-notices.sh — regenerate THIRD_PARTY_NOTICES.md for the whole
# repo (Go modules + Python images/connectors + frontend npm).
#
# Source-available (Elastic License 2.0) redistribution obligation: we ship
# third-party OSS inside our Docker images, so we must reproduce their license
# texts and copyright notices. This script produces a single aggregated
# THIRD_PARTY_NOTICES.md at the repo root.
#
# Tooling (install once — see § "which parts run now" in the Thread B report):
#   go-licenses    : go install github.com/google/go-licenses@latest
#   pip-licenses   : pipx install pip-licenses   (run INSIDE an env where the
#                    requirements are installed — see per-env venv logic below)
#   license-checker: npx --yes license-checker-rseidelsohn   (no global install)
#
# Usage:
#   scripts/gen-third-party-notices.sh            # full regen
#   CHECK=1 scripts/gen-third-party-notices.sh    # regen to a temp file + diff
#                                                 # against committed copy (CI)
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="${OUT:-$ROOT/THIRD_PARTY_NOTICES.md}"
if [[ "${CHECK:-0}" == "1" ]]; then
  OUT="$(mktemp -t tpn.XXXXXX.md)"
fi

TMPL="$(mktemp -t golic.XXXXXX.tpl)"
cat >"$TMPL" <<'TPL'
{{ range . }}
### {{ .Name }}

- License: {{ .LicenseName }}
- URL: {{ .LicenseURL }}
{{ end }}
TPL

# Go modules that produce a shipped binary. shared/go/* are pulled in via
# `replace` from the three services, so `go-licenses ./...` on each service
# already covers them; listing them separately is belt-and-suspenders.
GO_MODULES=(
  api-gateway
  backend-orchestrator
  backend-temporal-adapter
  # connector-deployer builds and ships in docker-compose.yml AND
  # docker-compose.quickstart.yml, but was missing from this list, so its closure --
  # 14 modules including github.com/docker/docker -- was redistributed unlisted.
  connector-deployer
  shared/mcp-connectors/internal/kafka-mcp-sink/worker-src
)

# Python requirement manifests. Grouped by the image/venv they install into --
# and ONLY those, which is the property that keeps this list honest. Each is
# resolved into its own throwaway venv so pip-licenses sees exactly that image's
# dependency closure.
#
# src/agents/{planner,tool_generator}/requirements.txt used to sit here and broke
# that premise: no Dockerfile ever installed either one (llm-service/Dockerfile:31
# and Dockerfile.community:38 take requirements.txt, Dockerfile.oss:38 takes
# requirements-oss.txt), so the notices attested to a closure that ships in no
# image. Both files are deleted; every package they named is already declared in
# llm-service/requirements.txt. Adding a manifest here is a claim that an image
# installs it -- check the Dockerfile before you do.
PY_MANIFESTS=(
  llm-service/requirements.txt
  llm-service/requirements-oss.txt
)
# Every connector requirements.txt (public + internal), auto-discovered so new
# connectors are covered without editing this script.
while IFS= read -r r; do PY_MANIFESTS+=("$r"); done < <(
  find shared/mcp-connectors -path '*/versions/*/requirements.txt' | sort
)

# ---------------------------------------------------------------------------
{
  echo "# Third-Party Notices"
  echo
  echo "rsync.ai (Elastic License 2.0) redistributes the third-party open-source"
  echo "components listed below inside its container images. Their licenses and"
  echo "copyright notices are reproduced here to satisfy their redistribution terms."
  echo
  echo "> Generated by \`scripts/gen-third-party-notices.sh\`. Do not edit by hand —"
  echo "> re-run the script and commit the result."
  echo
  echo "_Last generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)_"
  echo
} >"$OUT"

# ---- Go -------------------------------------------------------------------
echo "==> Go modules"
{
  echo "## Go modules"
  echo
} >>"$OUT"
for m in "${GO_MODULES[@]}"; do
  echo "    - $m"
  {
    echo "### module: \`$m\`"
    echo
  } >>"$OUT"
  # go-licenses is preferred (emits per-module license text + URL) but it
  # ABORTS on the Go >= 1.25 toolchain ("Package X does not have module info",
  # google/go-licenses#128), producing ZERO output. Detect that (empty result)
  # and fall back to `go list -deps` enumeration + a best-effort SPDX classify
  # from the cached LICENSE file, so the Go section is never silently empty.
  gl_out="$( cd "$m" && go-licenses report ./... --template "$TMPL" 2>/dev/null || true )"
  if [[ -n "${gl_out//[[:space:]]/}" ]]; then
    printf '%s\n' "$gl_out" >>"$OUT"
  else
    echo "  !! go-licenses empty for $m (Go>=1.25, google/go-licenses#128) — using 'go list -deps' fallback" >&2
    {
      echo "_go-licenses could not analyze this toolchain; third-party modules enumerated via"
      echo "\`go list -deps\` and SPDX-classified from the cached LICENSE file (best-effort — confirm"
      echo "full license texts at release)._"
      echo
      ( cd "$m" && GOOS=linux GOFLAGS=-mod=mod go list -deps -f '{{with .Module}}{{.Path}} {{.Version}}{{end}}' ./... 2>/dev/null ) \
        | awk 'NF' | sort -u | grep -v '^github.com/rsync-ai/' | while read -r path ver; do
          mp="$(go env GOMODCACHE)/${path}@${ver}"
          lic="?"
          lf="$(find "$mp" -maxdepth 2 \( -iname 'LICENSE*' -o -iname 'COPYING*' -o -iname 'LICENCE*' \) -type f 2>/dev/null | head -1)"
          if [[ -n "$lf" ]]; then
            h="$(head -40 "$lf" 2>/dev/null)"
            case "$h" in
              *"Apache License"*"Version 2.0"*)                    lic="Apache-2.0" ;;
              *"Mozilla Public License"*[Vv]"ersion 2.0"*)        lic="MPL-2.0" ;;
              *"GNU AFFERO"*)                                      lic="AGPL" ;;
              *"GNU LESSER"*)                                      lic="LGPL" ;;
              *"GNU GENERAL PUBLIC"*)                              lic="GPL" ;;
              *"ISC License"*)                                     lic="ISC" ;;
              *"Permission is hereby granted, free of charge"*)    lic="MIT" ;;
              *"Redistribution and use in source and binary"*)    lic="BSD" ;;
              *)                                                   lic="see LICENSE file" ;;
            esac
          fi
          echo "- \`${path}\` ${ver} — ${lic}"
        done
    } >>"$OUT"
  fi
  echo >>"$OUT"
done

# ---- Python ---------------------------------------------------------------
echo "==> Python environments"
{
  echo "## Python packages"
  echo
} >>"$OUT"
for req in "${PY_MANIFESTS[@]}"; do
  [[ -f "$req" ]] || continue
  echo "    - $req"
  {
    echo "### requirements: \`$req\`"
    echo
  } >>"$OUT"
  venv="$(mktemp -d -t tpnvenv.XXXXXX)"
  python3 -m venv "$venv"
  # shellcheck disable=SC1091
  "$venv/bin/pip" install --quiet --upgrade pip pip-licenses >/dev/null 2>&1 || true
  if "$venv/bin/pip" install --quiet -r "$req" >/dev/null 2>&1; then
    "$venv/bin/pip-licenses" \
        --format=plain-vertical \
        --with-license-file --no-license-path \
        --with-urls \
      >>"$OUT" 2>/dev/null \
      || echo "  !! pip-licenses failed for $req" >&2
  else
    echo "_(could not install $req in an isolated venv — resolve deps or generate from the built image, see report)_" >>"$OUT"
    echo "  !! pip install failed for $req (some connectors need system libs: pyodbc→unixodbc, etc.)" >&2
  fi
  rm -rf "$venv"
  echo >>"$OUT"
done

# ---- Frontend (npm) -------------------------------------------------------
echo "==> Frontend npm (production deps)"
{
  echo "## Frontend (npm, production dependencies)"
  echo
  echo '```'
} >>"$OUT"
( cd frontend \
    && [[ -d node_modules ]] || npm ci --omit=dev >/dev/null 2>&1 || true
  cd frontend 2>/dev/null || cd "$ROOT/frontend"
  npx --yes license-checker-rseidelsohn \
      --production \
      --csv \
      --columns name,version,licenses,repository \
) >>"$OUT" 2>/dev/null \
  || echo "  !! license-checker failed (run 'npm ci' in frontend/ first)" >&2
{
  echo '```'
  echo
} >>"$OUT"

rm -f "$TMPL"

if [[ "${CHECK:-0}" == "1" ]]; then
  if ! diff -u "$ROOT/THIRD_PARTY_NOTICES.md" "$OUT" >/tmp/tpn.diff 2>&1; then
    echo "::error::THIRD_PARTY_NOTICES.md is stale. Run scripts/gen-third-party-notices.sh and commit." >&2
    cat /tmp/tpn.diff >&2
    rm -f "$OUT"
    exit 1
  fi
  echo "THIRD_PARTY_NOTICES.md is up to date."
  rm -f "$OUT"
fi

echo "Done -> ${OUT}"
