#!/usr/bin/env python3
"""
Generate docker-compose.mcp.yml for all user-facing connectors.

Goal: deploy everything under a dedicated Docker Desktop group "rsync-ai-mcp".

Rules:
- Include only connector directories that have metadata.json
- Skip internal connectors (metadata.json has "internal": true)
- Skip utility directories: generators/, schemas/, oauth/, db_drivers/, context7/, __pycache__/
- Use versioned container_name format: rsync-ai-<id>-vX-Y-Z-mcp
- Join the external, dedicated user-connector network rsync-ai-mcp (created by the
  base rsync-ai project). This is the isolation boundary: USER connectors sit here,
  NOT on the internal-services network rsync-ai_default (SEC-M-06). The orchestrator,
  api-gateway, tool-generator, and kafka-mcp-sink bridge into rsync-ai-mcp to reach
  them. (JIT-deployed connectors are put on the same network by docker_builder.py.)

Usage:
  python3 scripts/mcp_generate_compose.py
"""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CONNECTORS_DIR = REPO_ROOT / "shared" / "mcp-connectors"
PUBLIC_CONNECTORS_DIR = CONNECTORS_DIR / "public" if (CONNECTORS_DIR / "public").is_dir() else CONNECTORS_DIR
OUT_PATH = REPO_ROOT / "docker-compose.mcp.yml"


SKIP_DIRS = {
    "generators",
    "schemas",
    "oauth",
    "db_drivers",
    "context7",
    "__pycache__",
    "_regen_backup",
}

# Backward-compatible docker network aliases for a few widely-referenced connectors.
# These were historically used by tests/scripts that pinned stable hostnames.
NETWORK_ALIASES_BY_CONNECTOR_ID: dict[str, list[str]] = {
    "mysql": ["rsync-ai-mysql-mcp"],
    "postgresql": ["rsync-ai-postgresql-mcp"],
    "sqlserver": ["rsync-ai-sqlserver-mcp"],
    # Some legacy code/scripts used underscore names (aws_s3) and/or non-versioned hostnames.
    "aws-s3": ["rsync-ai-aws_s3-mcp", "rsync-ai-aws-s3-mcp"],
}


def _load_metadata(path: Path) -> dict:
    with open(path, "r") as f:
        return json.load(f)


def _resolve_current_dir(connector_dir: Path) -> Path:
    """Connector root -> versions/<current_version>/ (the canonical source — the
    connector root holds only latest.json now). Falls back to the connector dir
    itself for any flat-layout connector."""
    latest_path = connector_dir / "latest.json"
    if latest_path.is_file():
        try:
            cv = (json.loads(latest_path.read_text()).get("current_version") or "").strip()
        except Exception:
            cv = ""
        if cv:
            vdir = connector_dir / "versions" / cv
            if vdir.is_dir():
                return vdir
    return connector_dir


def main() -> int:
    # Dedupe by canonical connector id. The repo may contain legacy duplicate layouts
    # (e.g. public/database/<id> and public/<id>). Prefer non-legacy (non-database/) paths.
    connector_by_id: dict[str, Path] = {}
    rel_by_id: dict[str, str] = {}

    # New layout: shared/mcp-connectors/public/<category>/<id>/...
    # Backward compatible: shared/mcp-connectors/<id>/...
    # A connector root is identified by latest.json (the version pointer); its
    # metadata + Dockerfile live in the canonical version dir (versions/<cv>/).
    for latest_path in sorted(PUBLIC_CONNECTORS_DIR.rglob("latest.json")):
        if any(part == "versions" for part in latest_path.parts):
            continue
        p = latest_path.parent
        if p.name in SKIP_DIRS:
            continue
        version_dir = _resolve_current_dir(p)
        meta_path = version_dir / "metadata.json"
        dockerfile_path = version_dir / "Dockerfile"
        if not meta_path.exists() or not dockerfile_path.exists():
            continue

        md = _load_metadata(meta_path)
        if md.get("internal") is True:
            continue

        connector_id = (md.get("id") or md.get("connector_type") or p.name).strip()
        connector_id = connector_id.replace("_", "-").lower().strip()

        try:
            rel_dir = p.relative_to(PUBLIC_CONNECTORS_DIR).as_posix()
        except Exception:
            rel_dir = p.as_posix()

        def is_legacy(rel: str) -> bool:
            rel = rel.replace("\\", "/")
            return rel.startswith("database/")

        if connector_id in connector_by_id:
            ex_rel = rel_by_id.get(connector_id, "")
            if is_legacy(ex_rel) and not is_legacy(rel_dir):
                connector_by_id[connector_id] = p
                rel_by_id[connector_id] = rel_dir
            # else keep existing (stable)
            continue

        connector_by_id[connector_id] = p
        rel_by_id[connector_id] = rel_dir

    # Compose YAML (handwritten minimal; avoids adding a dependency)
    lines = []
    lines.append("# Auto-generated Docker Compose file for MCP Connectors")
    lines.append("# Generated by scripts/mcp_generate_compose.py")
    lines.append("# Project: rsync-ai-mcp (shows as separate group in Docker Desktop)")
    lines.append("# DO NOT EDIT MANUALLY - changes will be overwritten")
    lines.append("")
    lines.append("name: rsync-ai-mcp")
    lines.append("services:")

    def _resolve_current_version(connector_dir: Path) -> str:
        latest_path = connector_dir / "latest.json"
        latest = json.loads(latest_path.read_text())
        cv = (latest.get("current_version") or "").strip()
        if not cv:
            # Support legacy internal format defensively, even though we skip internal connectors.
            cv = (latest.get("path") or "").strip().removeprefix("versions/").strip()
        if not cv:
            cv = (latest.get("version") or "").strip()
        if not cv:
            raise ValueError(f"{connector_dir.name}: missing current_version in latest.json")
        if not cv.startswith("v"):
            cv = f"v{cv}"
        return cv

    connector_dirs: list[Path] = [connector_by_id[k] for k in sorted(connector_by_id.keys())]

    for connector_dir in connector_dirs:
        md = _load_metadata(_resolve_current_dir(connector_dir) / "metadata.json")
        connector_id = (md.get("id") or md.get("connector_type") or connector_dir.name).strip()
        connector_id = connector_id.replace("_", "-").lower().strip()

        cv = _resolve_current_version(connector_dir)
        version_part = cv.lstrip("v").replace(".", "-")
        service_name = f"{connector_id}-v{version_part}-mcp"
        container_name = f"rsync-ai-{connector_id}-v{version_part}-mcp"
        rel = connector_dir.relative_to(REPO_ROOT).as_posix()
        lines.append(f"  {service_name}:")
        lines.append("    build:")
        # Prefer versioned snapshot when it exists; fall back to connector root for
        # connectors that use a flat layout (no versions/ subdirectory).
        versioned_path = connector_dir / "versions" / cv
        if versioned_path.is_dir() and (versioned_path / "Dockerfile").exists():
            lines.append(f"      context: ./{rel}/versions/{cv}")
        else:
            lines.append(f"      context: ./{rel}")
        lines.append("      dockerfile: Dockerfile")
        # Shared Python libs (rsync_protocol/, warehouse_adapters.py) live ONCE at
        # the public/ root. Expose that dir as a BuildKit named context so each
        # connector image pulls them at build time via `COPY --from=shared ...`
        # instead of carrying its own physical copy (which drifts — the same bug
        # class #184 killed for connector.py). Harmless for connectors that don't
        # reference it. Requires Compose >= 2.17 + BuildKit (both well met here).
        lines.append("      additional_contexts:")
        lines.append(f"        shared: ./{PUBLIC_CONNECTORS_DIR.relative_to(REPO_ROOT).as_posix()}")
        # Pin the built image to the canonical name the JIT/tool-generator launch
        # path expects (`mcp-{id}:v{x.y.z}`, dotted v-prefixed — see
        # llm-service/.../tool_generator/agents/integration.py image_ref). Without
        # this, compose falls back to its default `<project>-<service>:latest`
        # name, which the JIT `docker run` can't find → cold-start fails for every
        # connector that isn't already running. One name across both launch paths.
        lines.append(f"    image: mcp-{connector_id}:{cv}")
        lines.append(f"    container_name: {container_name}")
        lines.append("    labels:")
        # Stable discovery label used by api-gateway to detect running MCP connectors,
        # regardless of which compose project they run under.
        lines.append("      - rsync-ai.mcp=true")
        lines.append(f"      - rsync-ai.connector={connector_id}")
        lines.append(f"      - rsync-ai.connector_version={cv}")
        lines.append("    environment:")
        # Standardized MCP HTTP port (matches connector templates + orchestrator expectations)
        lines.append("      - PORT=8000")
        lines.append("      - MCP_PORT=8000")
        lines.append("      - MCP_HTTP_MODE=true")
        lines.append("      - DOCKER_CONTAINER=true")
        lines.append("      - LOG_FORMAT=json")
        lines.append("      - LOG_LEVEL=info")
        lines.append("      - ENVIRONMENT=docker")
        # Every container that touches Kafka must resolve the SAME topic
        # namespace. debezium computes topic.prefix itself and kafka-mcp-sink
        # subscribes by name, so a connector left on the default while the Go
        # services are pinned (or vice versa) writes and reads different topics
        # -- which raises nothing, it just moves no rows. Harmless for the
        # connectors that never speak Kafka. `-` not `:-`: an explicit empty
        # value means "disabled", and `:-` would turn that back into the default.
        lines.append("      - KAFKA_TOPIC_PREFIX=${KAFKA_TOPIC_PREFIX-rsync.}")
        lines.append("    healthcheck:")
        lines.append("      test: [\"CMD\", \"curl\", \"-f\", \"http://localhost:8000/health\"]")
        lines.append("      interval: 30s")
        lines.append("      timeout: 10s")
        lines.append("      start_period: 10s")
        lines.append("      retries: 3")
        lines.append("    restart: unless-stopped")
        # Least-privilege runtime hardening: connectors process untrusted upstream
        # data, so drop all Linux capabilities and forbid privilege escalation. The
        # image itself already runs as the unprivileged `appuser` (Dockerfile USER).
        lines.append("    cap_drop:")
        lines.append("      - ALL")
        lines.append("    security_opt:")
        lines.append("      - no-new-privileges:true")
        # Resource ceilings, matching the JIT deploy path byte-for-byte
        # (connector-deployer/internal/config/config.go CONNECTOR_MEMORY_LIMIT_MB /
        # CONNECTOR_PIDS_LIMIT). The SAME connector reaches a host two ways -- via
        # this compose file, or spawned on demand by the deployer -- and a limit
        # applied on only one of them is worse than none: the runaway would be
        # bounded in testing and unbounded in the path production actually uses.
        #
        # Short form on purpose: `mem_limit`/`pids_limit` are honoured by the v2
        # plugin AND by the legacy docker-compose v1 binary, which ignores a
        # `deploy:` block outside Swarm. A self-host box may have either.
        lines.append("    mem_limit: ${MCP_MEMORY_LIMIT:-512m}")
        lines.append("    pids_limit: ${MCP_PIDS_LIMIT:-512}")
        # `docker logs <connector>` must work on a customer's own box, and with
        # the fluentd driver it cannot: Docker keeps no local copy, so `docker logs`
        # fails outright with "configured logging driver does not support reading".
        # The generated connectors are the half of the stack a self-host customer
        # actually runs (docker-compose.quickstart.yml ships no fluent-bit at all),
        # so every one of them was shipping its logs to a collector that was not
        # there -- and `fluentd-async: "true"` meant that failed by buffering in
        # memory rather than by refusing to start. Silent on both ends.
        #
        # json-file restores `docker logs`; the rotation options are what keep that
        # from filling the disk, and they are the reason the driver cannot simply be
        # swapped back via env -- fluentd rejects max-size/max-file.
        lines.append("    logging:")
        lines.append("      driver: json-file")
        lines.append("      options:")
        lines.append("        max-size: ${MCP_LOG_MAX_SIZE:-10m}")
        lines.append("        max-file: \"${MCP_LOG_MAX_FILE:-3}\"")
        lines.append("    networks:")
        # EVERY connector must claim the unversioned `rsync-ai-<id>-mcp` hostname.
        # kafka-mcp-sink resolves destinations from a hardcoded candidate list
        # (worker-src/cmd/kafka-sink-worker/main.go destinationHostCandidates) that
        # does not read STACK_PREFIX, so the versioned container_name is
        # unresolvable in an isolated stack. This literal alias is
        # prefix-independent and is what made mysql/postgresql/sqlserver keep
        # working there while mongodb (and 15 others) NXDOMAINed.
        aliases = [f"rsync-ai-{connector_id}-mcp"]
        for a in NETWORK_ALIASES_BY_CONNECTOR_ID.get(connector_id, []):
            if a not in aliases:
                aliases.append(a)
        lines.append("      rsync-network:")
        lines.append("        aliases:")
        for a in aliases:
            lines.append(f"          - {a}")

    lines.append("networks:")
    lines.append("  rsync-network:")
    lines.append("    external: true")
    lines.append("    name: rsync-ai-mcp")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"✅ Wrote {OUT_PATH} with {len(connector_dirs)} user-facing connector services")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


