#!/usr/bin/env python3
"""
AWS S3 MCP Connector
Auto-generated by Pure Agentic Pipeline v1.0

JSON-RPC server for AWS S3 operations.
Category: cloud_storage

DO NOT EDIT - This file is auto-generated. Make changes to the spec instead.
Generated: 2026-01-04T09:11:05.997512
"""

import sys
import os
import logging
from typing import Dict, Any, List, Optional, Union
import json
from datetime import datetime

# Add parent directory for base_connector imports
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
# Make shared protocol modules importable when running from the repo: walk up to
# the public/ root that holds rsync_protocol/ (robust to flat vs category layout —
# the old hardcoded "3 dirnames up" landed on storage/aws-s3, not public/). In the
# container these are provided at /app/rsync_protocol via `COPY --from=shared`
# (see Dockerfile + docker-compose.mcp.yml build.additional_contexts), so this
# loop simply finds nothing and is a harmless no-op there.
_d = os.path.dirname(os.path.abspath(__file__))
while _d != os.path.dirname(_d):
    if os.path.isdir(os.path.join(_d, "rsync_protocol")):
        sys.path.insert(0, _d)
        break
    _d = os.path.dirname(_d)
from base_connector import (
    BaseMCPConnector,
    PaginationHandler,
    ApiHandler,
    StorageHandler,
    DatabaseHandler,
    ExportResult,
    ImportResult,
    ErrorItem,
)
from rsync_protocol.object_storage_source import ObjectStorageSourceMixin

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Pagination safety caps (overrideable per-call)
DEFAULT_MAX_PAGES = 10
DEFAULT_MAX_RECORDS = 10000


class AwsS3MCPServer(ObjectStorageSourceMixin, BaseMCPConnector):
    """MCP Server for AWS S3"""
    
    def __init__(self):
        # MUST call super().__init__() first
        super().__init__()
        
        # REQUIRED: Set connector metadata
        self.connector_type = "aws-s3"
        self.connector_category = "cloud_storage"
        self.supports_source = True
        self.supports_destination = True
        self.supports_cdc = False
        
        # Capability Stats
        self.supported_formats = ['csv', 'tsv', 'json', 'jsonl', 'parquet', 'avro', 'orc', 'arrow', 'xlsx']
        # Move-capability modalities (universal-blob-passthrough plan §2): object
        # storage can move structured records AND opaque bytes (blobs). Distinct from
        # supported_formats (serialization encodings); the orchestrator capability gate
        # reads this to allow/deny a blob (raw-bytes) move into this destination.
        self.supported_modalities = ['structured', 'blob']
        self.max_batch_size = 10000
        

        # Initialize storage handler for contract-driven operations
        self._storage_handler = StorageHandler(connector=self)

        self.log("AWS S3 MCP Server initialized")
    
    # =========================================================================
    # CONFIGURATION HELPERS
    # =========================================================================
    
    def _get_config(self, params: Dict) -> Dict:
        """Extract and validate configuration from params"""
        config = params.get('config', params) if params else {}
        
        # Apply environment variable defaults
        if not config.get('access_key_id'):
            config['access_key_id'] = os.getenv('AWS_S3_ACCESS_KEY_ID', '')
        if not config.get('secret_access_key'):
            config['secret_access_key'] = os.getenv('AWS_S3_SECRET_ACCESS_KEY', '')

        
        return config
    

    def _get_s3_client(self, config: Dict) -> Any:
        """Create an S3 client (AWS S3 or S3-compatible like MinIO via endpoint_url)."""
        import boto3
        from botocore.config import Config as BotoConfig

        endpoint_url = config.get("endpoint_url") or config.get("endpoint") or None
        self._assert_safe_endpoint(endpoint_url)
        region = config.get("region") or "us-east-1"
        access_key = (
            config.get("access_key_id")
            or config.get("aws_access_key_id")
            or config.get("access_key")
        )
        secret_key = (
            config.get("secret_access_key")
            or config.get("aws_secret_access_key")
            or config.get("secret_key")
        )

        if endpoint_url:
            return boto3.client(
                "s3",
                endpoint_url=endpoint_url,
                aws_access_key_id=access_key,
                aws_secret_access_key=secret_key,
                region_name=region,
                config=BotoConfig(signature_version="s3v4", s3={"addressing_style": "path"}),
            )

        return boto3.client(
            "s3",
            aws_access_key_id=access_key,
            aws_secret_access_key=secret_key,
            region_name=region,
            config=BotoConfig(signature_version="s3v4"),
        )

    def list_objects(
        self,
        *,
        config: Dict,
        bucket: str,
        prefix: str = "",
        max_keys: int = 1000,
    ) -> List[Dict[str, Any]]:
        """List objects under bucket/prefix (required by StorageHandler)."""
        s3 = self._get_s3_client(config)

        out: List[Dict[str, Any]] = []
        token: Optional[str] = None

        # list_objects_v2 pagination
        while len(out) < max_keys:
            req = {
                "Bucket": bucket,
                "Prefix": prefix or "",
                "MaxKeys": min(1000, max_keys - len(out)),
            }
            if token:
                req["ContinuationToken"] = token

            resp = s3.list_objects_v2(**req)
            for item in (resp.get("Contents") or []):
                lm = item.get("LastModified")
                out.append(
                    {
                        "key": item.get("Key"),
                        "size": item.get("Size"),
                        "last_modified": lm.isoformat() if hasattr(lm, "isoformat") else str(lm),
                    }
                )
                if len(out) >= max_keys:
                    break

            if not resp.get("IsTruncated"):
                break
            token = resp.get("NextContinuationToken")
            if not token:
                break

        return out

    def download_file(
        self,
        *,
        config: Dict,
        bucket: str,
        key: str,
    ) -> bytes:
        """Download object bytes (required by StorageHandler)."""
        s3 = self._get_s3_client(config)
        resp = s3.get_object(Bucket=bucket, Key=key)
        body = resp.get("Body")
        if body is None:
            return b""
        return body.read()

    # =========================================================================
    # CORE OPERATIONS (Required by BaseMCPConnector)
    # =========================================================================
    
    def get_capabilities(self, params: Dict = None) -> Dict[str, Any]:
        """Return connector capabilities with method keys for auto-dispatch."""
        return {
            "success": True,
            "connector_type": self.connector_type,
            "connector_category": self.connector_category,
            "supports_source": self.supports_source,
            "supports_destination": self.supports_destination,
            "supports_cdc": self.supports_cdc,
            "operations": [
                {
                    "name": "test_connection",
                    "method": "aws-s3_test_connection",
                    "type": "core",
                    "description": "Test connectivity to the data source"
                },
                {
                    "name": "validate_config",
                    "method": "aws-s3_validate_config",
                    "type": "core",
                    "description": "Validate configuration without connecting"
                },
                {
                    "name": "discover_schema",
                    "method": "aws-s3_discover_schema",
                    "type": "core",
                    "description": "Discover available tables/collections and their schemas"
                },
                {
                    "name": "get_capabilities",
                    "method": "aws-s3_get_capabilities",
                    "type": "core",
                    "description": "Return connector capabilities for agent interaction"
                },
                {
                    "name": "read",
                    "method": "aws-s3_read",
                    "type": "source",
                    "description": "Read file from storage"
                },
                {
                    "name": "import_data",
                    "method": "aws-s3_import_data",
                    "type": "destination",
                    "description": "Write data to storage"
                },
                {
                    "name": "write_batch_incremental",
                    "method": "aws-s3_write_batch_incremental",
                    "type": "destination",
                    "description": "Idempotent batch write with manifest/_SUCCESS (append-only)"
                },
                {
                    "name": "write_cdc_raw",
                    "method": "aws-s3_write_cdc_raw",
                    "type": "destination",
                    "description": "Idempotent CDC raw log write with manifest/_SUCCESS (append-only)"
                },
                {
                    "name": "delete_prefix",
                    "method": "aws-s3_delete_prefix",
                    "type": "destination",
                    "description": "Delete all objects under a bucket prefix (guardrailed)"
                },
                {
                    "name": "get_cdc_offsets",
                    "method": "aws-s3_get_cdc_offsets",
                    "type": "destination",
                    "description": "Durable CDC high-water offsets read from this pipeline's object metadata"
                },
            ],
            "capabilities": {
                "max_batch_size": self.max_batch_size,
                "supported_formats": self.supported_formats,
                "supported_modalities": self.supported_modalities,
                "supports_cdc": self.supports_cdc
            }
        }
    
    def validate_config(self, params: Dict = None) -> Dict[str, Any]:
        """Validate configuration without connecting."""
        if not params:
            return {"valid": False, "errors": ["No configuration provided"]}
        
        config = self._get_config(params)
        errors = []
        warnings = []

        
        # Check required fields
        if not config.get('access_key_id'):
            errors.append("Missing required field: access_key_id")
        if not config.get('secret_access_key'):
            errors.append("Missing required field: secret_access_key")
        if not config.get('region'):
            errors.append("Missing required field: region")
        if not config.get('bucket'):
            errors.append("Missing required field: bucket")
        
        return {
            "valid": len(errors) == 0,
            "errors": errors,
            "warnings": warnings
        }
    
    def test_connection(self, params: Dict = None) -> Dict[str, Any]:
        """Test connectivity to AWS S3."""
        config = self._get_config(params)
        
        try:
            # Test cloud storage connectivity (AWS S3 or S3-compatible via optional endpoint_url)
            import boto3
            from botocore.config import Config as BotoConfig

            endpoint_url = config.get("endpoint_url") or config.get("endpoint") or None
            self._assert_safe_endpoint(endpoint_url)
            region = config.get("region") or "us-east-1"
            access_key = (
                config.get("access_key_id")
                or config.get("aws_access_key_id")
                or config.get("access_key")
            )
            secret_key = (
                config.get("secret_access_key")
                or config.get("aws_secret_access_key")
                or config.get("secret_key")
            )

            if endpoint_url:
                s3 = boto3.client(
                    "s3",
                    endpoint_url=endpoint_url,
                    aws_access_key_id=access_key,
                    aws_secret_access_key=secret_key,
                    region_name=region,
                    config=BotoConfig(signature_version="s3v4", s3={"addressing_style": "path"}),
                )
            else:
                s3 = boto3.client(
                    "s3",
                    aws_access_key_id=access_key,
                    aws_secret_access_key=secret_key,
                    region_name=region,
                    config=BotoConfig(signature_version="s3v4"),
                )

            bucket = config.get("bucket") or config.get("bucket_name")
            if bucket:
                s3.head_bucket(Bucket=bucket)
                return {"success": True, "message": f"Connection successful (bucket: {bucket})"}

            # If no bucket provided, at least validate creds can call S3.
            s3.list_buckets()
            return {"success": True, "message": "Connection successful"}
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def read(self, params: Dict = None) -> Dict[str, Any]:
        """Read file from storage"""
        # Cloud storage source operations
        params = params or {}
        prepared = self.prepare_export_data(params)
        if not prepared.get('success'):
            return prepared

        config = prepared.get('config') or {}
        bucket = prepared.get('table') or params.get('bucket') or (config.get('bucket') if isinstance(config, dict) else None)

        if "read" == "read":
            key = (
                params.get("key")
                or params.get("object_key")
                or params.get("objectKey")
                or params.get("path")
            )
            # If a key is provided, download exactly that object.
            if key:
                try:
                    content = self.download_file(config=config, bucket=bucket, key=key)
                    rec = {"key": key, "size": len(content) if hasattr(content, "__len__") else None, "content": content}
                    return ExportResult(success=True, records=[rec], errors=[], stats={"total_files": 1}).to_dict()
                except Exception as e:
                    return {"success": False, "error": str(e)}

            # Otherwise behave like a prefix-based export.
            return self.export(params)

        if "read" == "list":
            prefix = params.get("prefix") or ""
            max_keys = int(params.get("max_keys") or params.get("max_files") or 1000)
            try:
                objs = self.list_objects(config=config, bucket=bucket, prefix=prefix, max_keys=max_keys)
                return {"success": True, "objects": objs, "count": len(objs)}
            except Exception as e:
                return {"success": False, "error": str(e)}

        return {"success": False, "error": "read not implemented"}
    
    # =========================================================================
    # DESTINATION OPERATIONS (REQUIRED)
    # =========================================================================
    
    # Object user-metadata keys the kafka-mcp-sink writes on every CDC object
    # (cdcObjectMetadata in kafka-sink-worker main.go). Keep the two in lockstep.
    CDC_META_PIPELINE_ID = "rsync_pipeline_id"
    CDC_META_TOPIC = "rsync_topic"
    CDC_META_PARTITION = "rsync_partition"
    CDC_META_LAST_OFFSET = "rsync_last_offset"
    # An S3 listing carries no user metadata, so get_cdc_offsets HEADs each object.
    # The scan must answer inside the sink's destination call timeout
    # (RSYNC_SINK_HTTP_TIMEOUT_SECONDS, default 120s) or the sink skips the seed.
    # 10 workers = botocore's default max_pool_connections for one client.
    CDC_OFFSETS_HEAD_WORKERS = 10
    CDC_OFFSETS_HEAD_CHUNK = 1000
    CDC_OFFSETS_TIME_BUDGET_S = 60.0

    @staticmethod
    def _clean_object_metadata(raw: Any) -> Dict[str, str]:
        """S3 user metadata is a flat str→str map; drop anything else."""
        if not isinstance(raw, dict):
            return {}
        out: Dict[str, str] = {}
        for k, v in raw.items():
            key = str(k).strip()
            if not key or v is None or isinstance(v, (dict, list)):
                continue
            out[key] = str(v)
        return out

    def get_cdc_offsets(self, params: Dict) -> Dict[str, Any]:
        """Durable CDC high-water marks for a pipeline (Tier C, cdc-exactly-once-offsets.md §5).

        Same contract as gcs and azure-blob: every CDC object the sink writes carries
        user metadata {rsync_pipeline_id, rsync_topic, rsync_partition,
        rsync_last_offset}; this returns the max last offset per (topic, partition)
        under the pipeline's root (`prefix`, sent by the sink) in the §2.3 shape.

        An S3 listing carries no user metadata, so each listed object costs one HEAD.
        The HEADs run concurrently, newest object first, and stop at a time budget
        (`time_budget_s`, default 60s) or at `max_objects`; either stop sets
        truncated=True. A truncated answer can only be LOW (a max over fewer
        objects): that costs duplicates on a replay, never lost rows, and newest-first
        keeps the objects written since the last Kafka commit inside the answer.
        Sidecars (a leaf starting with "_", e.g. _MANIFEST.json, _SUCCESS) are never
        stamped, so they are not HEADed.

        Never an error (§2.3): first run, a missing prefix/pipeline, or any listing or
        HEAD failure returns {"success": True, "offsets": []}, which the sink treats as
        "nothing to skip".
        """
        import time
        from concurrent.futures import ThreadPoolExecutor

        params = params or {}
        empty: Dict[str, Any] = {"success": True, "offsets": []}
        pipeline_id = str(params.get("pipeline_id") or "").strip()
        try:
            config = self._get_config(params)
        except Exception as e:  # pragma: no cover - _get_config does not raise today
            logger.warning("get_cdc_offsets: bad config (%s); returning no offsets", e)
            return empty
        bucket = str(params.get("bucket") or config.get("bucket") or config.get("bucket_name") or "").strip()
        prefix = str(params.get("prefix") or "").strip().lstrip("/")
        if not pipeline_id or not bucket or not prefix:
            # Refuse to scan a whole bucket: without the pipeline root there is no
            # bounded listing, and a wrong answer is worse than no answer.
            return {**empty, "note": "pipeline_id, bucket and prefix are required to derive offsets"}

        try:
            max_objects = int(params.get("max_objects") or 0)
        except (TypeError, ValueError):
            max_objects = 0
        try:
            budget = float(params.get("time_budget_s") or self.CDC_OFFSETS_TIME_BUDGET_S)
        except (TypeError, ValueError):
            budget = self.CDC_OFFSETS_TIME_BUDGET_S
        deadline = time.monotonic() + budget

        listed = []
        truncated = False
        try:
            s3 = self._get_s3_client(config)
            token = None
            while True:
                req = {"Bucket": bucket, "Prefix": prefix, "MaxKeys": 1000}
                if token:
                    req["ContinuationToken"] = token
                resp = s3.list_objects_v2(**req)
                for obj in resp.get("Contents") or []:
                    key = str(obj.get("Key") or "")
                    if not key or key.rsplit("/", 1)[-1].startswith("_"):
                        continue
                    lm = obj.get("LastModified")
                    listed.append((lm.timestamp() if hasattr(lm, "timestamp") else 0.0, key))
                if not resp.get("IsTruncated"):
                    break
                token = resp.get("NextContinuationToken")
                if not token or time.monotonic() >= deadline:
                    truncated = True
                    break
        except Exception as e:
            logger.warning("get_cdc_offsets: listing s3://%s/%s failed (%s); returning no offsets",
                           bucket, prefix, e)
            return empty

        listed.sort(reverse=True)
        keys = [k for _, k in listed]
        if max_objects and len(keys) > max_objects:
            keys = keys[:max_objects]
            truncated = True

        def _head(key: str) -> Dict[str, Any]:
            try:
                return s3.head_object(Bucket=bucket, Key=key).get("Metadata") or {}
            except Exception as e:
                code = str(((getattr(e, "response", None) or {}).get("Error") or {}).get("Code") or "")
                if code in ("404", "NoSuchKey", "NotFound"):
                    return {}  # deleted since it was listed
                raise

        best: Dict[tuple, int] = {}
        scanned = 0
        try:
            with ThreadPoolExecutor(max_workers=self.CDC_OFFSETS_HEAD_WORKERS) as pool:
                for i in range(0, len(keys), self.CDC_OFFSETS_HEAD_CHUNK):
                    if time.monotonic() >= deadline:
                        truncated = True
                        break
                    for meta in pool.map(_head, keys[i:i + self.CDC_OFFSETS_HEAD_CHUNK]):
                        scanned += 1
                        if str(meta.get(self.CDC_META_PIPELINE_ID) or "").strip() != pipeline_id:
                            continue
                        topic = str(meta.get(self.CDC_META_TOPIC) or "").strip()
                        if not topic:
                            continue
                        try:
                            partition = int(meta.get(self.CDC_META_PARTITION))
                            last = int(meta.get(self.CDC_META_LAST_OFFSET))
                        except (TypeError, ValueError):
                            continue
                        k = (topic, partition)
                        if k not in best or last > best[k]:
                            best[k] = last
        except Exception as e:
            logger.warning("get_cdc_offsets: HEAD under s3://%s/%s failed (%s); returning no offsets",
                           bucket, prefix, e)
            return empty

        if truncated:
            logger.warning("get_cdc_offsets: s3://%s/%s scan stopped after %d object(s) "
                           "(time budget or max_objects); offsets may be low", bucket, prefix, scanned)
        offsets = [{"topic": t, "partition": p, "offset": o} for (t, p), o in sorted(best.items())]
        return {"success": True, "offsets": offsets, "objects_scanned": scanned, "truncated": truncated}

    def delete_prefix(self, params: Dict) -> Dict[str, Any]:
        """
        Delete every object under a folder prefix, failing closed.

        Contract (pinned by shared/delete_prefix_contract_golden.json; the gcs and
        azure-blob connectors return the same shape):
          {success, deleted, failed, complete, bucket, prefix, errors[, error]}
        - success is True only when complete is True and failed == 0.
        - complete is True only when the listing was walked to its end.
        - The prefix is a folder: 'a/b' is normalised to 'a/b/', so 'a/bc/...'
          is never listed or deleted.
        - Pages are bounded: at most 1000 keys per list and per delete call, and at
          most max_pages pages. Stopping at max_pages or max_objects with objects
          still listed is complete=False, success=False -- never a silent truncation.
        - A key the store refuses to delete is counted in failed, never in deleted.

        Guardrails:
        - prefix must name a folder (refuse deleting the entire bucket)
        - if config includes path_prefix/prefix, refuse deletes outside that folder
        """
        params = params or {}
        config = self._get_config(params)

        bucket = params.get("bucket") or config.get("bucket")
        raw_prefix = params.get("prefix") or params.get("key_prefix") or params.get("path") or ""
        result: Dict[str, Any] = {
            "success": False, "deleted": 0, "failed": 0, "complete": False,
            "bucket": bucket, "prefix": raw_prefix, "errors": [],
        }
        if bucket is None or str(bucket).strip() == "":
            result["error"] = "Bucket is required"
            return result
        if str(raw_prefix).strip().strip("/") == "":
            result["error"] = "prefix is required (refusing to delete entire bucket)"
            return result

        # Folder boundary: 'a/b' must never match 'a/bc/...'.
        prefix = str(raw_prefix).strip()
        if not prefix.endswith("/"):
            prefix += "/"
        result["prefix"] = prefix

        # Guardrail: refuse deletes outside the configured base folder (if provided).
        base_prefix = (config.get("path_prefix") or config.get("prefix") or "").strip().strip("/")
        if base_prefix and not prefix.lstrip("/").startswith(base_prefix + "/"):
            result["error"] = (
                f"Refusing to delete outside configured path_prefix/prefix '{base_prefix}' "
                f"(requested '{raw_prefix}')"
            )
            return result

        page_size = 1000
        try:
            max_pages = int(params.get("max_pages") or 100000)
            max_objects = int(params.get("max_objects") or 0) or None
        except (TypeError, ValueError):
            result["error"] = "max_pages and max_objects must be integers"
            return result

        def _fail_key(key: Any, err: Any) -> None:
            result["failed"] += 1
            if len(result["errors"]) < 20:
                result["errors"].append({"key": key, "error": str(err)[:300]})

        try:
            s3 = self._get_s3_client(config)
            token: Optional[str] = None
            pages = 0
            while True:
                if pages >= max_pages:
                    result["error"] = f"stopped after max_pages={max_pages} before the listing ended"
                    return result
                req: Dict[str, Any] = {"Bucket": bucket, "Prefix": prefix, "MaxKeys": page_size}
                if token:
                    req["ContinuationToken"] = token
                resp = s3.list_objects_v2(**req)
                pages += 1
                keys = [
                    item.get("Key") for item in (resp.get("Contents") or [])
                    if item.get("Key") and str(item.get("Key")).startswith(prefix)
                ]

                over_bound = False
                if max_objects is not None:
                    room = max(max_objects - (result["deleted"] + result["failed"]), 0)
                    if len(keys) > room:
                        keys = keys[:room]
                        over_bound = True

                if keys:
                    try:
                        del_resp = s3.delete_objects(
                            Bucket=bucket, Delete={"Objects": [{"Key": k} for k in keys], "Quiet": True}
                        )
                    except Exception as e:
                        for k in keys:
                            _fail_key(k, e)
                        result["error"] = f"delete_objects failed: {e}"
                        return result
                    errs = (del_resp or {}).get("Errors") or []
                    for err in errs:
                        _fail_key(err.get("Key"), f"{err.get('Code')}: {err.get('Message')}")
                    refused = {err.get("Key") for err in errs}
                    result["deleted"] += sum(1 for k in keys if k not in refused)

                if over_bound:
                    result["error"] = f"stopped at max_objects={max_objects} with objects left under the prefix"
                    return result

                if not resp.get("IsTruncated"):
                    result["complete"] = True
                    break
                next_token = resp.get("NextContinuationToken")
                if not next_token or next_token == token:
                    result["error"] = "listing reported more objects but returned no new continuation token"
                    return result
                token = next_token
        except Exception as e:
            result["error"] = str(e)
            return result

        if result["failed"]:
            result["error"] = f"{result['failed']} object(s) under the prefix could not be deleted"
        result["success"] = result["complete"] and result["failed"] == 0
        return result

    def _object_exists(self, s3, bucket: str, key: str) -> bool:
        try:
            s3.head_object(Bucket=bucket, Key=key)
            return True
        except Exception:
            return False

    def write_batch_incremental(self, params: Dict) -> Dict[str, Any]:
        """
        Write an idempotent batch increment to S3/MinIO using two-phase commit:
        - Upload data files under a pending prefix
        - Publish manifest.json and _SUCCESS under a committed prefix
        """
        import tempfile
        import json as _json

        from rsync_protocol.file_formats import iter_jsonl_bytes, try_write_parquet_to_file
        from rsync_protocol.manifest import (
            ManifestObject,
            build_batch_manifest,
            manifest_key,
            manifest_success_key,
            pending_prefix,
        )

        params = params or {}
        config = self._get_config(params)
        bucket = (params.get("bucket") or config.get("bucket") or "").strip()
        if not bucket:
            return {"success": False, "error": "Missing bucket"}

        stream_id = (params.get("stream_id") or params.get("stream") or "").strip()
        batch_id = (params.get("batch_id") or params.get("run_id") or "").strip()
        if not stream_id or not batch_id:
            return {"success": False, "error": "Missing stream_id/batch_id"}

        base_prefix = (
            params.get("base_prefix")
            or params.get("prefix")
            or params.get("path_prefix")
            or config.get("path_prefix")
            or ""
        ).strip()
        file_format = (params.get("file_format") or params.get("format") or config.get("file_format") or "parquet").strip().lower()
        compression = (params.get("compression") or config.get("compression") or "none").strip().lower()

        data = params.get("data") or params.get("rows") or []
        if not isinstance(data, list):
            data = [data]

        s3 = self._get_s3_client(config)
        mkey = manifest_key(base_prefix, stream_id, batch_id)
        if self._object_exists(s3, bucket, mkey):
            return {"success": True, "message": "Batch already committed", "bucket": bucket, "manifest_key": mkey}

        pend = pending_prefix(base_prefix, stream_id, batch_id)
        objects = []
        stats = {"rows": len(data)}

        part_ext = "parquet" if file_format == "parquet" else "jsonl"
        part_key = f"{pend}/part-00000.{part_ext}"

        if file_format == "parquet":
            with tempfile.NamedTemporaryFile(suffix=".parquet", delete=True) as tf:
                bytes_written = try_write_parquet_to_file(tf.name, data)
                if bytes_written is None:
                    file_format = "jsonl"
                else:
                    with open(tf.name, "rb") as rf:
                        body = rf.read()
                    s3.put_object(Bucket=bucket, Key=part_key, Body=body, ContentType="application/octet-stream")
                    objects.append(ManifestObject(key=part_key, size_bytes=len(body)))

        if file_format != "parquet":
            body = b"".join(iter_jsonl_bytes(data))
            s3.put_object(Bucket=bucket, Key=part_key, Body=body, ContentType="application/x-ndjson")
            objects.append(ManifestObject(key=part_key, size_bytes=len(body)))

        manifest = build_batch_manifest(
            stream_id=stream_id,
            batch_id=batch_id,
            file_format=file_format,
            compression=compression,
            schema=params.get("schema"),
            objects=objects,
            stats=stats,
            extra={"mode": "batch_incremental"},
        )
        mbody = _json.dumps(manifest, default=str).encode("utf-8")
        s3.put_object(Bucket=bucket, Key=mkey, Body=mbody, ContentType="application/json")
        skey = manifest_success_key(base_prefix, stream_id, batch_id)
        s3.put_object(Bucket=bucket, Key=skey, Body=b"", ContentType="text/plain")

        return {
            "success": True,
            "bucket": bucket,
            "manifest_key": mkey,
            "success_key": skey,
            "objects": [o.to_dict() for o in objects],
        }

    def write_cdc_raw(self, params: Dict) -> Dict[str, Any]:
        """
        Write CDC raw log events as JSONL with idempotent commit markers.
        """
        import json as _json

        from rsync_protocol.event_order import extract_debezium_event_order
        from rsync_protocol.file_formats import iter_jsonl_bytes
        from rsync_protocol.manifest import (
            ManifestObject,
            build_batch_manifest,
            manifest_key,
            manifest_success_key,
            pending_prefix,
        )

        params = params or {}
        config = self._get_config(params)
        bucket = (params.get("bucket") or config.get("bucket") or "").strip()
        if not bucket:
            return {"success": False, "error": "Missing bucket"}

        stream_id = (params.get("stream_id") or params.get("stream") or "").strip()
        batch_id = (params.get("batch_id") or params.get("run_id") or "").strip()
        if not stream_id or not batch_id:
            return {"success": False, "error": "Missing stream_id/batch_id"}

        base_prefix = (
            params.get("base_prefix")
            or params.get("prefix")
            or params.get("path_prefix")
            or config.get("path_prefix")
            or ""
        ).strip()

        s3 = self._get_s3_client(config)
        mkey = manifest_key(base_prefix, stream_id, batch_id)
        if self._object_exists(s3, bucket, mkey):
            return {"success": True, "message": "Batch already committed", "bucket": bucket, "manifest_key": mkey}

        events = params.get("events") or params.get("data") or []
        if not isinstance(events, list):
            events = [events]

        enriched = []
        for ev in events:
            if isinstance(ev, dict):
                eo = extract_debezium_event_order(ev)
                row = dict(ev)
                row.setdefault("_rsync_event_order", eo.to_dict())
                enriched.append(row)

        pend = pending_prefix(base_prefix, stream_id, batch_id)
        part_key = f"{pend}/events-00000.jsonl"
        body = b"".join(iter_jsonl_bytes(enriched))
        s3.put_object(Bucket=bucket, Key=part_key, Body=body, ContentType="application/x-ndjson")
        objects = [ManifestObject(key=part_key, size_bytes=len(body))]

        manifest = build_batch_manifest(
            stream_id=stream_id,
            batch_id=batch_id,
            file_format="jsonl",
            compression="none",
            schema=params.get("schema"),
            objects=objects,
            stats={"events": len(enriched)},
            extra={"mode": "cdc_raw"},
        )
        mbody = _json.dumps(manifest, default=str).encode("utf-8")
        s3.put_object(Bucket=bucket, Key=mkey, Body=mbody, ContentType="application/json")
        skey = manifest_success_key(base_prefix, stream_id, batch_id)
        s3.put_object(Bucket=bucket, Key=skey, Body=b"", ContentType="text/plain")

        return {
            "success": True,
            "bucket": bucket,
            "manifest_key": mkey,
            "success_key": skey,
            "objects": [o.to_dict() for o in objects],
        }

    def import_data(self, params: Dict) -> Dict[str, Any]:
        """
        Import data to the destination.
        REQUIRED by BaseMCPConnector abstract class.
        """
        # Cloud storage import
        params = params or {}

        # Blob (raw-bytes passthrough) write — universal-blob-passthrough plan §3.
        # A blob copy hands us a claim-check pointer (data_ref) + the destination key
        # + the source content-type. Fetch the staged bytes, verify integrity, and
        # write them BYTE-IDENTICAL — bypassing the row-oriented prepare/convert path
        # so the source MIME is carried verbatim and a binary/NUL object is never
        # JSON-serialized.
        if (params.get("blob") or params.get("is_blob")) and params.get("data_ref"):
            try:
                import boto3
                from botocore.config import Config as BotoConfig
                body, bucket, key, content_type = self._prepare_blob_write(params)
                config = self._get_config({"config": params.get("config") or {}})
                endpoint_url = config.get("endpoint_url") or config.get("endpoint") or None
                self._assert_safe_endpoint(endpoint_url)
                region = config.get("region") or "us-east-1"
                access_key = (
                    config.get("access_key_id")
                    or config.get("aws_access_key_id")
                    or config.get("access_key")
                )
                secret_key = (
                    config.get("secret_access_key")
                    or config.get("aws_secret_access_key")
                    or config.get("secret_key")
                )
                if endpoint_url:
                    s3 = boto3.client(
                        "s3", endpoint_url=endpoint_url,
                        aws_access_key_id=access_key, aws_secret_access_key=secret_key,
                        region_name=region,
                        config=BotoConfig(signature_version="s3v4", s3={"addressing_style": "path"}),
                    )
                    try:
                        s3.head_bucket(Bucket=bucket)
                    except Exception:
                        try:
                            s3.create_bucket(Bucket=bucket)
                        except Exception:
                            pass
                else:
                    s3 = boto3.client(
                        "s3", aws_access_key_id=access_key, aws_secret_access_key=secret_key,
                        region_name=region, config=BotoConfig(signature_version="s3v4"),
                    )
                s3.put_object(Bucket=bucket, Key=key, Body=body, ContentType=content_type)
                return {
                    "success": True, "bytes_written": len(body),
                    "metadata": {"bucket": bucket, "key": key,
                                 "content_type": content_type, "modality": "blob"},
                }
            except Exception as e:
                return {"success": False, "error": str(e)}

        # Claim-check support: if we received data_ref but not data, fetch from staging.
        data = params.get("data") or params.get("rows") or params.get("source_data")
        data_ref = params.get("data_ref")
        if data_ref and (data is None or (isinstance(data, list) and len(data) == 0)):
            staging_config = params.get("staging_config") or params.get("config") or {}
            staging_result = self.read_from_staging(data_ref, staging_config)
            if not staging_result.get("success"):
                return {"success": False, "error": f"Failed to fetch data from staging: {staging_result.get('error', 'Unknown error')}"}
            data = staging_result.get("data")

        # Use destination helper to compute bucket/key/format/compression with proper precedence.
        params_for_dest = dict(params)
        if data is not None:
            params_for_dest["data"] = data
        prepared = self.prepare_destination_params(params_for_dest)

        config = self._get_config({"config": prepared.get("config") or {}})
        bucket = prepared.get("bucket") or config.get("bucket")
        key = prepared.get("key")
        payload = prepared.get("data")
        fmt = prepared.get("format") or "json"
        compression = prepared.get("compression") or "none"
        content_type = prepared.get("content_type") or "application/octet-stream"

        if not bucket or not key:
            return {"success": False, "error": "Bucket and key are required"}
        if payload is None:
            return {"success": False, "error": "Missing 'data' payload"}

        try:
            import boto3
            from botocore.config import Config as BotoConfig

            endpoint_url = config.get("endpoint_url") or config.get("endpoint") or None
            self._assert_safe_endpoint(endpoint_url)
            region = config.get("region") or "us-east-1"
            access_key = (
                config.get("access_key_id")
                or config.get("aws_access_key_id")
                or config.get("access_key")
            )
            secret_key = (
                config.get("secret_access_key")
                or config.get("aws_secret_access_key")
                or config.get("secret_key")
            )

            if endpoint_url:
                s3 = boto3.client(
                    "s3",
                    endpoint_url=endpoint_url,
                    aws_access_key_id=access_key,
                    aws_secret_access_key=secret_key,
                    region_name=region,
                    config=BotoConfig(signature_version="s3v4", s3={"addressing_style": "path"}),
                )
                # Best-effort bucket create for S3-compatible endpoints (e.g. MinIO)
                try:
                    s3.head_bucket(Bucket=bucket)
                except Exception:
                    try:
                        s3.create_bucket(Bucket=bucket)
                    except Exception:
                        pass
            else:
                s3 = boto3.client(
                    "s3",
                    aws_access_key_id=access_key,
                    aws_secret_access_key=secret_key,
                    region_name=region,
                    config=BotoConfig(signature_version="s3v4"),
                )

            raw = bool(params.get("raw") or params.get("raw_data") or params.get("raw_bytes"))
            if raw:
                # Raw mode: write payload bytes as-is (used for _MANIFEST.json and _SUCCESS markers)
                if payload is None:
                    body = b""
                elif isinstance(payload, (bytes, bytearray)):
                    body = bytes(payload)
                else:
                    body = str(payload).encode("utf-8")
            else:
                body = self.convert_data_to_format(payload, fmt, compression)
            put_args = {"Bucket": bucket, "Key": key, "Body": body, "ContentType": content_type}
            # CDC provenance (Tier C): the kafka-mcp-sink stamps each CDC object with its
            # pipeline + Kafka coordinates so get_cdc_offsets can recover the durable
            # high-water mark. Sent with the PUT so it lands atomically with the bytes.
            object_metadata = self._clean_object_metadata(params.get("object_metadata"))
            if object_metadata:
                put_args["Metadata"] = object_metadata
            s3.put_object(**put_args)

            return {
                "success": True,
                "rows_inserted": len(payload) if isinstance(payload, list) else 1,
                "bytes_written": len(body),
                "metadata": {"bucket": bucket, "key": key, "format": fmt, "compression": compression},
            }
        except Exception as e:
            return {"success": False, "error": str(e)}
    


    # DO NOT implement handle_request, _handle_tool_call, run, or list_tools
    # The base class handles these automatically!


# =============================================================================
# HTTP SERVER MODE (for Docker deployment)
# =============================================================================

def create_http_app():
    """Create FastAPI app for HTTP-based MCP server"""
    from fastapi import FastAPI, HTTPException
    # Decimal crosses this boundary as a STRING, never a float. FastAPI's
    # jsonable_encoder maps Decimal -> float (ENCODERS_BY_TYPE), which silently
    # destroys precision on the way to the sink: a numeric 123456789012345678.5
    # arrives as 1.2345678901234568e+17, and the orchestrator writes that back
    # out as 123456789012345680 -- a changed value, with no error raised anywhere.
    # The stdio path already serialises with json.dumps(..., default=str), so
    # HTTP mode was the only lossy leg -- and it is the leg every containerised
    # deployment uses, which is why no stdio-based test could ever see it.
    from decimal import Decimal as _Decimal
    from fastapi.encoders import ENCODERS_BY_TYPE as _ENCODERS_BY_TYPE
    _ENCODERS_BY_TYPE[_Decimal] = str
    from pydantic import BaseModel
    from typing import Optional, Any
    
    runtime_version = os.getenv("MCP_CONNECTOR_VERSION") or os.getenv("CONNECTOR_VERSION") or "1.0.0"
    runtime_version = str(runtime_version).strip()
    if runtime_version and not runtime_version.startswith("v"):
        runtime_version = f"v{runtime_version}"

    app = FastAPI(
        title="AWS S3 MCP Connector",
        description="Connector for AWS S3 cloud storage service, allowing operations on buckets and objects.",
        version=runtime_version or "1.0.0"
    )
    
    server = AwsS3MCPServer()
    
    class MCPRequest(BaseModel):
        """MCP JSON-RPC request (full envelope)"""
        jsonrpc: str = "2.0"
        id: Optional[int] = None
        method: str
        params: Optional[dict] = None
    
    class LegacyMCPRequest(BaseModel):
        """Legacy MCP request format (backward compatibility)"""
        method: str
        params: Optional[dict] = None
    
    @app.get("/health")
    async def health():
        return {
            "status": "healthy",
            "connector": server.connector_type,
            "version": runtime_version or "1.0.0",
        }
    
    @app.post("/mcp")
    async def mcp_handler(request: Union[MCPRequest, LegacyMCPRequest, Dict]):
        """Handle MCP JSON-RPC requests over HTTP (supports full envelope or legacy format)"""
        try:
            # Normalize to full JSON-RPC envelope
            if isinstance(request, dict):
                request_dict = request
            else:
                request_dict = request.dict() if hasattr(request, 'dict') else request.model_dump()
            
            # If legacy format (no jsonrpc field), wrap it
            if "jsonrpc" not in request_dict:
                request_dict = {
                    "jsonrpc": "2.0",
                    "id": 1,
                    "method": request_dict.get("method"),
                    "params": request_dict.get("params") or {}
                }
            
            result = server.handle_request(request_dict)
            return result
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
    @app.post("/invoke/{tool_name}")
    async def invoke_tool(tool_name: str, params: dict = {}):
        """Direct tool invocation endpoint"""
        try:
            # Map tool names to methods
            method_name = tool_name.replace("-", "_")
            # Security: this route bypasses _handle_tool_call, so it needs its own
            # copy of that dispatcher's guard. Without it a crafted name like
            # "_cleanup_worker" resolves via getattr and exposes internals to any
            # caller that can reach the container. Tool handlers are always public.
            if method_name.startswith("_"):
                raise HTTPException(status_code=404, detail=f"Tool not found: {tool_name}")
            if hasattr(server, method_name):
                method = getattr(server, method_name)
                return method(params)
            
            # Try with connector prefix
            prefixed = f"aws-s3_{method_name}"
            if hasattr(server, prefixed):
                method = getattr(server, prefixed)
                return method(params)
            
            raise HTTPException(status_code=404, detail=f"Tool not found: {tool_name}")
        except HTTPException:
            raise
        except Exception as e:
            raise HTTPException(status_code=500, detail=str(e))
    
    @app.get("/capabilities")
    async def get_capabilities():
        return server.get_capabilities()
    
    @app.post("/test_connection")
    async def test_connection(params: dict = {}):
        return server.test_connection(params)
    
    @app.post("/validate_config")
    async def validate_config(params: dict = {}):
        return server.validate_config(params)
    
    @app.post("/discover_schema")
    async def discover_schema(params: dict = {}):
        return server.discover_schema(params)
    
    return app


if __name__ == "__main__":
    import os
    
    # Check if running in HTTP mode (Docker)
    http_mode = os.getenv("MCP_HTTP_MODE", "false").lower() == "true"
    port = int(os.getenv("MCP_PORT", os.getenv("PORT", "8000")))
    
    if http_mode or os.getenv("DOCKER_CONTAINER"):
        # HTTP mode for Docker
        import uvicorn
        app = create_http_app()
        logger.info(f"🚀 Starting AWS S3 MCP Server in HTTP mode on port {port}")
        uvicorn.run(app, host="0.0.0.0", port=port)
    else:
        # Stdio mode for local/CLI usage
        server = AwsS3MCPServer()
        server.run()

